### ISSUE TITLE
Distinguish production environment from others

### ISSUE THREAD

**Issue by jetaggart** [jnunemaker/flipper#101]
One useful trick we use in production is to have a banner, or some sort of distinguishing color/banner/icon/popup that indicates that you are making changes to production. What do you all think about adding something similar to Flipper? It's definitely helpful to prevent mistakes from happening.

**Comment by jetaggart** [comment]
IRT, Flipper UI.

**Comment by jnunemaker** [comment]
We do the same at GitHub. Seems like a good idea. I haven't thought through how it would work or where it would go, but a PR would definitely activate my spidey sense. :)

**Comment by blunderdome** [comment]
We'd be happy to see this
