### ISSUE TITLE
Disable a boolean gate via the UI would auto-remove it

### ISSUE THREAD

**Issue by raysegantii** [jnunemaker/flipper#104]
It's cause: https://github.com/jnunemaker/flipper/commit/ec711815 -- the feature, boolean gate, is gone once I press Disable and then leave the page. I would have to re-add the feature although I simply want to disable it for awhile for experiment.

What was the reason to introduce that commit? Would it be reverted?

**Comment by jnunemaker** [comment]
Adapters should only remove the gate values, not the entire feature. I'm guessing this is based on the adapter you are using. As I look, I don't have an explicit test in the shared specs for that and some of the core adapters would fail if so. I'll get a test added and update the core adapters to correct that. 

Which adapter were you using?

**Comment by raysegantii** [comment]
I'm using the ActiveRecord, is there something wrong with it for handling boolean flag?

**Comment by jnunemaker** [comment]
Hmm, no the AR adapter explicitly only clears the gate values, not the feature.
https://github.com/jnunemaker/flipper/blob/4c6a9978940e0f7b097e51df153c4cac49f141c8/lib/flipper/adapters/active_record.rb#L66

When you say AR adapter, do you mean the core one I support or one of the community ones that exist?

**Comment by jnunemaker** [comment]
It looks like flipper activerecord handles the gate clearing incorrectly, if you are using that.
https://github.com/bgentry/flipper-activerecord/blob/cbdc8ab4ec57799343a6c8a9c2192f6bd87bc3d8/lib/flipper/adapters/activerecord.rb#L38

They delete the entire feature.
