### ISSUE TITLE
Overriding templates for flipper-ui

### ISSUE THREAD

**Issue by tarebyte** [jnunemaker/flipper#109]
Hi @jnunemaker :wave: 

We're currently adding flipper to Classroom for GitHub https://github.com/education/classroom/pull/474, and I was trying to figure out how to override the `flipper-ui` views.

Is there a way to do this?

My attempt at doing it myself was rather unsuccessful.

I tried to override adding to the Rails `lib` directory `/lib/flipper-ui/flipper/lib/views/layout.erb`, but I was unsuccessful.

Any help would be much appreciated!

**Comment by jnunemaker** [comment]
Overriding the views is not possible as this is built as a rack middleware, not a rails engine, so it can be used with any web framework, instead of just rails. What is the goal you are trying to accomplish in overriding the template?

**Comment by tarebyte** [comment]
@jnunemaker since we already have primer and markup already done I wanted to build it into Classroom to make it feel like it is apart of the app.

If that's the case, I will probably just build the functionality we need inside Classroom itself. Or make a rails engine `flipper-rails`? and throw it in.

**Comment by jnunemaker** [comment]
Gotcha. In general, I worry less about it feeling apart of the application and more about saving the time of having to recreate it all but to each their own! I'll close this out. Thanks for the discussion.
