### ISSUE TITLE
[Fipper UI] Assets are not loaded correctly using Rails 4.2 and NGINX 

### ISSUE THREAD

**Issue by bfagundez** [jnunemaker/flipper#112]
I can see all assets loading fine on development, but on production they do not work.
The routes of the assets seem static (no MD5 fingerprint) I suppose that is fine, but for some reason they are not loaded.
I tried running `assets:precompile` and I don't see anything of flipper-ui there.
I also tried running a fresh rails app with `RAILS_ENV=production` and it worked, so the problem must be between NGINX and the flipper-ui gem.

I have this rule:
```
location ^~ /assets/ {
      gzip_static on;
      expires max;
      add_header Cache-Control public;
    }
```

But there's nothing from flipper-ui on assets so I think that may be the problem.

Rails 4.2.4
flipper and flipper-ui 0.7.2

**Comment by jnunemaker** [comment]
Flipper serves assets through rack static file.

https://github.com/jnunemaker/flipper/blob/a4e11c5195ae576a43c31925cac564f267ee59b6/lib/flipper/ui/middleware.rb#L51
https://github.com/jnunemaker/flipper/blob/a4e11c5195ae576a43c31925cac564f267ee59b6/lib/flipper/ui/actions/file.rb#L12

The asset pipeline is not involved. The routes for flipper static files are defined here:
https://github.com/jnunemaker/flipper/blob/a4e11c5195ae576a43c31925cac564f267ee59b6/lib/flipper/ui/actions/file.rb#L9

None of them are prefixed with assets so that nginx declaration won't affect them.

Can you describe what you mean by "they do not work". Is the page missing css and images? If you look at network timeline are they loading but with incorrect mime types? Are they not loading at all? Can they not be found?

**Comment by bfagundez** [comment]
I get 404s of all assets, so the page loads without styles/js

**Comment by jnunemaker** [comment]
I'm kind of at a loss. Flipper uses only rack (nothing from rails) so that is why it behaves differently than active admin (which is a rails engine or something along those lines). I've not had any other reports of this and I've never experienced it myself. Could you provide any of the flipper related bits from your app here so I could at least check those?

**Comment by bfagundez** [comment]
OK, so on the Gemfile I got :
```
gem 'flipper', '~> 0.7.3'
gem 'flipper-ui'
gem 'flipper-active_record'
```

I'm using the active_record adapter

I have the following flipper initializer:
```
require 'flipper'
require 'flipper/adapters/active_record'

#modify these constants to programmatically add a feature and set it's default state
#in the environment, the feature's state is persisted via ActiveRecord
DISABLED_FEATURES = %w(user_login srp_blacklisting )
ENABLED_FEATURES = %w()

FlipperFeatures = Flipper::Adapters::ActiveRecord::Feature

#purpose of this is to create a way for creating a default state for each feature
#while at the same time retaining persisted state if a feature already exists
class FlipperDefault
  def initialize(global_flipper,key,default_state = "disable")
    #if a key is found in the database then it will use the existing state (do nothing)
    #otherwise, create the feature and use the default state
    raise "FlipperDefault: Unsupported default state of #{default_state.inspect}" unless default_state == :disable || default_state == :enable
    feature = FlipperFeatures.where(key:key).first
    if feature.blank?
      global_flipper[key].send(default_state)
      Rails.logger.debug "Flipper feature #{key} created and set to #{default_state}"
    end
    Rails.logger.debug "Flipper feature: #{global_flipper[key].inspect}}"
  end
end

class FlipperIniter
  FEATURES = {:disable => DISABLED_FEATURES, :enable =>  ENABLED_FEATURES}
  attr_accessor :it

  def initialize
    adapter = Flipper::Adapters::ActiveRecord.new
    @it = Flipper.new(adapter)
    FEATURES.each_pair do |default_state, key_ary|
      key_ary.each{ |key| FlipperDefault.new(@it, key , default_state)  }
    end
  end
end

#this conditional protects the code in the initializer from breaking when
#migrations to create the flipper_features table have not yet been run
$flipper = FlipperIniter.new.it  if  ActiveRecord::Base.connection.table_exists? 'flipper_features'
```

and I have the flipper ui mounted to `/admin/flipper` behind active_admin auth:

```
Rails.application.routes.draw do
  authenticate :admin_user do
    mount Flipper::UI.app($flipper), at: '/admin/flipper'
  end
end
```

**Comment by bfagundez** [comment]
Another interesting detail is that if I change the route to:
```
Rails.application.routes.draw do
   mount Flipper::UI.app($flipper), at: '/flipper'
end
```

I get a 404 directly. No access at all to the dashboard.

**Comment by bfagundez** [comment]
There was a problem with NGINX conf. Flipper has nothing to do with it.
I had the following:
```
    root /home/ubuntu/deploys/current/public;

    location ^~ /assets/ {
      gzip_static on;
      expires max;
      add_header Cache-Control public;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires       max;
        log_not_found off;
    }
```
And that was overriding every single resource load and asking nginx for the file from the filesystem.

After replacing it with:
```

    location ^~ /assets/ {
      gzip_static on;
      expires max;
      add_header Cache-Control public;
      root /home/ubuntu/deploys/current/public;
    }
```

Flipper resources are loaded OK, and assets as well.
Thanks for reaching out @jnunemaker

**Comment by jnunemaker** [comment]
:cool:

**Comment by timvoet** [comment]
does anyone know what could be causing the same issue on an apache2 configuration?

**Comment by DizzyNYC** [comment]
> There was a problem with NGINX conf. Flipper has nothing to do with it.
> I had the following:
> 
> ```
>     root /home/ubuntu/deploys/current/public;
> 
>     location ^~ /assets/ {
>       gzip_static on;
>       expires max;
>       add_header Cache-Control public;
>     }
> 
>     location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
>         expires       max;
>         log_not_found off;
>     }
> ```
> 
> And that was overriding every single resource load and asking nginx for the file from the filesystem.
> 
> After replacing it with:
> 
> ```
> 
>     location ^~ /assets/ {
>       gzip_static on;
>       expires max;
>       add_header Cache-Control public;
>       root /home/ubuntu/deploys/current/public;
>     }
> ```
> 
> Flipper resources are loaded OK, and assets as well.
> Thanks for reaching out @jnunemaker

Hey! Looks like this problem was years ago for you. Hope you still have some insight. Why did this change only affect your Production env?

**Comment by timvoet** [comment]
> > There was a problem with NGINX conf. Flipper has nothing to do with it.
> > I had the following:
> > ```
> >     root /home/ubuntu/deploys/current/public;
> > 
> >     location ^~ /assets/ {
> >       gzip_static on;
> >       expires max;
> >       add_header Cache-Control public;
> >     }
> > 
> >     location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
> >         expires       max;
> >         log_not_found off;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And that was overriding every single resource load and asking nginx for the file from the filesystem.
> > After replacing it with:
> > ```
> > 
> >     location ^~ /assets/ {
> >       gzip_static on;
> >       expires max;
> >       add_header Cache-Control public;
> >       root /home/ubuntu/deploys/current/public;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Flipper resources are loaded OK, and assets as well.
> > Thanks for reaching out @jnunemaker
> 
> Hey! Looks like this problem was years ago for you. Hope you still have some insight. Why did this change only affect your Production env?

This issue is new for me.  I just enabled Flipper on a legacy project so that I can slowly release new features without breaking everything.  It's a 5+ year old codebase.

I have no idea what's not working, as I don't have any specific mount points for assets, that could be bypassing requests to the server ( like the example above) I created another issue ( hopefully someone has answers ): [Github issue #545](https://github.com/jnunemaker/flipper/issues/545)
