### ISSUE TITLE
gem version bump?

### ISSUE THREAD

**Issue by camallen** [jnunemaker/flipper#133]
Re: https://github.com/jnunemaker/flipper/pull/126

I'm speccing some changes using flipper and would like to use the remove feature to clear any memoized state, it'd be nice to have this in the gem version.

**Comment by camallen** [comment]
Looks good, thanks for cutting a new gem!

**Comment by jnunemaker** [comment]
Sorry I had overlooked this. Haha. I released, but hadn't noticed this issue yet. :)
