### ISSUE TITLE
Feature Request: toggle feature for user

### ISSUE THREAD

**Issue by joegaudet** [jnunemaker/flipper#145]
A common use case for feature flagging, is to allow users to opt in to a feature.

```Ruby
def toggle
 feature = flipper[:feature]
 if feature.enabled?(current_user)
    feature.disable(current_user)
else
   feature.enable(current_user)
end
```

Would be nice to be able to one liner it.

**Comment by jnunemaker** [comment]
Somehow lost this one. Sorry. I generally avoid toggle methods as they are not deterministic. If two people are viewing the UI, both see someone enabled for a feature that shouldn't be and both click toggle, the first will disable the user and the second will enable. That would be confusing. For this reason I usually recommend just using deterministic methods like enable or disable. In the same example, if two users click disable, the actor will definitely be disabled, which is what both users expect.

**Comment by joegaudet** [comment]
That makes sense, in the case I was thinking it would always be a gate for a single user, so it would be deterministic. That is to say, enabled feature x for me only.
