### ISSUE TITLE
Flipper and before_filter

### ISSUE THREAD

**Issue by krzcho** [jnunemaker/flipper#146]
I have a before_filter that modifies parameters used by flipper to flip features (basically user is able to switch database within before_filter processing)
After such action I need to reload page to see correct features set
How could I refresh flipper's state within before_filter so that features set is correct?
I could probably redirect such action to the same page again but maybe there is other way?

**Comment by AlexWheeler** [comment]
@krzcho The before_filter logic will run before the controller action code and will modify the flipper before you render your view so you should be fine if you modify flipper in your before_filter and then just respond with your view

**Comment by krzcho** [comment]
unfortunately it is not the case for me; maybe some caching is triggering?

**Comment by AlexWheeler** [comment]
Hmm okay, can you provide a bit more info, it might help us figure this one out.  Which adapter are you using? Are you using the memoizing middleware? If possible can you post what your code looks like?

**Comment by krzcho** [comment]
`
require "flipper/adapters/pstore"

Flipper.register(:uae) do |actor|
  actor.shard.to_sym==:uae
end

Flipper.register(:gulf) do |actor|
  actor.shard.to_sym==:gulf
end

Flipper.register(:sa) do |actor|
  actor.shard.to_sym==:sa
end

Flipper.register(:pk) do |actor|
  actor.shard.to_sym==:pk
end

Flipper.register(:lb) do |actor|
  actor.shard.to_sym==:lb
end

Flipper.register(:eg) do |actor|
  actor.shard.to_sym==:eg
end

Flipper.register(:ir) do |actor|
  actor.shard.to_sym==:ir
end

Flipper.register(:is_admin) do |actor|
  actor.is_admin==1
end

Flipper.register(:is_hr) do |actor|
  actor.is_hr==1
end

$flipper = Flipper.new(Flipper::Adapters::PStore.new("flipper-#{Rails.env}.pstore")) 
`

before_filter is modifying a shard of the actor

**Comment by jnunemaker** [comment]
Thanks for providing the groups and other configuration. What does the before filter look like? That is probably the last piece we'd need to see.

**Comment by krzcho** [comment]
`
class ApplicationController < ActionController::Base

  before_filter :do_authenticate_user!
  around_filter :select_shard

  def do_authenticate_user!
    if session[:shard]
      if params[:database] && session[:user_shards]
        new_shard = params[:database].to_sym
        if session[:user_shards].include?(new_shard) or add_another_shard?(new_shard)
          if session[:shard] != new_shard
            session[:shard] = new_shard
            session[:runas] = current_user.login
            init_shard
          end
        end
      end
      Octopus.using(session[:shard]) do
        authenticate_user!
      end
    else
      logger.debug "no session"
      authenticate_user!
      init_session(current_user) if current_user
    end
  end
  
  def select_shard(&block)
    logger.debug "select_shard"
    Octopus.using(session[:shard] || SHARDS.first) do
      check_session
      Time.zone = current_user.time_zone if current_user
      @working_week = current_user.working_week if current_user
      block.call
    end
  end
...  
end
`

**Comment by jnunemaker** [comment]
@krzcho I'm confused. I don't see where flipper is being called in those filters. Is it tucked away in one of the method calls invoked there?

**Comment by krzcho** [comment]
Flipper's groups are based on actor's shard
Shard is being changed in before_filter
Problem may not be in flipper but in the way current_user's shard is being obtained by devise - I will investigate further on my side

**Comment by jnunemaker** [comment]
@krzcho I was going to mention that. As I'm not able to reproduce this I'm pretty sure it is something with how you are selecting shards and swapping AR's connections.

**Comment by jnunemaker** [comment]
Let me know what you find out and post it here for others please. :)

**Comment by krzcho** [comment]
It was my mistake, sorry: a call to current_user must be made within proper shard context

```ruby
  def do_authenticate_user!
    reset_runas = false
    if session[:shard]
      if params[:database] && session[:user_shards]
        new_shard = params[:database].to_sym
        if session[:user_shards].include?(new_shard) or add_another_shard?(new_shard)
          if session[:shard] != new_shard
            session[:shard] = new_shard
            reset_runas = true
            init_shard
          end
        end
      end
      Octopus.using(session[:shard]) do
        authenticate_user!
        session[:runas] = current_user.login if reset_runas
      end
    else
      logger.debug "no session"
      authenticate_user!
      init_session(current_user) if current_user
    end
  end
```

**Comment by jnunemaker** [comment]
Thanks for the update!
