### ISSUE TITLE
Feature Request: Capacity to query if a feature was enabled from js

### ISSUE THREAD

**Issue by gbalbuena** [jnunemaker/flipper#150]
I found myself working on some features related to js client side code that requires to know if a feature was enabled or not, I know it's easy to get a quick and dirty approach with erb.

Code draft
```
var Flipper = (function(){
  var features = <%= @flipper.features.map {|f| {f.name => (f.state.eql? :on)} }.reduce(:merge).to_json.html_safe %>
  return {
    features: features
  };
}());
```

But what if there's other way to do it using a `js` client to query the flipper API that is already a WIP according to what i saw.

**Comment by gbalbuena** [comment]
Related to: #130

**Comment by jnunemaker** [comment]
It would have to be a locked down API, not the API that is in the works, as that one is full access to everything, which is not what you want from a security perspective (ie: someone querying from js what are all the features and which actors are enabled for them). 

Also, I wouldn't do what you are doing as that would require N+1 network calls where N is the number of features as it currently takes 1 network call to get the enabled state per feature. I wouldn't check state either. Instead use Feature#enabled? as that can take an actor (like current_user) to allow for partial rollouts.

I'd recommend just adding an endpoint where you can request the enabled state of one or more features:

```
# request something like
GET /features?name[]=first&name[]=second

# response something like:
features = params[:name].map { |name| feature[name] }
features = features.inject({}) { |hash, feature| hash[feature.key] = feature.enabled?(current_user); hash }.to_json

# json would look like this
{
  "first": false,
  "second": true,
}
```

Or just doing the same in JS.

```ruby
var EnabledFeatures = <%= features.inject({}) { |hash, feature| hash[feature.key] = feature.enabled?(current_user); hash }.to_json %>
```

Thoughts?

**Comment by gbalbuena** [comment]
Good point, this is closer to what I'm looking for.

Lets close this, since there is a good approach using a partial.
