### ISSUE TITLE
Auditing

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#164]
Mostly a placeholder for now, but hooking up some form of auditing for flipper would be awesome. A common need is users wanting to know when a feature was enabled/disabled/added/removed, etc. The audit logs should be viewable in the UI and API someday as well.
- action - enable/disable/feature created/feature deleted
- who performed the action
- when was the action performed

**Comment by fbjork** [comment]
@jnunemaker Any progress on this? For now, what's the quickest way to log who performed an action to STDOUT?

**Comment by Subomi** [comment]
Why STDOUT @fbjork wouldn't an audit trail in the adapter be the preferable route to go about this?

**Comment by jnunemaker** [comment]
@fbjork nothing related to open source. Auditing is pretty closely tied to your application so I'm not sure if flipper is going to solve this or not. We'd need some way to identify a user who performed the action in your app. I will say that we have this in https://www.flippercloud.io and we also did it at github so it is definitely possible, but not sure flipper oss is going to solve it. I'd be open to someone taking a whack at it if anyone is interested. Going to close this for now.

**Comment by jnunemaker** [comment]
For those who end up on this, I wrote up a decent amount of thoughts in a response to a different issue: https://github.com/jnunemaker/flipper/pull/102#issuecomment-612707892.
