### ISSUE TITLE
Api V1 percentage_of_actors gate

### ISSUE THREAD

**Issue by AlexWheeler** [jnunemaker/flipper#168]
endpoint to enable/disable percentage_of_actors for a feature following the convention:
`POST api/v1/features/:feature_name/:gate_name # enable`
`DELETE api/v1/features/:feature_name/:gate_name # disable`

api/v1/features/logging/percentage_of_actors
`flipper[:feature].enable_percentage_of_actors 10`

**Comment by jnunemaker** [comment]
Closed by https://github.com/jnunemaker/flipper/pull/179 I believe.
