### ISSUE TITLE
Ruby API Client

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#174]
Now that we have an API, it would be nice to have an API client as well. I'd like to just build it on net/http to avoid any extra dependencies. 

``` ruby
client = Flipper::Api::Client.new("path to api mount point...?")
client.features
client.feature(:search) or client.feature("search")
client.feature(:search).enable(...)
client.feature(:search).disable(...)
client.feature(:search).enabled?(...)
# etc, similar to Flipper::Feature, might make sense to just create this as a flipper adapter so people could just use the API through flipper like normal, hmmm

http_adapter = Flipper::Adapters::Http.new("path to api mount point...?")
client = Flipper.new(http_adapter)
```

**Comment by AlexWheeler** [comment]
The idea of an http adapter sounds pretty cool, I'll start working on this and get a PR up for some feedback when I have a good idea of how it will look

**Comment by AlexWheeler** [comment]
just an update - have a work in progress branch https://github.com/jnunemaker/flipper/tree/http-adapter

**Comment by jnunemaker** [comment]
First version is in. Going to close this, but we can always iterate.
