### ISSUE TITLE
Groups are in-memory?

### ISSUE THREAD

**Issue by apanzerj** [jnunemaker/flipper#187]
Are groups defined in the code and then loaded at runtime? I'm using the AR adapter and I don't see anywhere where the group is stored to the DB. 

If that's the case, it means that you can flip flippers and change things but you can't mess with groups w/o deploy.

Is that true or am I missing something?

**Comment by jnunemaker** [comment]
Yep, that is true. I don't feel safe storing ruby code in the database and eval'ing it at runtime, so groups are just in memory. You aren't missing anything. Closing the issue, but let me know if you have any ideas or more questions.
