### ISSUE TITLE
Examples/Version Confusion

### ISSUE THREAD

**Issue by eggie5** [jnunemaker/flipper#196]
The software works great. Just the only hangup I had was that the example in https://github.com/jnunemaker/flipper/blob/master/examples/group_dynamic_lookup.rb seems reference the current master at 11/16/16 and not the current 0.9.2 release. Specifically the second parameter of the block that `register` accepts isn't supported in 0.9.2.

**Comment by jnunemaker** [comment]
It has been a while since I released so I just updated the changelog and released 0.10.0.

**Comment by jnunemaker** [comment]
If you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly (it shows up on my [profile page](https://github.com/jnunemaker)). I'm just always curious. :)

**Comment by eggie5** [comment]
Hi, thanks for getting that release out. We were looking for a way to get more releases out and faster. If we had a way to deploy features w/o turning them on (or gradually turn them on) we would be able to get remove the log jam of testing and QA in staging. This project seemed stable and had some recent activity so it looked like a good fit. Got it setup in about a day (only b/c of above mentioned demo/version mixup) and so far it's been a nice addition to our stack. Thanks.
