### ISSUE TITLE
Whitespace in actors_value but not in actor's flipper_id

### ISSUE THREAD

**Issue by KevinBongart** [jnunemaker/flipper#204]
Hi @jnunemaker, thanks for this really useful gem (also hi @AlexWheeler! 👋)

I noticed that by copy-pasting emails as actors_value in the Flipper UI like `test@test.com \n`, then it won't let a User with `test@test.com` as `flipper_id` in.

The UI also makes it difficult to notice that kind of extra whitespace, so it took a little effort debugging on my side to find the root cause.

Should values stored in Redis always be stripped from leading-trailing whitespace? Should the user's custom `Thing#flipper_id` be in charge of this logic? Should the UI run `String#strip` before giving the value to Flipper?

I'd love to help out with this problem but I'm not sure where the responsibility lies between the user, the gem and its various components.

Let me know how I can help!

**Comment by jnunemaker** [comment]
Great question! I would have the UI/API do the strip. Putting it in flipper
could cause unexpected things for users of flipper in the future.

**Comment by KevinBongart** [comment]
Thanks, I also agree it shouldn't be in Flipper. The UI seems the right place, as the API should just save what it's given. I'll take a look today
