### ISSUE TITLE
Cleanup work for Adapter#get_multi

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#206]
get_multi was [recently added](https://github.com/jnunemaker/flipper/pull/198), but only made efficient for the redis adapter. I need to finish making the other adapters do bulk loads for get multi instead of n+1's.  

* [x] add get_multi to active record
* [x] add get_multi to dalli
* [x] add get_multi to mongo
* [x] add get_multi to sequel 
* [x] return value for get_multi? currently array, should it be hash 
* [x] ensure get_multi is doc'd (Adapters.md)
* [x] ensure preload and preload_all are doc's (Optimizations.md)

**Comment by gshutler** [comment]
`get_multi` returning a `Hash` is probably preferable. I know it would reduce [the complexity in `Memoizable`](https://github.com/jnunemaker/flipper/blob/2c580a16b1b0bf66e845ab92a86a0c9843780dda/lib/flipper/adapters/memoizable.rb#L82) for example, and if you only want the `Array` you can always call `values` on the `Hash` so I don't think there's any loss.

Let me know if I can help in any way.

**Comment by jnunemaker** [comment]
@gshutler cool. Changed to hash. I think I have everything ready but the docs. If you want to take a crack at those, feel free (just let me know so we don't both work on them), but I'll try to get to them soon and push out a new release afterwards.

**Comment by jnunemaker** [comment]
@gshutler it would be helpful if you wanted to double check some of my recent changes for get_multi in the various adapters for sanity, but don't feel like you have to. I should have done a PR...

**Comment by gshutler** [comment]
I had a look through them all (using https://github.com/jnunemaker/flipper/compare/fc6b58d1cb53384aa2a06f3b3313b4161118e86b...master) and didn't notice anything unexpected. All following a similar pattern to the Redis one which only changed slightly to return a `Hash`.

I'm not going to have time to look at docs for a few days so unlikely to get to it before you do.

**Comment by jnunemaker** [comment]
@gshutler thanks! No problem about the docs. I'll try to get to it tonight or tomorrow night.

**Comment by mscoutermarsh** [comment]
Hey @jnunemaker. Running this in production now.

![image](https://cloud.githubusercontent.com/assets/155044/20994224/002ee368-bca4-11e6-8a2f-85ffbaaf59b4.png)

Nice. THANK YOU for your work on this.

This is an endpoint doing 10-15 flag checks with postgres. Now uses `preload` with redis.

**Comment by jnunemaker** [comment]
Finished up docs this morning quick. Going to do a release. 

@mscoutermarsh awesome! Really appreciate you sharing that.
