### ISSUE TITLE
Should I deprecate flipper-activerecord?

### ISSUE THREAD

**Issue by bgentry** [jnunemaker/flipper#207]
Hey @jnunemaker,

It's been awhile since I checked in on this project. Seems you've added first-party adapters for both ActiveRecord and Sequel during that time, which is great.

I wrote the original [flipper-activerecord](https://github.com/bgentry/flipper-activerecord), but it seems there's no longer a reason to keep it alive or try to maintain it since this project now has an AR adapter. Shall I just deprecate it and point people here?

Prompted by https://github.com/bgentry/flipper-activerecord/issues/6, which is an issue I will also direct this way if that's ok.

**Comment by jnunemaker** [comment]
> I wrote the original flipper-activerecord, but it seems there's no longer a reason to keep it alive or try to maintain it since this project now has an AR adapter. Shall I just deprecate it and point people here?

Totally up to you, but deprecating it and pointing people here would reduce work for you probably. 

> Prompted by bgentry/flipper-activerecord#6, which is an issue I will also direct this way if that's ok.

Already responded. :)
