### ISSUE TITLE
How to scope a rails model against an actor gate

### ISSUE THREAD

**Issue by njt1982** [jnunemaker/flipper#215]
So I have a feature. I have setup an actor gate against the User model. It looks like this, when my user has the feature:

![image](https://cloud.githubusercontent.com/assets/384976/22178558/59b64af6-e031-11e6-8dc1-6bc50dcf89c2.png)

Any thoughts on the best approach for scoping this? How do I find all Users which have the "thing" feature?

**Comment by njt1982** [comment]
Is it as simple as this?

```
irb(main):011:0> pp MyApp.flipper[:thing].actors_value
  Flipper::Adapters::ActiveRecord::Gate Load (0.3ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "thing"]]
#<Set: {"1274"}>
=> #<Set: {"1274"}>
```

**Comment by jnunemaker** [comment]
Something like this in a method should get you all actors as instances in your app, assuming you have a flipper_id like `class:id` (e.g. `User:235`). I wouldn't recommend trying to setup a has many relationship or anything as flipper really isn't designed to work that way.

```
MyApp.flipper[:thing].actors_value.map { |flipper_id| 
  class_name, separator, id = flipper_id.rpartition(":")
  class_name.constantize.find_by_id(id)
}
```
