### ISSUE TITLE
Flipper default adapter/dsl instance

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#243]
Up until now Flipper has made no decision on where to store the flipper adapter and Flipper::DSL instance. The main reason is that I don't like globals and storing things like this is basically a global. That said, it forces flipper users to make the decision of where to keep track of this stuff (MyApp.flipper, $flipper, Rails.configuration.flipper, etc.), which means there is no standardization. 

I have been thinking that perhaps providing a default adapter and Flipper::DSL instance that is kept track of in Flipper itself might be useful. Most people probably just have one adapter and flipper instance per app, so keeping track of that for them would probably be useful. 

## What would it look like? 

First, set the default adapter. Not sure if I want to do full on config (like below) or just add an accessor for default_adapter to Flipper.

```ruby
Flipper.configure do |config|
  config.default_adapter = Flipper::Adapters::ActiveRecord.new
end
```

Once we (Flipper) know that, we can lazily instantiate a Flipper instance for you at the top level. I don't think we need to expose this, but it could be stored like:

```ruby
module Flipper
  def default
    @default ||= Flipper.new(default_adapter)
  end
end

Flipper.default # sets up new Flipper instance using default_adapter
Flipper.default # uses memoized instance setup in previous call
```

From there, we could expose the DSL methods on Flipper at the top level like this:

```ruby
require "forwardable"

module Flipper
  extend Forwardable

  def_delegators :default, :enabled?, :enable, :disable, :[] # etc. etc.
end
```

Which would allow for usage in a flipper user's application like:

```ruby
Flipper.enabled?(:stats, current_user)
Flipper[:stats].enabled?(current_user)
Flipper.enable(:stats, current_user)
# etc etc etc
```

Anyone have any thoughts for or against something like this? Just curious.

**Comment by AlexWheeler** [comment]
@jnunemaker interesting idea and it would be nice to have a standard way to do this.  In our Rails app we take the approach of initializing a global flipper instance `$flipper` in an initializer.  

One thing that might be worth mentioning is that we'll use an in memory adapter (or Redis)  in our test suite for small performance improvement and active_record in prod.  So being able to easily configure this for different environments would be something to keep in mind - which should still be simple with this approach in environment files or even just switching on the Rails env.

**Comment by Casao** [comment]
This would be super useful, and I'd love to see it.
