### ISSUE TITLE
Can't get started with Flipper:Api on a standalone server

### ISSUE THREAD

**Issue by helaili** [jnunemaker/flipper#246]
👋 @jnunemaker and @AlexWheeler 

I'm trying to put together [a simple standalone Flipper server](https://github.com/helaili/soloflipper) with UI and Api for demo purposes (maybe more later). Just trying to leverage Flipper from a Node app for now. 

Basically, I've created a Rails app with `rails new soloflipper`, changed my `Gemfile` and  `config/routes.rb` (see [code](https://github.com/helaili/soloflipper/blob/master/config/routes.rb)). 

UI works fine, but I get a 404 with `curl -i http://localhost:3000/flipper/api/features` 
```
HTTP/1.1 404 Not Found
Content-Type: application/json
Cache-Control: no-cache
X-Request-Id: c63a2de9-a793-4ae0-99de-8e7c284127bd
X-Runtime: 0.000705
Transfer-Encoding: chunked
```

`bin/rails routes` generates the following output, which seems weird for the Rails noob I am : 

```
Prefix Verb URI Pattern  Controller#Action
 /flipper/api #<Rack::Builder:0x007f85ca4c9580 @warmup=nil, @run=#<Flipper::Api::App:0x007f85ca4e33b8 @status=200, @headers={"Content-Type"=>"application/json"}, @body=[""]>, @map=nil, @use=[#<Proc:0x007f85ca4c9058@/Users/alain/.rvm/gems/ruby-2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:86>]>
 /flipper     Flipper::UI
```

Any guidance would be much appreciated ❤️ :octocat:

**Comment by jnunemaker** [comment]
I'm away from computer but locking to flipper master (or better latest ref
in master) in your Gemfile should get you going. That is what I'm doing
currently. I'll be doing another release soon.

**Comment by AlexWheeler** [comment]
Hey @helaili, sorry to hear that! We've been doing some work on the api to make it even more user friendly for the next release, and have updated the api documentation to reflect these new changes that haven't been released yet 😵.  You can get your api working by instructing your Gemfile to download the master branch as opposed to the most recent RubyGems release (the default) by replacing lines 38-40 in your Gemfile with:
```
 gem 'flipper',github: 'jnunemaker/flipper'
 gem 'flipper-ui', github: 'jnunemaker/flipper'
 gem 'flipper-api', github: 'jnunemaker/flipper'
```

Your Gemfile as it currently is will download the latest version on RubyGems which is 0.10.2.  In that version we prefixed every api route with `api/v1/`, so `mount Flipper::Api.app(flipper) => '/flipper/api'`, would serve the features route, for example, at `flipper/api/api/v1/features`.  As @jnunemaker suggested if you want the routes to be served as the documentation says (which we believe is much simpler) you can tell your Gemfile to download the master branch of flipper-api, where everything will be served right from the uri you mounted the app at:

`mount Flipper::Api.app(flipper) => '/flipper/api'` will serve the features at `flipper/api/features`

**Comment by helaili** [comment]
Awesome! Works perfectly, thanks a lot :heart_eyes_cat:
