### ISSUE TITLE
feature.enabled? through API

### ISSUE THREAD

**Issue by helaili** [jnunemaker/flipper#247]
Double checking here as I could not find a way to verify if a feature is enabled for a user through the API. Is this something you are planning on implementing?

**Comment by AlexWheeler** [comment]
@helaili There isn't an endpoint you can, for example, pass a flipper_id and get a response telling you if that thing is enabled.  If you're curious you could check out how Flipper determines this https://github.com/jnunemaker/flipper/blob/master/lib/flipper/feature.rb#L82.

I don't see the api supporting this in the future and think a project using Flipper could add this as their own custom endpoint.  Curious, how are you consuming the api?  If the app talking to the api is using Flipper you could use the [http adapter](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/adapters/http.rb) and use `flipper.enabled?(user)`  ?

**Comment by jnunemaker** [comment]
@helaili I agree with @AlexWheeler. The easiest way currently would be to use the http adapter. The key is just to ensure the uri is set like in the [tests](https://github.com/jnunemaker/flipper/blob/b57f9ec0600fe6a66c87e01429a6ef010d87754c/spec/flipper/adapters/http_spec.rb#L12). 

I'm closing this to keep issues tidy, but @AlexWheeler and I are happy to answer more questions here if you have any.

**Comment by helaili** [comment]
Thanks guys, I've been able to come close to a good solution with your help.

@AlexWheeler, as said in jnunemaker/flipper#246 I'm trying to leverage Flipper from a Node.js app. Therefore I have embedded Flipper in [a simpler Rails app](https://github.com/helaili/soloflipper) and I'm now exposing a REST endpoint to wrap the feature.enabled? code.

**Comment by jnunemaker** [comment]
@helaili oh neat. I forgot that, sorry. If I were you I would add a single route that passes a flipper_id and returns true/false. I wonder if enough people would find that useful for us to provide a simple rack middleware which does so... 

I think the key if you are going to expose this data across platforms is that you either have some sort of authentication/authorization or only expose a read-only endpoint. 

Something ala this could work for a read-only endpoint (never executed, just whipped together):


```ruby
class FlipperEnabledMiddleware
  class FlipperActor
    attr_reader :flipper_id

    def initialize(flipper_id)
      @flipper_id = flipper_id
    end
  end

  def initialize(app, flipper)
    @app = app
    @flipper = flipper 
  end

  def call(env)
    request = Rack::Request.new(env)

    if request.path == "/flipper-enabled"
      headers = {"Content-Type" => "application/json"}
      flipper_id = request.params["flipper_id"]
      enabled = if flipper_id.nil? || flipper_id.empty?
        false
      else
        @flipper.enabled?(FlipperActor.new(flipper_id))
      end

      body = JSON.generate({enabled: enabled})
      [200, headers, [body]]
    else 
      @app.call(env)
    end
  end 
end

use FlipperEnabledMiddleware, SomeApp.flipper
```

The downside of this is that, without injecting some sort of authentication/authorization in the endpoint, someone could hammer your endpoint with flipper id's to figure out what features exist and who they are enabled for.

Also, FWIW, I plan on re-making flipper for other languages and node is on my list, but I have no idea when I'll actually get time. My big dream is flipper for each language with http adapters that talk to a central API like we currently have and you are attempting to use.
