### ISSUE TITLE
GroupNotRegistered never raised

### ISSUE THREAD

**Issue by jonmagic** [jnunemaker/flipper#262]
Have been reading through the library and don't see `GroupNotRegistered` raised anywhere.

According to [this comment](https://github.com/jnunemaker/flipper/blob/c2b7a7e126accb92db0bce7bc8206536701bc69d/lib/flipper/dsl.rb#L220) I think it's supposed to be raised in `Flipper.group` if the group is not present. [Here](https://github.com/jnunemaker/flipper/blob/75ec873585706d403393bd50a139cc960a03b0fd/lib/flipper.rb#L69) maybe? From the looks of it though the real expected behavior is that a `Types::Group` object with a name and no block to execute should be returned.

**Comment by jnunemaker** [comment]
I believe https://github.com/jnunemaker/flipper/pull/244 is what changed to allow unregistered groups and avoid raising. I think that DSL doc and the accompanying exception need to be removed.
