### ISSUE TITLE
ActiveSupport::Cache::Store support

### ISSUE THREAD

**Issue by rzane** [jnunemaker/flipper#263]
ActiveSupport::Cache::Store is an abstraction on top of a bunch of different caching backends: file, memory, null, redis, dalli, etc.

This would be nice for rails users:

```ruby
Flipper::Adapters::Cache.new(some_other_adapter, Rails.cache, 4800)
```

Another similar project is [monetta](https://github.com/minad/moneta). By leveraging one of these existing cache abstractions, this project could support more backends with (I assume) less maintenance effort.

**Comment by rzane** [comment]
Looks like there's a gem for that! https://github.com/hundredwatt/flipper-cache_store.

**Comment by jnunemaker** [comment]
@rzane looks like that gem is pretty out of date. The adapter interface has changed and it will need an update.

Overall, I like the idea of an ActiveSupport cache adapter and a monetta adapter. I'm very familiar with monetta as it inspired https://github.com/jnunemaker/adapter a long time ago. 😄

**Comment by jnunemaker** [comment]
https://github.com/jnunemaker/flipper/pull/265 fixed this.
