### ISSUE TITLE
Create gemspec for cache-store

### ISSUE THREAD

**Issue by AlexWheeler** [jnunemaker/flipper#267]
Each of the other adapters have been pulled into their own gem with their own .gemspecs + deps.  We'll want to create a .gemspec for cache store with an activesupport dependency right?

**Comment by jnunemaker** [comment]
Probably a good idea since it has dependencies on active support.

**Comment by jnunemaker** [comment]
I can wait to release 0.11 until this so we don't have a backwards compat break.

**Comment by AlexWheeler** [comment]
sweet will get this + docs up tonight
