### ISSUE TITLE
Auto add missing features 

### ISSUE THREAD

**Issue by antulik** [jnunemaker/flipper#271]
Would nice to autopopulate features list if the feature was requested but does not exist yet. 

As a result new added features will automatically appear in the admin view

**Comment by jnunemaker** [comment]
Ooooh, this would be convenient! Thanks for bringing it up. We do this for [enable](https://github.com/jnunemaker/flipper/blob/f2454a95fedeed90d43c55c0121e717fa7a6314d/lib/flipper/feature.rb#L45)/[disable](https://github.com/jnunemaker/flipper/blob/f2454a95fedeed90d43c55c0121e717fa7a6314d/lib/flipper/feature.rb#L61), but not for get/get_multi and friends. I had to think for a sec to remember why I didn't do it for reads. I believe the main reason thus far is that feature reads are an extremely hot path in some applications and doing this would require additional network calls that could make flipper prohibitively expensive to use. 

In order to know if a feature is in the list, you either have to add the feature on each read or check if it is in the list of features on each read, both of which require network calls. One could work around that by memoizing in memory per process for a period of time. 

The good news is, you can do this right now if you really need it, without flipper itself doing it. I believe you just need to make an adapter that wraps another adapter. Then, on read, do the checks you need to add the feature. Something like:

```ruby
class AutoAddAdapter
  include Flipper::Adapter

  attr_reader :name

  def initialize(adapter)
    @adapter = adapter
    @name = :auto_add
  end

  def get(feature)
    add(feature) unless features.include?(feature.key)
    @adapter.get(feature)
  end

  # delegate all the other methods like get or use SimpleDelegator
end

adapter = AutoAddAdapter.new(Flipper::Adapters::ActiveRecord.new)
flipper = Flipper.new(adapter)
```

I like to think of adapters similar to middleware in that they can be stacked do anything you need really. Does that help? 

Going to close the issue since I don't think I'll add this to the read path, but if it seems valuable enough, we could an example on how to do this in the examples directory. I'd totally ❤️ a pull request for an example if you do this in your app. 

Also, if you don't mind, I would love to know what you are using flipper for as well and how it is working out for you other than features not auto-populating (what went well, what was hard). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly (it shows up on my profile page). I'm always curious. :)

**Comment by dyeje** [comment]
@jnunemaker this would be really helpful for my team. It's a bit of a pain to keep flags up to date between multiple environments. I'd be happy to make a PR with an example once I get it working. So far I've got the following in an initializer:

```ruby
require 'flipper/adapters/active_record'

class AutoAddAdapter < SimpleDelegator
  include Flipper::Adapter

  attr_reader :name

  def initialize(adapter)
    @adapter = adapter
    @name = :auto_add
  end

  def get(feature)
    add(feature) unless features.include?(feature.key)
    @adapter.get(feature)
  end
end

Flipper.configure do |config|
  config.adapter { AutoAddAdapter.new(Flipper::Adapters::ActiveRecord.new) }
end
```

I get the following error:
```
undefined local variable or method `features' for #<AutoAddAdapter:0x00007fa05eba42c0 @adapter=#<Flipper::Adapters::ActiveRecord:0x00007fa05eba4310 @name=:active_record, @feature_class=Flipper::Adapters::ActiveRecord::Feature(id: integer, key: string, created_at: datetime, updated_at: datetime), @gate_class=Flipper::Adapters::ActiveRecord::Gate(id: integer, feature_key: string, key: string, value: string, created_at: datetime, updated_at: datetime)>, @name=:auto_add>

Extracted source (around line #29):

    # make this more efficient.
    def get_all
      instances = features.map { |key| Flipper::Feature.new(key, self) }
      get_multi(instances)
    end

/Users/jeremydye/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/delegate.rb:91:in `method_missing'
flipper (0.25.2) lib/flipper/adapter.rb:29:in `get_all'
flipper (0.25.2) lib/flipper/adapters/memoizable.rb:104:in `get_all'
flipper (0.25.2) lib/flipper/dsl.rb:202:in `preload_all'
/Users/jeremydye/.rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/forwardable.rb:238:in `preload_all'
flipper (0.25.2) lib/flipper/middleware/memoizer.rb:68:in `memoized_call'
flipper (0.25.2) lib/flipper/middleware/memoizer.rb:37:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/cookies.rb:697:in `call'
activerecord (7.0.3) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
sentry-rails (5.4.2) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
sentry-ruby (5.4.2) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'
sentry-ruby (5.4.2) lib/sentry/hub.rb:199:in `with_session_tracking'
sentry-ruby (5.4.2) lib/sentry-ruby.rb:372:in `with_session_tracking'
sentry-ruby (5.4.2) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'
sentry-ruby (5.4.2) lib/sentry/hub.rb:59:in `with_scope'
sentry-ruby (5.4.2) lib/sentry-ruby.rb:352:in `with_scope'
sentry-ruby (5.4.2) lib/sentry/rack/capture_exceptions.rb:18:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.3) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.3) lib/rails/engine.rb:530:in `call'
puma (5.6.4) lib/puma/configuration.rb:252:in `call'
puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
puma (5.6.4) lib/puma/server.rb:441:in `process_client'
puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by jnunemaker** [comment]
@dyeje you need super or __setobj__ in the initialize method so that SimpleDelegator knows what object to forward to. I think that is the issue.

**Comment by dyeje** [comment]
@jnunemaker worked like a charm. I poked around the repo and didn't see an obvious place to put it, so here's the working code for future readers:

`config/initializers/flipper.rb`
```ruby
require 'flipper/adapters/active_record'

class AutoAddAdapter < SimpleDelegator
  include Flipper::Adapter

  attr_reader :name

  def initialize(adapter)
    @adapter = adapter
    @name = :auto_add
    super
  end

  def get(feature)
    add(feature) unless features.include?(feature.key)
    @adapter.get(feature)
  end
end

Flipper.configure do |config|
  config.adapter { AutoAddAdapter.new(Flipper::Adapters::ActiveRecord.new) }
end
```

**Comment by travisbell** [comment]
Hey guys,

I tried giving this a go with the Mongo adapter but all of my attempts broke `Flipper::Middleware::Memoizer`. I couldn't quite figure out why.

However, having said that, I think the original post would be a pretty useful feature. We noticed even though we are memoizing our features, random extra calls were being made out to the database. Lo and behold, it's features that hadn't been created in the environment yet, so they weren't preloaded with the memoizer.

This kind of highlights two separate issues, one being that if a key isn't memoized, Flipper still checks the DB for it, and second that it can be hard in a large codebase to track all of the features in use vs. what has been created in a certain environment. I can understand why the first issue is the way it is, but the second one could be solved.

**Comment by jnunemaker** [comment]
@travisbell great input. Appreciate you taking the time. I think you make a good case for having this adapter exist in core. 

I think the reason I've never added it is I use [flippercloud.io](https://www.flippercloud.io). Cloud syncs all the features to all environments including your dev machines so you don't feel this pain.

**Comment by jnunemaker** [comment]
Created an issue for people to follow. I'll try to tackle this soonish. Open to Prs. https://github.com/flippercloud/flipper/issues/925
