### ISSUE TITLE
I don't know how to use this gem.

### ISSUE THREAD

**Issue by mahhek** [jnunemaker/flipper#275]
Hi there, 

Can anybody tell me how to use this gem? for example I want to use ActiveRecord Adapter and want to enable disable search feature from my admin panel of my application, can anyone please tell me the steps? I understood this gem but not understanding how I can use it from my admin panel to enable/disable any feature. thanks a lot.

**Comment by jnunemaker** [comment]
Did you look over the [active record docs](https://github.com/jnunemaker/flipper/tree/master/docs/active_record)? They detail how to install and use it. 

The key is to add it to your gemfile:

```
gem 'flipper-active_record'
```

Then generate the migration:

```
$ rails g flipper:active_record
```

Then run the migration:

```
$ rails db:migrate
```

Then you need to setup an instance of flipper to use. If your application module is `MyApp`, you could drop this in a file named `config/initializers/flipper.rb`:

```ruby
require 'flipper/adapters/active_record'

module MyApp
  def self.flipper
    Thread.current[:flipper] ||= Flipper.new(Flipper::Adapters::ActiveRecord.new)
  end
end
```

Then in your admin controller, views or models, you can check if a feature is enabled with a normal ruby `if` conditional:

```ruby
# say in a view
<% if MyApp.flipper.enabled?(:search) %>
  ... show the search stuff ...
<% else %>
  ... show nothing or something that indicates search is off ...
<% end %>
```

If you have a user model, you can add a method like this:

```ruby
class User
  def flipper_id
    "#{self.class.name};#{id}"
  end
end
```

And if you know the currently signed in user say `current_user` you can check if the feature is specifically enabled for that user like this:

```ruby
# say in a view
<% if MyApp.flipper.enabled?(:search, current_user) %>
  ... show the search stuff ...
<% else %>
  ... show nothing or something that indicates search is off ...
<% end %>
```

Does that help? 

Closing the issue to keep things tidy, but feel free to ask more questions and I can help as I have time.

**Comment by mahhek** [comment]
Great, it worked like a charm, thanks a lot.
