### ISSUE TITLE
New Bootstrap for Flipper::UI

### ISSUE THREAD

**Issue by Erol** [jnunemaker/flipper#276]
Hi @jnunemaker, would you be interested in using the new/flat-style version of Bootstrap? If no one's doing it yet, I think I can spike a PR to have Flipper::UI use the new version.

**Comment by jnunemaker** [comment]
@Erol sounds good to me! No one has communicated to me that they are working on it or intend to other than you.

**Comment by wcurtis** [comment]
@Erol this would be fantastic - did you end up starting this?
