### ISSUE TITLE
Multitenancy and Flipper

### ISSUE THREAD

**Issue by arcticbarra** [jnunemaker/flipper#280]
Hi there!

I have a multi tenant app using the apartment gem with various schemas and would like to put all flipper features in one schema instead of having to put all the features in all schemas manually. In the apartment config I can exclude models and therefore all queries to those models are made to the public schema. I tried to create a custom model for Flipper Features and Flipper Gates and pointing them to their respective tables but had no luck.

Is there any way to do this?

Thanks!

**Comment by AlexWheeler** [comment]
@arcticbarra I'm assuming you're using the ActiveRecord Flipper adapter because it looks like apartment is for Rails/ActiveRecord apps, right?

Internally the adapter defines and uses `Flipper::Adapters::ActiveRecord::Feature`, `Flipper::Adapters::ActiveRecord::Gate` models.  Can you try:

```
config.excluded_models = ["Flipper::Adapters::ActiveRecord::Feature", "Flipper::Adapters::ActiveRecord::Gate"]   
```

**Comment by arcticbarra** [comment]
It worked! Thank you very much @AlexWheeler 🎉
