### ISSUE TITLE
Supporting query param or cookie gates

### ISSUE THREAD

**Issue by oboxodo** [jnunemaker/flipper#283]
I was looking for some example to allow a user to enable/disable a feature specifically for a request using a query param, or maybe for a session using a cookie. But I couldn't find any.

That would allow a dev, qa, stakeholder, etc to try a feature, say `new_signup_form`, by adding a special `f_new_signup_form=true` query param to the URL. The advantage of this over using the actors gate is that it's faster to do if I only need it to be enabled for a single request, and that it also works independently of a user being logged in or not (being `current_user` a typical actor)

Looking at the already implemented gates I thought maybe there's a way to support that with a new gate... but I'd probably need to pass the request as the actor instead of the user... and even in that case it's not very clear what to do with `flipper_id`.

Probably a better approach would be to implement a rack middleware taking care of this feature. But then we'd end up with a gatekeeper which is not an actual `Gate` instance.

Do you know of anyone already doing something like this with Flipper?

**Comment by AlexWheeler** [comment]
@oboxodo I think the current actors gate is a great solution for this since the definition of an actor is very broad. As you mentioned its really just an object that responds to flipper_id.  You could make an Actor abstraction on top of the Rails params hash for example:

```
class RequestActor
  def initialize(params, key)
    @params = params
    @key = key
  end

  def flipper_id
    @params[@key]
  end
end
```
Let's say you want this feature to be enabled for any request with the query param `my_feature=true`

An example request comes in to `www.your_app.com?my_feature=true`

we know that the params hash will be `{ "my_feature" => "true" }`

First, we'd make sure the actor is enabled

```
actor = RequestActor.new( { "my_feature" => "true" }, "my_feature")
$flipper["my_feature"].enable(actor)
```
This will work because `actor.flipper_id` will return `true`, and this is what's stored in the database.

In your controller you could then check in your show action for example:
```
def show
  actor = RequestActor.new(params, "my_feature")
   $flipper["my_feature"].enabled?(actor)
end
```
If params contains { "my_feature" => true } then `enabled?` will be true, otherwise it will be false.  You could do something similar for cookies.  Does that help?

**Comment by oboxodo** [comment]
Thanks, @AlexWheeler. That makes sense. I'll revisit this when we get to finally make the move to flipper, hopefully before EOY.

**Comment by jnunemaker** [comment]
We have some stuff at work for this as well. We allow overriding what features are enabled/disabled using query params, but only if you have a certain level of permission (ie: staff, etc.). 

The query param syntax looks like this:

```
    #   ?_features=apples  # Enable the apples feature for this request
    #   ?_features=!apples # Disable apples for this request
    #   ?_features=apples,oranges  # Enable apples and oranges
    #   ?_features=apples,!oranges # Enable apples, disable oranges
    #   ?_features=a* # Enable all features with names starting with "a"
    #   ?_features=*  # Enable all features
    #   ?_features=!* # Disable all features
```

The implementation is a middleware and an adapter. The middleware parses the parameter and sets the override on the adapter for the duration of the request (resetting to no overrides following the request). The adapter wraps our memcached adapter which wraps our mysql adapter.

```ruby
memcached = ...
override = Flipper::Adapters::Override.new(memcached)
Flipper.new(override, ...)
```

The adapter provides a method named `override_features` (called by middleware after parsing param), which allows us to specify a feature is either fully enabled or fully disabled by name/pattern. It delegates all methods to the wrapped adapter other than `get` which first checks if a feature name is explicitly enabled or disabled falling back to the wrapped adapter.

We also have a FlipperSession actor. We generate id's for each session and use that as the flipper_id for % of session rollouts. All that to say a query param, session or cookie value will all work. All you need is an actor that responds to `flipper_id` as @AlexWheeler said and you can do whatever you want. 

I actually just added a [generic actor class](https://github.com/jnunemaker/flipper/blob/624217804a0225d1e219a2ba6354d7f9bc2fe41e/lib/flipper/actor.rb) too that you could use like: 

```ruby
actor = Flipper::Actor.new("session:#{id}")
flipper.enable_percentage_of_actors(:new_form, 5)
flipper.enabled?(:new_form, actor)
```

I can try to open source something like that at some point, but that should give you a good start.
