### ISSUE TITLE
.configure method is undefined

### ISSUE THREAD

**Issue by Orbyt** [jnunemaker/flipper#286]
I wanted to test out Flipper and was writing a small class to handle the Flipper configuration. I'm getting an error noting that the `Flipper.configure` method is undefined. Opening up the Rails console, `Flipper.respond_to? :configure` returns `false`. 

The examples on the project's ReadMe show the use of `.configure`, and I can see the method defined in the `flipper.rb` file. What's going on here?

**Comment by Orbyt** [comment]
It appears there's a mismatch in documentation for the default gem installed.

The default installation installs `0.10.2`, the latest stable release, however the rest of the ReadMe is incompatible with that version. This is quite confusing, and should be fixed.

**Comment by jnunemaker** [comment]
0.10.2 is the latest non-beta release. The docs you are looking at are for master, which is highly stable, but not released (outside of 0.11.beta7, which I am using in production on github.com, so its legit). I'd recommend looking at the [0.10.2 docs](https://github.com/jnunemaker/flipper/tree/v0.10.2/docs/active_record) ([main readme](https://github.com/jnunemaker/flipper/tree/v0.10.2)) or using 0.11.beta7 and the docs you were using. Sorry for the confusion!
