### ISSUE TITLE
Create memcached adapter

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#3]
I can definitely see use for a memcached adapter that is simply a cache adapter. It will work just like the memoized adapter but talk to memcache instead of memory.

We fronted rollout with memcache when working on words with friends and it really relieved the feature reads burden.

**Comment by jnunemaker** [comment]
Old and stale. Still want to do but has nothing to do with this repo. I'll make it live in a new repo like flipper-memcached or whatever.

**Comment by ericboehs** [comment]
This would be great. :+1:
