### ISSUE TITLE
NameError: uninitialized constant Flipper::Adapters::Redis

### ISSUE THREAD

**Issue by krtschmr** [jnunemaker/flipper#303]
Rails 3.2 seems to have issues with using the gem

*NameError: uninitialized constant Flipper::Adapters::Redis* 

```

Flipper.configure do |config|
  config.default do
    # pick an adapter, this uses memory, any will do
    adapter = Flipper::Adapters::Redis.new

    # pass adapter to handy DSL instance
    Flipper.new(adapter)
  end
end

```

previously we used flipper 0.7 and our code looked like this

```
require 'flipper/adapters/redis'
$flipper = Flipper.new(Flipper::Adapters::Redis.new(Redis.new))
```

this *should* work aswell but somehow the adapter class (and the required file) aren't found anymore. does it has to do with the gem structure?

**Comment by jnunemaker** [comment]
What gems are in your Gemfile? Is flipper-redis?

**Comment by jnunemaker** [comment]
Closing this to keep things tidy here, but happy to continue to help when you get a chance to respond.

**Comment by krtschmr** [comment]
didn't had time to fix  it so far, but it's on. my boss said sidekiq-branch is not important, so this might be in the future a thing again (happened when i wanted to switch from resque to sidekiq, so i had to use some redis gem and stuff)

have a nice day

**Comment by jnunemaker** [comment]
No problem! Let me know if you ever get back to it.
