### ISSUE TITLE
No non-beta gem pushed for flipper-ui 0.11

### ISSUE THREAD

**Issue by marten** [jnunemaker/flipper#305]
Is this intentional? This is the reason bundler won't update me to Flipper 0.11. I figured since everything is in the same repo, it would all be developed in unison with nothing lagging behind, so wanted to check if it wasn't an oversight.

**Comment by jnunemaker** [comment]
Not intentional at all! Thanks for pointing that out. I guess my release script failed and I didn't notice it. I went through each flipper gem and made sure 0.11 is out for them.
