### ISSUE TITLE
Enable for everyone but ... - blacklist

### ISSUE THREAD

**Issue by AntoineInsa** [jnunemaker/flipper#314]
Right now, it's possible to whitelist actors.

It would be useful to add a option to blacklist actors, ie allow everyone but specific actors.

**Comment by jnunemaker** [comment]
Disable seems really simple, but it gets tricky 😄. Could you provide any more details about a feature that you have that also needs disabling and why you want to disable those actors? That would help me understand.

To provide some more context, Flipper is about enabling, not disabling. The way I detect that a feature is enabled is if **any** gate is enabled. If I add a disabled (blacklist) of actors, then how should it work if % of actors is enabled for 100 or the boolean gate is true (actor gate would return false for disable, but the other gates would return true and let the actor in)? 

Disabling actors or groups adds a lot of complexity/decisions. I'd be happy to be wrong about that and/or see a PR exploring the addition of disable the whole way through, but I don't think I'm ready to take on that complexity and own it long term for the few times it gets requested. 

Any chance you are 😉? If not, the good news is that disabling is the opposite of enabling, so what people usually do is add a negation feature. If your feature if "foo", you can add "foo_disabled".

```ruby
if Flipper.enabled?(:foo, actor) && !Flipper.enabled?(:foo_disabled, actor)
  # only gets here if foo is enabled for actor and foo_disabled is not enabled
end
```

**Comment by jnunemaker** [comment]
@AntoineInsa oh, and also, if you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard other than the disable). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly (it shows up on my profile page). I'm just always curious. :)

**Comment by AntoineInsa** [comment]
@jnunemaker thanks for your reactivity and all your feedback! It helps understand how the tool was designed! We mostly use the feature flipper for soft launches, release it to know customer, before making it available to everyone. We just went into an issue where one of the customer hasn't upgraded his "theme" and thus couldn't access a related feature. Having a "disable_feature_x" would have helped, but I didn't want to go through all the places in the code where the conditional was set and add one more, thus the present request.
The "disable_feature_x" flag would work for know though, thanks for the advice!

**Comment by fabn** [comment]
> Any chance you are 😉? If not, the good news is that disabling is the opposite of enabling, so what people usually do is add a negation feature. If your feature if "foo", you can add "foo_disabled".
> 
> ```ruby
> if Flipper.enabled?(:foo, actor) && !Flipper.enabled?(:foo_disabled, actor)
>   # only gets here if foo is enabled for actor and foo_disabled is not enabled
> end
> ```

I had the same need and I've used the same approach. However it might be useful to have (maybe in a future release) something like this:

```ruby
class Flipper
  def blacklisted?(feature, actor)
    !Feature.enabled?("#{feature}_disabled", actor)
  end
end
```

Just for syntactic sugar
