### ISSUE TITLE
Rails 5 ActionView::Template::Error occurred in controller#action: “nested transaction”

### ISSUE THREAD

**Issue by krzcho** [jnunemaker/flipper#316]
I have recently migrated from 4 to latest 5.1 rails with flipper. I have a non-repeatable error and I am not able to trace it's source. Below is a an example application backtrace:

```
  app/views/reports/_transaction_dialog.html.erb:88:in `_app_views_report=
s__transaction_dialog_html_erb___259516699_72100400'
  app/views/reports/show.html.erb:40:in `block in _app_views_reports_show=
_html_erb___439575899_73388840'
  app/views/reports/show.html.erb:38:in `_app_views_reports_show_html_erb=
___439575899_73388840'
  app/controllers/application_controller.rb:52:in `block in select_shard'=

  app/controllers/application_controller.rb:48:in `select_shard'

```
I know it does not say much... it is just a partial rendering. It happens in various places of the code but usually in a place where app uses flipper to check for feature availability. Here _transaction_dialog.html.erb:88 has:

`      <% if $flipper[:schooling].enabled? current_user %>
`

I know it does not point directly to flipper but I am out of ideas that is why I post it here. Gemfile.lock below:

GIT
  remote: https://github.com/zquestz/omniauth-google-oauth2
  revision: 605f483311a1885d87fa636791faba109ff37221
  branch: master
  specs:
    omniauth-google-oauth2 (0.5.2)
      jwt (~> 1.5)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)

GEM
  remote: https://rubygems.org/
  remote: https://rails-assets.org/
  specs:
    actioncable (5.1.4)
      actionpack (= 5.1.4)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.4)
      actionview (= 5.1.4)
      activesupport (= 5.1.4)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.4)
      activesupport (= 5.1.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.1.4)
      activesupport (= 5.1.4)
      globalid (>= 0.3.6)
    activemodel (5.1.4)
      activesupport (= 5.1.4)
    activerecord (5.1.4)
      activemodel (= 5.1.4)
      activesupport (= 5.1.4)
      arel (~> 8.0)
    activerecord-sqlserver-adapter (5.1.2)
      activerecord (~> 5.1.0)
      tiny_tds
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    ar-octopus (0.9.1)
      activerecord (>= 4.0.0)
      activesupport (>= 4.0.0)
    arel (8.0.0)
    autoprefixer-rails (7.1.6)
      execjs
    axlsx (1.3.6)
      htmlentities (~> 4.3.1)
      nokogiri (>= 1.4.1)
      rubyzip (>= 0.9.5)
    bcrypt (3.1.11-x64-mingw32)
    bcrypt (3.1.11-x86-mingw32)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bootstrap_form (2.7.0)
    builder (3.2.3)
    byebug (9.1.0)
    cmxl (0.2.0)
      rchardet19
    cocoon (1.2.11)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    crass (1.0.3)
    declarative (0.0.10)
    declarative-option (0.1.0)
    devise (4.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    devise_ldap_authenticatable (0.8.5)
      devise (>= 3.4.1)
      net-ldap (>= 0.6.0, <= 0.11)
    docx (0.2.07)
      nokogiri (~> 1.5)
      rubyzip (~> 1.1.6)
    erubi (1.7.0)
    erubis (2.7.0)
    exception_notification (4.2.2)
      actionmailer (>= 4.0, < 6)
      activesupport (>= 4.0, < 6)
    execjs (2.7.0)
    faraday (0.12.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.18-x64-mingw32)
    ffi (1.9.18-x86-mingw32)
    flipper (0.11.0)
    flipper-ui (0.11.0)
      erubis (~> 2.7.0)
      flipper (~> 0.11.0)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, < 2.1.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    gmail (0.6.0)
      gmail_xoauth (>= 0.3.0)
      mail (>= 2.2.1)
    gmail_xoauth (0.4.2)
      oauth (>= 0.3.6)
    google-api-client (0.17.3)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
    googleauth (0.6.2)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    googlecharts (1.6.12)
    hashie (3.5.6)
    htmlentities (4.3.4)
    httpclient (2.8.3)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    jwt (1.5.6)
    little-plugger (1.1.4)
    logging (2.2.2)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    loofah (2.1.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    memoist (0.16.0)
    method_source (0.9.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.10.3)
    money (6.10.0)
      i18n (>= 0.6.4, < 1.0)
    multi_json (1.12.2)
    multi_logger (0.1.0)
      railties
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    net-ldap (0.11)
    nio4r (2.1.0)
    nokogiri (1.8.1-x64-mingw32)
      mini_portile2 (~> 2.3.0)
    nokogiri (1.8.1-x86-mingw32)
      mini_portile2 (~> 2.3.0)
    oauth (0.5.3)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.7.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    os (0.9.6)
    public_suffix (3.0.1)
    puma (3.11.0)
    rack (2.0.3)
    rack-protection (2.0.0)
      rack
    rack-test (0.8.2)
      rack (>= 1.0, < 3)
    rails (5.1.4)
      actioncable (= 5.1.4)
      actionmailer (= 5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      activemodel (= 5.1.4)
      activerecord (= 5.1.4)
      activesupport (= 5.1.4)
      bundler (>= 1.3.0)
      railties (= 5.1.4)
      sprockets-rails (>= 2.0.0)
    rails-assets-fullcalendar (3.7.0)
      rails-assets-jquery (>= 2, < 4)
      rails-assets-moment (>= 2.9.0, < 3)
    rails-assets-fullcalendar-scheduler (1.9.0)
      rails-assets-fullcalendar (~> 3.7.0)
      rails-assets-jquery (>= 2, < 4)
      rails-assets-moment (>= 2.9.0, < 3)
    rails-assets-jquery (3.2.1)
    rails-assets-jquery-ui (1.12.1)
      rails-assets-jquery (>= 1.6)
    rails-assets-jquery-ujs (1.2.2)
      rails-assets-jquery (> 1.8)
    rails-assets-jqueryui-timepicker-addon (1.6.3)
    rails-assets-js-cookie (2.2.0)
    rails-assets-lightbox (2.10.0)
      rails-assets-jquery (> 2)
    rails-assets-moment (2.19.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.1.4)
      actionpack (= 5.1.4)
      activesupport (= 5.1.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rchardet19 (1.3.7)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    retriable (3.1.1)
    ruby-oci8 (2.2.5-x64-mingw32)
    ruby-oci8 (2.2.5-x86-mingw32)
    rubyzip (1.1.7)
    sass (3.5.3)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    signet (0.8.1)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13-x64-mingw32)
    sqlite3 (1.3.13-x86-mingw32)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tiny_tds (2.1.0-x64-mingw32)
    tiny_tds (2.1.0-x86-mingw32)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    tzinfo-data (1.2017.3)
      tzinfo (>= 1.0.0)
    uber (0.1.0)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    zip (2.0.2)

PLATFORMS
  x64-mingw32
  x86-mingw32

DEPENDENCIES
  activerecord-sqlserver-adapter
  ar-octopus
  axlsx
  bootstrap-sass
  bootstrap_form
  byebug
  cmxl
  cocoon
  coffee-rails
  devise
  devise_ldap_authenticatable
  docx
  exception_notification
  flipper
  flipper-ui
  gmail
  google-api-client
  googleauth
  googlecharts
  money
  multi_logger
  omniauth-google-oauth2!
  puma
  rails
  rails-assets-fullcalendar!
  rails-assets-fullcalendar-scheduler!
  rails-assets-jquery!
  rails-assets-jquery-ui!
  rails-assets-jquery-ujs!
  rails-assets-jqueryui-timepicker-addon!
  rails-assets-js-cookie!
  rails-assets-lightbox!
  ruby-oci8
  sass-rails
  sqlite3
  tiny_tds
  tzinfo-data
  uglifier
  zip

BUNDLED WITH
   1.16.0

**Comment by jnunemaker** [comment]
What is the error? How is flipper configured for your app? What adapter are you using? What http server are you using (unicorn, puma, etc.)?

**Comment by jnunemaker** [comment]
Closing the issue since there is no direct bug report here but happy to help if I can and you still have a problem.

**Comment by krzcho** [comment]
I was finally able to reproduce this error on development: I was doubleclicking a link causing two simultaneous requests
The actual "nested transaction" error comes from the PStore

Here is my config:

require "flipper/adapters/pstore"

Flipper.register(:uae) do |actor|
  actor.shard.to_sym==:uae
end

... another 10 countries registered this way

Flipper.register(:is_admin) do |actor|
  actor.is_admin==1
end

Flipper.register(:is_hr) do |actor|
  actor.is_hr==1
end

Flipper.register(:enters_customer_stock) do |actor|
  actor.enters_customer_stock==1 || actor.is_admin==1
end

$flipper = Flipper.new(Flipper::Adapters::PStore.new("flipper-#{Rails.env}.pstore"))

then application is doing multiple per-actor checks:

reports_enabled = !($flipper[:no_reports].enabled? @current_user)
requests_enabled = $flipper[:requests].enabled? @current_user
requisitions_enabled = $flipper[:requisitions].enabled? @current_user
leaves_enabled = $flipper[:leaves].enabled? @current_user
surveys_enabled = $flipper[:surveys].enabled? @current_user
...

What could I do better here to prevent this error?

**Comment by jnunemaker** [comment]
Hmmm, what web server are you using? Puma? Unicorn? I'm wondering if this is simple due to the fact that you are using puma with multiple threads and hitting concurrency issues across threads. This could be solved by having a Flipper instance per thread, like Flipper.configure with a default Flipper instance does.

```ruby
Flipper.configure do |config|
  config.default { Flipper.new(Flipper::Adapters::PStore.new("flipper-#{Rails.env}.pstore")) }
end

# now you can use Flipper
Flipper.enabled?(:requests, @current_user)
```

Does that seem possible? It looks like PStore does support [thread safety optionally](https://ruby-doc.org/stdlib-1.9.2/libdoc/pstore/rdoc/PStore.html#method-c-new). If this is the case, we could make that a config option for the pstore adapter. 

The only other thing I can think is that a single pstore doesn't like being accessed by multiple processes at once. This wouldn't be something that Flipper is likely to solve, but you could use some sort of shared lock amongst the processes along with sleep or something to keep the processes from fighting each other. I suppose one could test this with a simple rack app loaded by unicorn with two processes doing calls to the same pstore file. Then hammer the app with traffic and see if it pops errors. 

Let me know if any of that helps.

**Comment by krzcho** [comment]
Hi, yes, it is puma and my changes have just decreased number of errors
I am not sure that more Flipper instances would do the job - there will still be a concurrency over a single file, won't be? PStore option seems more viable - will you provide a patch for it?
