### ISSUE TITLE
Using symbols messes up the memoized features

### ISSUE THREAD

**Issue by axos88** [jnunemaker/flipper#320]
After using a symbol for creating a flipper, when reading back the flipper names, it is returned as a symbol. But after a restart, it is returned back as a string.

Symbol names should probably be converted to strings before saving them to the memoized list.

**Comment by jnunemaker** [comment]
@axos88 thanks for taking the time to report. I don't quite understand what you mean here. What did you use/do to create the flipper? What do you mean by reading it back? Does after a restart mean a restarting the process or something else? 

> Symbol names should probably be converted to strings before saving them to the memoized list.

Do you mean in the memoized adapter/middleware? Or are you referring to something else?

**Comment by axos88** [comment]
```

$ bin/console

[3] pry(main)> CD.flipper
=> #<Flipper::DSL:0x007fa97d6ed740
 @adapter=#<Flipper::Adapters::Redis:0x007fa97d6ed7e0 @client=<Redis::Namespace v1.5.3 with client v3.3.5 for redis://127.0.0.1:6379/0/dh_import_development:feature_toggles>, @name=:redis>,
 @instrumenter=#<CD::Services::FlipperInstrumenter:0x007fa97d6ed7b8>,
 @memoized_features={}>
[4] pry(main)> CD.flipper[:foo].disable
=> true
[5] pry(main)> CD.flipper
=> #<Flipper::DSL:0x007fa97d6ed740
 @adapter=#<Flipper::Adapters::Redis:0x007fa97d6ed7e0 @client=<Redis::Namespace v1.5.3 with client v3.3.5 for redis://127.0.0.1:6379/0/dh_import_development:feature_toggles>, @name=:redis>,
 @instrumenter=#<CD::Services::FlipperInstrumenter:0x007fa97d6ed7b8>,
 @memoized_features={:foo=>#<Flipper::Feature:70182962723320 name=:foo, state=:off, enabled_gate_names=[], adapter=:memoizable>}>
[6] pry(main)> CD.flipper.features.map(&:name)
=> [:foo]
[7] pry(main)> exit

$ bin/console

[3] pry(main)> CD.flipper
=> #<Flipper::DSL:0x007fa0b8334720
 @adapter=#<Flipper::Adapters::Redis:0x007fa0b8334900 @client=<Redis::Namespace v1.5.3 with client v3.3.5 for redis://127.0.0.1:6379/0/dh_import_development:feature_toggles>, @name=:redis>,
 @instrumenter=#<CD::Services::FlipperInstrumenter:0x007fa0b8334860>,
 @memoized_features={}>
[4] pry(main)> CD.flipper.features.map(&:name)
=> ["foo"]
[5] pry(main)> CD.flipper
=> #<Flipper::DSL:0x007fa0b8334720
 @adapter=#<Flipper::Adapters::Redis:0x007fa0b8334900 @client=<Redis::Namespace v1.5.3 with client v3.3.5 for redis://127.0.0.1:6379/0/dh_import_development:feature_toggles>, @name=:redis>,
 @instrumenter=#<CD::Services::FlipperInstrumenter:0x007fa0b8334860>,
 @memoized_features={:foo=>#<Flipper::Feature:70164167928740 name="foo", state=:off, enabled_gate_names=[], adapter=:memoizable>}>
```

Notice how foo changes from symbol to string over the restart / reinitialization of the Flipper instance.

**Comment by jnunemaker** [comment]
Oh, also what version of ruby and flipper are you using?

**Comment by jnunemaker** [comment]
Ah, I see. I'll get a fix out. Should be easy.

**Comment by jnunemaker** [comment]
Ok, I dug into the source and this is expected. name is whatever you use. It defaults to a string from the adapters, but if you use a symbol it will be that. 

https://github.com/jnunemaker/flipper/blob/196946c63aee1eaa09fa25e945cdbff896fe71e5/lib/flipper/feature.rb#L28

If you always want a string, key is what you should use. It is confusing. Part of me feels like I should get rid of name and just have key. key is always a string for adapter storage. FWIW, I use symbols in ruby code like you are, I just never use Feature#name for anything. Whatever you need it for, I recommend  using `CD.flipper.features.map(&:key)` or `CD.flipper.adapter.features`.

Does that help? Closing as this is currently intended, but I'm open to more discussion. Do you think it is important that name is always a string or always a symbol?

**Comment by axos88** [comment]
I'm just saying that it's unexpected, and leads to errors if the name is not consistent. What I mean is that I create a feature, and the name is returned as a symbol. Then I restart the application, and now the name is returned as a string... Using the key works now, but i'm a bit puzzled what the difference is between them.

**Comment by jnunemaker** [comment]
@axos88 yep, I totally understand the confusion. My hope was that one day the adapter would allow setting name as well. Say you have a new feature with a key of request_tracing. I'd like for someday to have a nicer version for the UI like "Request Tracing". The goal was for name to be used like that, but currently it is not, which causes the confusion. For now, stick to key and I'll think about whether it makes sense to remove name entirely or start work on supporting a more human readable name in addition to the key. Does that help clear it up at all?

**Comment by axos88** [comment]
Yep. might want to rename it to description though.

**Comment by andyw8** [comment]
I ran into a problem that I think may be related to this. With ActiveSupport notifications (https://github.com/jnunemaker/flipper/issues/513) sometimes `feature_name` in the payload was a string, at other times a symbol. I couldn't figure out the pattern, but for safety I chose to always convert to a string before comparing.
