### ISSUE TITLE
Move Flipper::UI config to Flipper::UI::Configuration

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#326]
Specifically, these 3 options:

https://github.com/jnunemaker/flipper/blob/49167082d655d07141622bced1f8ac98bf9f5904/lib/flipper/ui.rb#L20-L32

Add backwards incompatible note to changelog as well so people know how to upgrade. Another option would be to leave the reader and writer methods on Flipper::UI and make them raise with an error that describes the code changes necessary. We could leave those for a few versions.

**Comment by AlexWheeler** [comment]
*Another option would be to leave the reader and writer methods on Flipper::UI and make them raise with an error that describes the code changes necessary*

I really like this idea, we can link to the docs too so users know exactly what to do
