### ISSUE TITLE
Questions regarding Percentage of Actors performance

### ISSUE THREAD

**Issue by tleish** [jnunemaker/flipper#335]
I read the following in some of the documentation:

> **Percentage of Actors**
> Turn this on for a percentage of actors (think user, member, account, group, whatever). Consistently on or off for this user as long as percentage increases. Think slow rollout of a new feature to a percentage of things.

and

> **Caveats**
> The individual actor gate is typically not designed for hundreds or thousands of actors to be enabled. This is an explicit choice to make it easier to batch load data from the adapters instead of performing individual checks for actors over and over. If you need to enable something for more than 20 individual people, I would recommend using a group.

I also read in comments of a code example something about actor's flipper_id:

```ruby
flipper = Flipper.new(adapter)

# turn search on for 10 percent of users in the system
flipper[:search].enable_percentage_of_actors 10

# checks if actor's flipper_id is in the enabled percentage by hashing
# user.flipper_id.to_s to ensure enabled distribution is smooth
flipper[:search].enabled? user
```

In understanding the scalability and performance of Percentage of Actors, I want to better understand:

* Can the Percentage of Actors gate support support hundreds or thousands of users (unlike individual actor)?
* If yes, how does it keep track of the state of a feature for a given actor within thousands of actors?  Is there a single redis key with an array of user ids or thousands of redis entries?  What is the flipper_id and how is it stored/used?

**Comment by AlexWheeler** [comment]
Hi @tleish, great question!  The percentage_of_actors gate will store one key in redis (or 1 row in postgres if you're using activerecord adapter for example) no matter how many actors you have in your datastore.

Check out [this post I wrote](http://alexwheeler.io/ruby/2017/07/03/feature-flipping-deli-coffee-hashing-algorithms.html) on how the percentage_of_actors gate works and let me know if you still have questions!  You can skip down to the Percentage Of Actors section.

**Comment by jnunemaker** [comment]
Closing this to keep things tidy, but do feel free to hit us up with more questions if you have any. Happy to help!

**Comment by tleish** [comment]
Hi @AlexWheeler - your article was exactly what I was looking for.  Thank you!

**Comment by alessandrostein** [comment]
> Check out [this post I wrote](http://alexwheeler.io/ruby/2017/07/03/feature-flipping-deli-coffee-hashing-algorithms.html) on how the percentage_of_actors gate works and let me know if you still have questions! You can skip down to the Percentage Of Actors section.

Unfortunately, the post is no longer available, but I would like to know how the Percentage Of Actors works.

**Comment by jnunemaker** [comment]
@alessandrostein I dropped the url alex shared in the wayback machine and found this for you:

https://web.archive.org/web/20240424184411/http://alexwheeler.io/ruby/2017/07/03/feature-flipping-deli-coffee-hashing-algorithms.html

Let me know if you have questions.

**Comment by alessandrostein** [comment]
> [@alessandrostein](https://github.com/alessandrostein) I dropped the url alex shared in the wayback machine and found this for you:
> 
> https://web.archive.org/web/20240424184411/http://alexwheeler.io/ruby/2017/07/03/feature-flipping-deli-coffee-hashing-algorithms.html
> 
> Let me know if you have questions.

Thank you so much, it works 🥳
