### ISSUE TITLE
Solution to seed features?

### ISSUE THREAD

**Issue by archonic** [jnunemaker/flipper#340]
I'm looking for a solution to seeding features with Rails. The codebase makes references to features that won't exist until they're created through the UI. Seeing as new features don't exist without changes to code, it makes sense to me that features would be manageable through seeds and migrations (for all adapters). That would also make environment management and deploying easier.

With the redis adapter I created a boolean feature and enabled it, and opened a console to dump the key. It looks like this:
```
\r\u001A\u001A\u0000\u0000\u0000\u0013\u0000\u0000\u0000\u0002\u0000\u0000\aboolean\t\u0004true\xFF\a\u0000\xA8\xF7\xB9\x91\xFF\xA1b\xAA
```

Given the complexity of that, it seems to underline the need for this to be managed within the gem.

Update:
I've figured out `Flipper.enable :whatever` for getting tests to pass but I'm still curious about seeding/migrating features.

**Comment by jnunemaker** [comment]
@archonic any reason not to use the same thing for seeding features? I don't currently seed features, so I can't guarantee it will work, but I'm curious if it does for you and believe it should.

I also do the same for tests. The only other test thing I do is use the memory adapter in `setup` (minitest, etc.) or `before` (rspec).

```
require "flipper/adapters/memory"
Flipper.instance = Flipper::Adapters::Memory.new
```

I use https://featureflipper.com, which I'm building for all to use soon™. It has the concept of environments built in (development, staging, production, or whatever). All environments inherit from production, but can override. This makes it super easy for the app to work similar to production from your own development laptop, but customize new things you are working on and avoids the need to seed.

If you want to know more about it, you can drop your email on the form on https://featureflipper.com or feel free to email me: john@featureflipper.com.

If you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard other than what you mentioned here). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly (same as above). I'm just always curious. :)

**Comment by archonic** [comment]
Interesting idea for a service, although I don't know that I'd use it. I've built a custom feature flipper and it was quite simple and easy. I reached for flipper because I was confident in it's ability to scale and it's work I didn't have to do myself.

Would this service be responsible for syncing features and their attributes across services and environments? If I have to make an external call to check if a feature is available, I wouldn't use it.

What went well is it worked out of the box and the interface is quite good. I wasn't sure what the % of time gate was for, but canary testing features without having to route a % of requests to servers running experimental branches is very very handy.

What didn't go well was just this issue - no solution to seeding or migrating features. I can think of a few ways to tackle that myself though. I don't think I'd pay for a solution there.

**Comment by jnunemaker** [comment]
> I've built a custom feature flipper and it was quite simple and easy. I reached for flipper because I was confident in it's ability to scale and it's work I didn't have to do myself.

So great to hear!

> Would this service be responsible for syncing features and their attributes across services and environments?

Yes.

> If I have to make an external call to check if a feature is available, I wouldn't use it.

Totally get this! At first this was why I was like no one would use this. Then, I put on my thinking hat and came up with several ways around this. The key to me is that feature checks are fast (ie: reads are local to datacenter/region/whatever). 

What I'm doing right now is forcing a sync adapter for cloud. The sync adapter uses two adapts (local and remote) and ensures that the local matches the remote every N seconds. All reads (feature checks) are to the local adapter and all writes go to the remote and then the local if remote succeeded. 

The benefit of a service like featureflipper.com is less about the storage of feature data and more about organization, permissions, auditing, stats and the like. Without storage though, providing permissions, auditing and all that is more painful. Having local storage with all those other capabilities provided for you feels compelling enough to me (and some others I've chatted with). 

Currently, the sync (e.g. the external net/http call to cloud) does happen in the main thread, but timeouts can be tuned and it rescues all errors to avoid that sync disrupting your application. That said, we are planning on moving that sync to a background thread to avoid any disruption at all (even the time of the external call). At that point, the only extra time would be an extra local flipper write on the rare sync where something has changed in the remote.

This should make using flipper with remote storage free from a performance standpoint. I toyed with the idea of an external daemon/service as well that would run in your infra as sidecar process or N per datacenter/region, but for now I'm going with a fatter client.

> What went well is it worked out of the box and the interface is quite good.

I've spent a lot of thinking and time on both of these so it really warms my :heart: to hear this. Thanks!

> I wasn't sure what the % of time gate was for, but canary testing features without having to route a % of requests to servers running experimental branches is very very handy.

Totally! At GitHub we actually re-label % of time as "Dark Shipping/Load Testing". 

Again, thanks for taking the time to create this issue and to even follow up and answer my questions. Appreciated!

**Comment by jnunemaker** [comment]
Oh, forgot to link an example of [reads for sync adapter](https://github.com/jnunemaker/flipper/blob/a36dcc3957b2f501d219399965db74dc55e0adce/lib/flipper/adapters/sync.rb#L44-L57) and an [example of writes](https://github.com/jnunemaker/flipper/blob/a36dcc3957b2f501d219399965db74dc55e0adce/lib/flipper/adapters/sync.rb#L59-L87). Also, [here is where cloud sets up the sync adapter](https://github.com/jnunemaker/flipper/blob/a36dcc3957b2f501d219399965db74dc55e0adce/lib/flipper/cloud/configuration.rb#L91-L97) using whatever you provide as your local (e.g. redis, mongo, active record, etc.) and cloud's http adapter as the remote.

**Comment by archonic** [comment]
Awesome, thanks for the answers here. I'll have a look at the flipper service closer to our launch (and flippers!). Right now we're too stingy for Slack :stuck_out_tongue:. Is there a mailing list for the flipper service?

**Comment by jnunemaker** [comment]
@archonic https://featureflipper.com/ has a mailing list signup.
