### ISSUE TITLE
Duplication in readme! 

### ISSUE THREAD

**Issue by EmmaB** [jnunemaker/flipper#348]
A tiny thing: the "# check if search is enabled" example in the readme appears twice.

**Comment by AlexWheeler** [comment]
```
# check if search is enabled.
# search is not enabled so this will print 'No search for You'
if Flipper.enabled?(:search)
  puts 'Search away!'
else
  puts 'No search for you!'
end

puts 'Enabling Search...'
# search feature is enabled w/  `Flipper.enable(:search) below so this prints Search away!`
Flipper.enable(:search)

# check if search is enabled...
if Flipper.enabled?(:search)
  puts 'Search away!'
else
  puts 'No search for you!'
end
```
Good morning @EmmaB, if you're mentioning the above ^ this is actually intentional.  I've added two additional comments to explain what's happening.  Does that make sense?  Is there any way this could be improved?

**Comment by EmmaB** [comment]
Aha! That makes it much clearer, and many thanks! 

Only thing I'd tweak is just in the comments: lower case 'y' on 'you', and put 'Search away!' in inverted commas. 

And maybe putting the `Flipper.enable(:search)` before the `puts "Enabling search..."` might read more fluidly. Not sure. 

Many thanks!

**Comment by AlexWheeler** [comment]
great, going to close now, but if you come across any inconsistencies in the docs or things you think could be improved definitely open a PR!

**Comment by EmmaB** [comment]
I definitely will. Thanks for a fantastic gem and your quick response.

**Comment by jnunemaker** [comment]
@EmmaB you are welcome! What are you using flipper for? Kicking the tires? Already in production? I am always curious 😄. If you aren't comfortable dropping it here, feel free to email me directly john@featureflipper.com.
