### ISSUE TITLE
Flipper UI can't handle feature names containing _features

### ISSUE THREAD

**Issue by EmmaB** [jnunemaker/flipper#352]
If the name contains _features, clicking on the name on the UI index page has no effect. 

<img width="529" alt="screen shot 2018-04-30 at 12 13 57" src="https://user-images.githubusercontent.com/679014/39424776-25645ad4-4c70-11e8-946e-cb80a4abe939.png">

In the screenshot, clicking on "another_features" or "production_features" does not take you to the edit page. (Admittedly, it's a bad name, anyway. But still.)

**Comment by jnunemaker** [comment]
@EmmaB thanks for reporting! I've got a bug fix in https://github.com/jnunemaker/flipper/pull/353. Should be out soon.
