### ISSUE TITLE
A way to detect whether a feature exists?

### ISSUE THREAD

**Issue by brandondrew** [jnunemaker/flipper#354]
Forgive me if I've simply overlooked it, but it doesn't appear that there's a method to check whether a feature exists yet built into Flipper, just whether it has been enabled or disabled.

Here's what I do (by adding this to my `features.rb` initializer) but since this appears (to me at least) to be something that everyone using Flipper will need, I am guessing I might have  missed something.

```ruby
def feature_exists?(name)
  Flipper.features.map(&:name).include?(name.to_s)
end
```

If I did miss it, then please interpret this issue as a request for it to be added to the documentation.

If it doesn't exist yet and you'd like it added, I'd be happy to submit a PR for `Flipper.feature_exists?` (or whatever).

If there is some reason this is a bad idea, I'd love to hear it.  Thanks.

--- 

For what it's worth, my use case is for setting defaults.  In my `features.rb` I define the default settings to add to the database if and only if they are not already in the database.  I'm using the ActiveRecord adaptor, but I assume this is useful for any adaptor except possibly the memory adaptor.

```ruby
def default_to_enabled(name)
  Flipper.enable(name) unless feature_exists?(name)
end

def default_to_disabled(name)
  Flipper.disable(name) unless feature_exists?(name)
end

default_to_enabled('some_feature_name')
default_to_disabled('some_other_feature_name') 
```

**Comment by jnunemaker** [comment]
@brandondrew hi! There is no way to tell if one exists beyond checking the set of known features.  Do you really care that the feature exists or just that it is enabled/disabled? Is this for seeding development and/or other environments or some other use case? 

> If there is some reason this is a bad idea, I'd love to hear it. Thanks.

I can't say that the idea is bad per say, but my gut says that I don't want people worrying about whether a feature row/key/whatever exists in a database somewhere. I'd rather they focus on whether the feature is enabled/disabled.

**Comment by alainravet** [comment]
I created something similar to @brandondrew 
```ruby
module Features
  def self.settable_via_the_flipper_ui
    Flipper.features.to_a.map(&:name)
  end
end
```
No big deal to create, but it just took some - light - digging.

(My goal was to auto-maintain (add new and remove obsolete) features keys after each deploy so that the Flipper UI page would always been up-to-date.)

**Comment by brandondrew** [comment]
Hi @jnunemaker  I'm trying make sure the feature is set in the database according to a default that can be available and set with a deployment.  My use case is features that were previously just hard-coded in a legacy app I inherited, which the client was needing to turn off and on periodically.  I'd rather not add a step in the deployment to set them in the database, since:

1. It's not automated 
2. I don't necessarily always do the deployments for this client.

I could have skipped the active record adapter entirely, but then any future change would require a config file change and a deployment.  I want to be able to make the change immediately (_and_ have it be persistent). Flipper has a pretty nice UI, so I'm happy to use it 😉.

I thought about using migrations to make the changes, but I'm not a fan of putting too much data into migrations.  

Seed files seem more suited to things you *don't* expect to change. 

So right now my defaults are set in an initializer, and it has these benefits:

1. It's in the Git repo, and
2. it takes effect if nothing is in the database, so
3. the code can rely on 2-value logic (features are either on or off) instead of having to handle nil (the 3rd possibility);
4. it doesn't overwrite the database setting, so 
5. the setting can be immediately and persistently changed from the web UI for any given environment without need for a code or config change or a deployment; and 
6. it doesn't pollute migrations with data or seed files with regularly-changing data, and most of all 
7. it works non-disruptively with a normal deployment. 

I couldn't figure out a better way to get these benefits, but perhaps there is one.  Perhaps my aversion to data in migrations isn't entirely rational.  I've seen it end up as a giant mess in projects where people have done that, but perhaps there is a good way of doing it... I'm not entirely sure.

**Comment by jnunemaker** [comment]
@brandondrew :cool: Thanks for all the context. Super helpful. We have `add` and `remove`, so I think having something for existence makes a lot of sense. I'm 🆗 with adding `exists?` to `Flipper::Feature`, `Flipper::DSL` and to the methods delegated by `Flipper` itself. I can take a stab at some point, but I'd love a PR with some tests if you or anyone else has time.
