### ISSUE TITLE
application_breadcrumb_href error in initializer in 0.15

### ISSUE THREAD

**Issue by veganstraightedge** [jnunemaker/flipper#355]
Hi! Thanks for Flipper. It's great.

In today's PR from @dependabot that version bumps Flipper from `0.14.0` to `0.15.0`, a new exception cropped up in our `flipper.rb` initializer.

```ruby
ArgumentError: wrong number of arguments (given 1, expected 0)
/tmp/build_64d223c72805005df2eb2e5e2ba13d57/vendor/bundle/ruby/2.5.0/gems/flipper-ui-0.15.0/lib/flipper/ui.rb:25:in `block (2 levels) in singleton class'
/tmp/build_64d223c72805005df2eb2e5e2ba13d57/config/initializers/flipper.rb:18:in `<top (required)>'
```

```ruby
Flipper::UI.application_breadcrumb_href = '/top-secret'
```

What's the new way to this same behavior in the new version?

Thanks

**Comment by jnunemaker** [comment]
> Hi! Thanks for Flipper. It's great.

Thanks! I really appreciate you taking the time to say that, even after hitting some friction.

> What's the new way to this same behavior in the new version?

Something like this should work:

```ruby
Flipper::UI.configure do |config|
  config.application_breadcrumb_href = '/top-secret'
end
```

More examples: https://github.com/jnunemaker/flipper/tree/042facb10d2269ed93c1563f290d32e798eb221d/docs/ui#configuration

Let me know if that doesn't straighten things out for you. 

If you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard other than what you mentioned here). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly john@flippercloud.io. I'm just always curious. :)
