### ISSUE TITLE
Exclude List

### ISSUE THREAD

**Issue by drlube** [jnunemaker/flipper#366]
Hi @jnunemaker,

We love Flipper :).

Sorry if this has been asked before. I was curious if there is a way to enable a feature for all _except_ certain actors. We have dozens of actors and while our enabled list will grow, our exclusion list will mostly stay the same, so you can see how it would help with maintenance. Or, would you recommend using groups in this case?

Thanks ahead of time,

Jamie

**Comment by jnunemaker** [comment]
Groups work great for this. Another option is to have a negative feature that enables actors. If you have feature named foo you can have foo_disabled. Add actors you want disabled to foo_disabled and then in your code you do this which is a bit awkward but can be wrapped up in one spot:

```
If Flipper.enabled?(:foo, user) && !Flipper.enabled?(:foo_disabled, user)
  # do stuff 
end
```

**Comment by jnunemaker** [comment]
Here is a related longer explanation https://github.com/jnunemaker/flipper/pull/94#issuecomment-162917454. The trick is that flipper is really about enabling, not disabling. Adding disabling muddies up a simple concept. I’d be open to an approach that didn’t muddy things up but I haven’t come up with anything yet.
