### ISSUE TITLE
Performance of individual actor set

### ISSUE THREAD

**Issue by jmr0** [jnunemaker/flipper#367]
Hello!

I know that enabling thousands of individual actors does not scale, since checking a feature for any individual actor requires the entire set of actors to be loaded in advance. 

That being said, I'm wondering if you had any suggestions for supporting the following scenario: I want to be able to turn on a feature for some % of actors for those users on our platform that are logged out / anonymous, (with Flipper ID `Anon:<random_uuid_from_cookie>` let's say), but in addition to that, we would like to persist those enabled features once they sign up (in which case their Flipper ID would look like `User:<permanent_user_id>`). The intuitive but non-scalable way of doing it is to check the anonymous user's feature as they sign up and then add their new permanent User ID to the set of individual actors if that feature was enabled for the anonymous ID. I've also considered just relying on device-specific anonymous ID's exclusively, but we'd like to persist features across devices once a user is signed up.

Is there a reasonable path I could take for introducing performant individual actors (by inverting the structure from Feature -> Set of Actors to Actor -> Set of Features in some scenario)? Do you have any recommendations otherwise?

Thanks so much

**Comment by jnunemaker** [comment]
Super sorry for the delay on this. Great question. I haven't needed to do this, but it seems like a completely legit problem. I've considered allowing Flipper actor stuff to be configurable. Maybe config.unlimited_actors = true or something equal silly? If that is set, it would stop loading all the actors and instead only load the one being checked. Maybe it could even be configurable per feature? Something like that would remove the limit a bit or at least raise it. I don't want to change the current default as that would have some huge ripples from a performance perspective. 

For your problem, you could keep track of record for each anon user that signs up. Then, you could have a flipper group that is enabled for the feature and returns true if the user has a record. That is one easy way to keep consistency. The only cost is an extra record of storage for each user that was enabled anonymously AND signed up, plus the lookup from the group. Not clean/perfect, but maybe do-able? 

I'd definitely like to know what others do. At GitHub we have some features that allow actors to opt-in and store that opt-in in [GitHub KV](https://github.com/github/github-ds#githubkv) along with a group check like I mentioned above. It has worked fine and gets us around the actor set size caveat.

**Comment by jnunemaker** [comment]
Closing but feel free to keep the conversation rolling.

**Comment by jmr0** [comment]
Thanks John! I think that's a great way of doing it. We're working on a different approach currently:

We assign a random flipper_id (in a cookie, let's say) to anonymous users that is then associated with their account once they sign in or sign up, and then we always use this flipper_id to check whether a feature is enabled (rather than their actual user id). If an anonymous user signs in and we detect that we had already assigned a feature_id for that user, we make sure to use that instead. Let me know if that makes sense.
