### ISSUE TITLE
Gem Dependencies

### ISSUE THREAD

**Issue by voltechs** [jnunemaker/flipper#373]
Hello! 👋

Thank you for this gem and for your efforts behind it!

I was doing some maintenance on a project that leverages `flipper`, and after doing a `bundle update` and getting all the latest and greatest, I discovered an error while running specs.

```
An error occurred while loading spec_helper.
Failure/Error: require 'flipper'

LoadError:
  cannot load such file -- rack/body_proxy
# ./app/helpers/flipper.rb:2:in `require'
```

Turns out, we don't need `rack` for our project, however it appears `flipper` does. Upon adding it to our Gemfile to get passing, I then went to investigate the issue.

From my sleuthing, it appears that `flipper` doesn't leverage the `require_runtime_dependency` feature of the `gemspec` file. This makes dependency management (done by RubyGems) difficult.

I forked the project and went to add the dependency but realized that this is a much more prolific issue throughout the entire project including the libraries and extensions (`redis`, `activerecord`, etc)

Would you consider moving the gems listed in the `Gemfile` into the `.gemspec` files? I'm happy to help with this process as well if you'd like.

**Comment by hex337** [comment]
I'm also running into this issue.

**Comment by jnunemaker** [comment]
Oh, and if there is something above all this I'm missing, please let me know. I've always used `add_dependency` and have never used `require_runtime_dependency` so I'm not sure how they differ.
