### ISSUE TITLE
Trying to use the `Flipper::Adapters::Memory` for tests with `Flipper::Middleware::Memoizer`

### ISSUE THREAD

**Issue by hmcfletch** [jnunemaker/flipper#375]
I seem to be running into issues using the memory adapter in conjunction with the memoization middleware in my specs. The issue is present in both versions `0.15.0` and `0.16.0`.

Flipper definition:
```ruby
if Rails.env.test?
  require 'flipper/adapters/memory'
  adapter = Flipper::Adapters::Memory.new
else
  client = Redis.new(host: uri.host, port: uri.port, password: uri.password, db: 1)
  Flipper::Adapters::Redis.new(client)
end

$flipper = Flipper.new(adapter, instrumenter: ActiveSupport::Notifications)
```

Error I get in all of my acceptances tests:
```
NoMethodError:
   undefined method `memoize=' for #<Array:0x00007fd3d9ebd9a8>
# /Users/Les/.rvm/gems/ruby-2.5.1@latergram/gems/flipper-0.15.0/lib/flipper/middleware/memoizer.rb:71:in `ensure in memoized_call'
# /Users/Les/.rvm/gems/ruby-2.5.1@latergram/gems/flipper-0.15.0/lib/flipper/middleware/memoizer.rb:71:in `memoized_call'
# /Users/Les/.rvm/gems/ruby-2.5.1@latergram/gems/flipper-0.15.0/lib/flipper/middleware/memoizer.rb:42:in `call'
```

Not sure what else to provide. Let me know if there is anything else you need. Or better yet, let me know if I am doing something crazy. :p

**Comment by jnunemaker** [comment]
It looks like you are missing `adapter =` on the line before `Flipper::Adapters::Redis.new(client)`. Are you sure that is the exact setup? Closing to keep things tidy but happy to keep helping.

**Comment by hmcfletch** [comment]
Sorry, copy and paste error. This is the full code snippet:

```ruby
adapter =
  if Rails.env.test?
    Flipper::Adapters::Memory.new
  else
    client = Redis.new(host: uri.host, port: uri.port, password: uri.password, db: 1)
    Flipper::Adapters::Redis.new(client)
  end

$flipper = Flipper.new(adapter, instrumenter: ActiveSupport::Notifications)
```

The Redis adapter works fine. It's the memory adapter that I am running into problems with.

**Comment by jnunemaker** [comment]
If you aren't using the flipper default instance, you'll have to also add setup env middleware. I wonder if that is the problem. Are you using the setup env middleware ala [the docs](https://github.com/jnunemaker/flipper/blob/4275e909def244c03bc19127b462e0c2204e7865/docs/Optimization.md)?

**Comment by hmcfletch** [comment]
Feeling super dumb. I had added something right at the end of the `config.default` block that looped through an array (which was frozen). Said array was getting returned and breaking things for me.

Thanks for the prompt replies. You're doing amazing work.
