### ISSUE TITLE
Flags randomly disappearing in UI with Redis adapter

### ISSUE THREAD

**Issue by jon-eckstein** [jnunemaker/flipper#383]
Hi,
I have an issue where the UI will lose features such that if I browse to the FlipperUI root it will give me the T.Swift Blank Space page even though I know there are flags.  I'm using the Redis adapter and if I query Redis directly via `client.smembers("flipper_features")` it will return the flags I'm expecting. So I know redis isn't ejecting those keys and I can verify the gate is working corrrectly.  Is there anything I can do? 
Thanks.

**Comment by AlexWheeler** [comment]
Hey @jon-eckstein as cool as T Swift is let's help ya with seeing those flipper features instead. Can you provide a bit more info:

* Flipper version
* Rails version if using Rails

and paste the following:

* Your Flipper configuration (if using Rails `initializers/flipper.rb`

* routes.rb where you're mounting Flipper::UI (or wherever you mount Flipper::UI if not using Rails)

**Comment by jon-eckstein** [comment]
Thanks @AlexWheeler, let me know if you need anything else.

#### Flipper version: 
flipper 0.16
flipper-redis 0.16
flipper-ui 0.16

#### Rails:
5.0.6

#### Other:
Hosted on Heroku with Redis Cloud redis add-on

#### Flipper config:
```ruby
Flipper.configure do |config|
  config.default do
    redis_client = Redis.new(url: ENV["REDIS_URL"])
    adapter = Flipper::Adapters::Redis.new(redis_client)

    # pass adapter to DSL instance
    Flipper.new(adapter)
  end
end
```

#### routes.rb
```
constraints CanAccessFlipperUI do
      mount Flipper::UI.app(Flipper) => '/flipper'
    end
```

#### CanAccessFlipperUI
```
class CanAccessFlipperUI
  def self.matches?(request)
    current_user = request.env["warden"].user
    current_user.present? && current_user.admin?
  end
end
```

**Comment by jnunemaker** [comment]
@jon-eckstein very weird. I haven't hit this issue and I can't think of anything obvious that could cause it. 

Are you using Puma or a threaded web server? If so, I'm betting that you will need to use a [connection pool](https://github.com/mperham/connection_pool) around redis. Though flipper is most likely thread safe (I use it with puma without issue), you will likely need something around the redis instance. 

I don't want to send you in the wrong direction, but that is the only thing that comes to mind.

**Comment by jnunemaker** [comment]
I'm going to close the issue to keep things clean but please feel free to keep working through this here with us.

**Comment by nunommc** [comment]
This is currently happening to me every time I run rspec, then I need to initialize my flags for development over again.

This is happening even though for development I'm using Redis adapter, and for the tests Memory adapter.
