### ISSUE TITLE
Consideration for restricting users

### ISSUE THREAD

**Issue by mkadlec** [jnunemaker/flipper#388]
As it is now, the Flipper gem allows All users, or a select amount.

It would be nice to have a way to enable everyone _except_ the users defined.

Possibly a new gate called disable?

**Comment by jnunemaker** [comment]
@mkadlec Flipper is really focused on enabling and less on disabling ([see caveat 2](https://github.com/jnunemaker/flipper/blob/a04de088bed7f28209f5586a438cf78b975594aa/docs/Caveats.md)). That said, I'd love to know, as specific as you can provide me with, what your use case was for disabling a few users. That would help me think through the problem a bit more. I'm going to close this to keep things tidy but I'd love to keep the conversation going.

Also, if you don't mind, I would love to know what you are using flipper for as well and how it is working out for you (what went well, what was hard other than what you mentioned here). If you aren't comfortable leaving that information here in a public comment, feel free to email me directly john@flippercloud.io. I'm just always curious. :)
