### ISSUE TITLE
Where to put default values for redis adapter?

### ISSUE THREAD

**Issue by vdhpieter** [jnunemaker/flipper#390]
We're already using flipper with the memory adapter and no UI (it's awesome) but now we want to move to the Redis adapter with the UI. I'm having one problem I really don't know how to solve.

For now, we have a wrapper class for Flipper and when we initialize it we set all our flags as hardcoded in our code. When we switch to Redis we don't want to reinitialize all flags when we create the class because they could have been changed through the web UI. I was thinking of moving the initialization to `initializers/flipper.rb` but now we get errors when compiling our assets because Redis is not reachable...

My question is where do we need to init our flags when we only want to do this on startup? If the initializer is the best choice do we have to wrap it in a block to check if Redis is present or?

**Comment by jnunemaker** [comment]
@vdhpieter if you use the flipper default config stuff it should solve that problem. You just move your redis configuration inside the block. Something like this would make it lazy loaded so assets wouldn't use it (assuming you have no flipper calls in stylesheets/js):

```ruby 
require 'flipper/adapters/redis'

Flipper.configure do |config|
  config.default do 
    client = Redis.new
    adapter = Flipper::Adapters::Redis.new(client)
    Flipper.new(adapter)
  end
end
```

On the first call to `Flipper.enabled?(...)` or similar methods that would setup the redis connection for that thread. You can then get rid of your wrapper too. Does that help?

Closing this to keep things tidy, but please feel free to keep responding.

**Comment by vdhpieter** [comment]
I was more looking for a way to initialize features from code with a value that then will be stored in redis so that we don’t need to type in the feature key in the UI

**Comment by vdhpieter** [comment]
That’s what I want to avoid. So ideally it would check if it exists in redis and put in if it doesn’t, I dove a bit deeper in the code and wrote this functionality my self for now :-)

**Comment by jnunemaker** [comment]
Gotcha. One way I’d check (and perhaps flipper needs a method) is to see if
the gate values for the feature equal the default gate values for adapters.
If they are equal then you could seed stuff.
