### ISSUE TITLE
undefined method `add' for #<Flipper::Adapters::Redis:0x00007ff5a6203a48>

### ISSUE THREAD

**Issue by stlewis** [jnunemaker/flipper#391]
Given the following configuration:

```ruby
Flipper.configure do |config|
  config.default do
    client = Redis.new
    adapter = Flipper::Adapters::Redis.new(client)
    Flipper.new(adapter)
  end
end
```
Upon trying to invoke this line:
```ruby
  Flipper.enable(:my_feature)
```

I'm getting back this error/trace:

`/Users/stevelewis/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/flipper-0.16.0/lib/flipper/adapters/memoizable.rb:48:in `add': undefined method `add' for #<Flipper::Adapters::Redis:0x00007ff5a6203a48> (NoMethodError)`

FWIW, in my Gemfile:

```
gem 'flipper'
gem 'flipper-redis'
```

Do I need to peg one/both of these down to a version to get them to play nicely together?

**Comment by AlexWheeler** [comment]
Hey @stlewis I see that you're using flipper 0.16.0, but what version of `redis` and `flipper-redis` are you running?

I'm thinking your `redis` gem may be an older version than flipper-redis requires so bundler is resolving to use a really old version of flipper-redis that does not have a redis version constraint on it

**Comment by stlewis** [comment]
@AlexWheeler It turns out my version of Redis was actually too _new_, but you had the right idea! I made sure that my redis gem was grabbing an appropriate version, and re-installed flipper-redis. 

Thanks for the help!

**Comment by AlexWheeler** [comment]
Great! I'll find some time to try out/test flipper-redis with redis > 4.0 and bump version constraint if all is good
