### ISSUE TITLE
updated_at field not being updated in features table

### ISSUE THREAD

**Issue by pxr13** [jnunemaker/flipper#393]
The `updated_at` field for all rows in our features table is the same DateTime value as the `created_at` field, even after updates like changing percentage of actors through the web UI. 

We're looking to use the `updated_at` field to notify teams of old flippers that should be removed from our codebase.

This is our adapter set up:

```ruby
module Company
  def self.flipper
    # flips are loaded by first:
    # 1/ checking the activesupport memory store for the flipper
    # 2/ checking the memcached store (through dalli)
    # 3/ checking activerecord
    @flipper ||= begin
      ar_adapter = Flipper::Adapters::ActiveRecord.new
      dalli_adapter = Flipper::Adapters::Dalli.new(ar_adapter, Dalli::Client.new(ENV["MEMCACHE_SERVERS"].to_s.split(",")), 10.hours)
      memory_store = ActiveSupport::Cache::MemoryStore.new
      memory_store.silence!
      memory_adapter = Flipper::Adapters::CacheStore.new(dalli_adapter, memory_store, expires_in: 1.minute)
      Flipper.new(memory_adapter, :instrumenter => ActiveSupport::Notifications)
    end
  end

end
```

Is there any other set up we need to ensure the `updated_at` field in our features table gets updated properly?

Thanks!

**Comment by AlexWheeler** [comment]
@pxr13 A new `flipper_features` record is created when you first add a feature.  After that it will never be updated. 

When you're enabling actors, percentage_of_actors/time, etc. the AR adapter is creating`flipper_gates` records associated to the flipper_features via their `feature_key` column

```
# creates a flipper_features record 
Flipper.add(:my_feature).
```

```
# creates a flipper_gates record w/ values
Flipper[:my_feature].enable_percentage_of_actors(10)

{
  value: 10,
  created_at: ...,
  updated_at: ...,
  feature_key: 'my_feature',
  key: "percentage_of_actors'
}
```

*We're looking to use the updated_at field to notify teams of old flippers that should be removed from our codebase.*

You'd want to find the most recently created gate record for the feature.  You can also have features without any gates so you'd probably want to take into account flipper_features created_at too

```
select max(flipper_gates.created_at) from flipper_gates inner join flipper_features on flipper_features.key = flipper_gates.feature_key where flipper_features.key = YOUR_FEATURE_KEY;
```

**Comment by pxr13** [comment]
@askwheeler Awesome suggestions and clarification. Thank you!
