### ISSUE TITLE
Feature names are being percent-encoded but are not good for the UI. 

### ISSUE THREAD

**Issue by Subomi** [jnunemaker/flipper#400]
I setup a feature in my code as this

`features = ['Feature One', 'Feature Two']`
`setup_features(features)`

But when this renders on the UI it comes as `Feature%20One`

Should the DB be changed to reflect a feature name or this should just be changed simply at the response time.

I will be glad to send in a fix for this.

**Comment by AlexWheeler** [comment]
Hey @Subomi.  This was fixed in https://github.com/jnunemaker/flipper/pull/377 and part of the 0.16.0 release.  What version of `flipper`, `flipper-ui` are you using? If its pre 0.16 then you should just need to update to 0.16

**Comment by AlexWheeler** [comment]
ahh yes @Subomi I totally understand

 That would be great if you could submit a fix!

**Comment by AlexWheeler** [comment]
Just adding a note here for clarity: #377 fixed that when a gate is enabled from the UI for a feature with a space, the gate's feature_key is unescaped

Subomi's issue is that if you view a feature in the Flipper::UI, the rendered value is url encoded
![screen shot 2019-01-31 at 10 40 03 am](https://user-images.githubusercontent.com/3260042/52076952-b5d2b680-2544-11e9-9d5f-3e82cac1723a.png)

**Comment by jnunemaker** [comment]
I believe this is fixed in master. 

![Screen Shot 2019-09-13 at 2 08 43 PM](https://user-images.githubusercontent.com/235/64884562-03adb200-d630-11e9-8d4d-0a200ee2ba1e.png)

Closing, but please re-open with steps to reproduce if you try master and it still isn't work.
