### ISSUE TITLE
Blocking redis gem upgrade

### ISSUE THREAD

**Issue by jondavidjohn** [jnunemaker/flipper#404]
```
Bundler could not find compatible versions for gem "redis":
  In Gemfile:
    redis (~> 4.1)

    flipper-redis (~> 0.16.0) was resolved to 0.16.1, which depends on
      redis (< 4.1.0, >= 2.2)
```

Looks like you may be inadvertently blocking new versions of the redis gem.

Is there some specific incompatibility to be dealt with?

**Comment by dvmonroe** [comment]
@jnunemaker any chance you have some time to release with the update from https://github.com/jnunemaker/flipper/pull/401

Appreciate the work.

**Comment by gerrywastaken** [comment]
Damn, we already use Redis 4.1.0. Having this restriction causes bundler to go all the way back to using flipper-redis 0.3 (which I'm guessing doesn't have this restriction on Redis versions). This then results in an unhelpful:

`undefined method `get' for #<Flipper::Adapters::Redis:0x00007facf5dcf538>
Did you mean?  gem`

That took a while to track down the actual cause.

**Comment by jnunemaker** [comment]
0.16.2 is in its way out! Should be on rubygems in a few minutes. Sorry folks! Thanks for the gentle bump.

**Comment by gerrywastaken** [comment]
@jnunemaker No worries at all. Thanks for making this change. Really appreciate your work! :)
