### ISSUE TITLE
Symbol procs as groups don't work as expected.

### ISSUE THREAD

**Issue by supersam654** [jnunemaker/flipper#405]
Consider these two groups:

```
Flipper.register(:working) do |actor|
  actor.admin?
end

Flipper.register(:broken, &:admin?)

class User
  def admin?
    true
  end
end

```

The first group works as expected. However, the second group raises an exception about passing the wrong number of arguments to `admin?` even though it appears to be syntactic sugar for the first one.

I did some digging and the problem appears to be at https://github.com/jnunemaker/flipper/blob/master/lib/flipper/types/group.rb#L17.

Notably, the arity of the symbol proc is `-1` while the arity of the regular block is `1`.

```
def print_arity(&block)
  puts block.arity
end

print_arity(&:to_s) # Prints -1
print_arity { |a| a.to_s } # Prints 1
```

With all of that said, I'm not very familiar with [arity](https://apidock.com/ruby/Proc/arity) checking in Ruby. However, it seems that checking the absolute value of the arity would work in this situation. If someone else thinks this is a good idea, I'd be more than happy to make the (tiny) PR for this.

**Comment by jnunemaker** [comment]
Definitely open to a PR with a spec/fix.

**Comment by thetimbanks** [comment]
Closing since this was resolved by https://github.com/jnunemaker/flipper/pull/406
