### ISSUE TITLE
Best Practices for Feature Dependencies

### ISSUE THREAD

**Issue by chipach** [jnunemaker/flipper#412]
Are there best practices for Flipper when one feature depends on another? As far as I can tell, there isn't anything built in to the code to help here, but the desire is to have certain features that can only be enabled if other features are enabled.  As a relatively easy example, let's say we're rolling out BigNewThing, so there is a gate for BigNewThing itself.  As BigNewThing gets into real production (beta) use and we write ImprovedBigNewThing, we want to gate ImprovedBigNewThing and ImprovedBigNewThing2, ImprovedBigNewThing3, ImprovedBigNewThing4) code until it is ready for users to see (in the vein of continuous delivery), but in order to turn on ImprovedBigNewThing*, BigNewThing has to be on.  Beyond this simple example, I can see things getting messy if there's no clean way of documenting/enforcing that gate A must be on for gate B to be on.  Are there best practices (or some code thing I'm missing!) to help here?

**Comment by jnunemaker** [comment]
Usually for application logic like this I recommend building application code. `BigNewThing.enabled?(...)` could check the big new thing and each subclass could have similar code that passes things on down to flipper and does more complicated enabled or not logic using one or more features. I'd be open to something in flipper that was simple and logical but I haven't come up with anything of yet. 

Does that help? So sorry for the late response on this.
