### ISSUE TITLE
flipper-ui: Remove misleading actor placeholder?

### ISSUE THREAD

**Issue by andyw8** [jnunemaker/flipper#416]
The actor field has a default of placeholder of "ie User:6". This is misleading because the format is implementation-dependent.

Even in the README, the actors in the screenshot are usernames, so it doesn't follow this format.

See also #151 where the placeholder caused confusion.

I think it would be better for the placeholder to be blank.

**Comment by jnunemaker** [comment]
I could see this being configurable for the UI. We have a config module now and you are right, this can be per project. I actually recommend `class;id` now as semicolons don't complicate modularized classes.

**Comment by jnunemaker** [comment]
Closed by the commit above.

```
Flipper::UI.configuration.add_actor_placeholder = ""
```
