### ISSUE TITLE
Flipper UI: Looking for a way to mount under ApplicationController

### ISSUE THREAD

**Issue by deecewan** [jnunemaker/flipper#419]
Hey,

I have a fair amount of auth + audit logic for actions inside of ApplicationController. Is there any way I can use my existing logic to verify access to Flipper?

I'm not even sure if this is possible, but I'd like to be able to mount Flipper *underneath* an ApplicationController. Essentially have the ApplicationController call out to Flipper to generate the HTML/run the underlying requests, and then return the relevant information to the ApplicationController.

I have tried to instantiate the flipper app inside of the controller (once I can verify the auth is correct, etc) and then use the `call` method on the Rack app like this:

```rb
class FeatureFlagController < ApplicationController
  # auth logic, etc
  def index
    Flipper::UI.app(Flipper).to_app.call(request.env)
  end
end
```

It tells me that `call` expects 0 arguments. If I try to pass 0 args, it tells me `call` expects 1 arg.

**Comment by jnunemaker** [comment]
What I do is mount flipper with a constraint. See the [flipper ui docs](https://github.com/jnunemaker/flipper/blob/b602168282d0c2efb7a50613b2e998d6b28a099e/docs/ui/README.md#route-constraints). 

The only trick is you need to be able to determine the user or whatever you need from the request env. Always do-able but sometimes you have to do some digging if you are using devise or something.

Let me know if that is or is not helpful.

**Comment by deecewan** [comment]
@jnunemaker i've seen the constraints - i got an initial version working with constraints, but i have a bunch of `before_action`s, etc, that are all in my `ApplicationController`. Also logging and auditing around requests coming in and who made those requests. It'd be swell to not have to duplicate the code/extract all that functionality just to make flipper work 😢

**Comment by jnunemaker** [comment]
@deecewan ah, I'm sorry. I guess I've always used middleware for logging/auditing, so that is why I haven't hit this issue. I'm pretty sure there has to be a way to do this. I don't have time to play with it right now, but I'd see what to_app is returning and look through its methods. Likely you are close.
