### ISSUE TITLE
Documentation for implementing in rails isn't centrally located

### ISSUE THREAD

**Issue by cdhagmann** [jnunemaker/flipper#421]
It is not clear what needs to be place in `config/initializers/flipper.rb`, etc. Can we have a doc that goes through this specifically?

**Comment by jnunemaker** [comment]
For active record, something like this would work:

```ruby
require "flipper/adapters/active_record"

Flipper.configure do |config|
  config.default do
    Flipper::Adapters::ActiveRecord.new
  end
end

require "flipper/middleware/memoizer"
Rails.configuration.middleware.use Flipper::Middleware::Memoizer, preload_all: true
```

Does that help?

**Comment by asadakbarml** [comment]
Is any of this necessary now with version 0.21.0 configuring by default?

**Comment by jnunemaker** [comment]
I don't think so. 0.21 does all this for you.
