### ISSUE TITLE
Enable feature for actor 100% of the time

### ISSUE THREAD

**Issue by mzaragoza** [jnunemaker/flipper#425]
I am trying to enable a feature 100% of the time for the Actors that it's assigned to.
At this times it changes every time I refresh

<img width="1920" alt="Screen Shot 2019-07-22 at 3 46 19 PM" src="https://user-images.githubusercontent.com/1479619/61664479-7174d780-ac98-11e9-98f4-24243defcfd8.png">
<img width="1920" alt="Screen Shot 2019-07-22 at 3 46 09 PM" src="https://user-images.githubusercontent.com/1479619/61664480-7174d780-ac98-11e9-9e21-b8e616278fa7.png">

**Comment by jnunemaker** [comment]
@mzaragoza can you be more descriptive? If you could provide the steps you are taking along with what happens and what you expect to happen that would help? I'm closing this out as insufficient steps to reproduce, but with more info I'd be happy to keep digging/helping.
