### ISSUE TITLE
Bulk add actors

### ISSUE THREAD

**Issue by alexabbott** [jnunemaker/flipper#428]
I have a list of 5000 actors to add, but the UI only allows to add one at a time. Is there any way to bulk add actors to a feature?

**Comment by jnunemaker** [comment]
See [Caveat 1](https://github.com/jnunemaker/flipper/blob/master/docs/Caveats.md). For that many actors, I'd think seriously about a group. Is there anything they share? Is there anything more you can share about the reason those 5k are in and not others? Often a group can do true/false for a common trait and that solves the problem more efficiently than adding 5k individually. 

That said, there is nothing bulk in flipper or flipper ui for adding actors. Using the UI would be quite painful, but a script to run or a snippet of code to run in a console would get the trick done. 

Let me know if none of that above was helpful. Definitely want to know more to see if there is something we can come up with.
