### ISSUE TITLE
Release new version for rails 6.0.0 ?

### ISSUE THREAD

**Issue by vinc** [jnunemaker/flipper#430]
Hello! Rails 6.0.0 has been released and I've been personally using the latest version of this gem with rc1 and rc2 in production without any issues. Could you release a new version with the changes made to `flipper-active_record.gemspec` 3 months ago so we can upgrade to rails 6.0.0? 🙏 🎉

**Comment by jonnyom** [comment]
Big +1, this is our only blocker for upgrading and we'd love to get it done!

**Comment by vpereira** [comment]
blocker for us too. Any issue with updating the gem to support 6.0.0 or it's just matter of bump it in the gemspec?

**Comment by jonnyom** [comment]
Bumping once again! It'd be really great if we could get this done to get ourselves upgraded.

**Comment by devinmcgloin** [comment]
In the same boat over here. This is the only blocker preventing us from upgrading. It's really unfortunate, as it's such a straightforward issue to resolve.

Just in case you've got notifications for the repo off, do you mind releasing the next version @jnunemaker ?

**Comment by vinc** [comment]
You can follow the PR here: https://github.com/jnunemaker/flipper/pull/429

And while we are waiting we can use the latest commit of `master` on this repo in production, that's what I've been doing since opening this issue.

**Comment by jnunemaker** [comment]
New version coming soon. Hopefully today.

**Comment by jnunemaker** [comment]
0.17 is out on rubygems.

**Comment by jnunemaker** [comment]
0.17.1 is out with a fix if you are using flipper-active_record. I yanked the 0.17.0 versions of all gems because #437  basically made that version unusable for rails.
