### ISSUE TITLE
RedisCache adapter should not break if redis is down

### ISSUE THREAD

**Issue by dgmora** [jnunemaker/flipper#443]
If redis is down,`RedisCache` would start throwing exceptions due to that. Since `RedisCache` wraps another adapter, I think a nice option would be to skip the cache and to instead use the wrapped adapter.

A plus would be to use instrumentation so that the error is not just "swallowed". A simple approach I have tried that works is:
```ruby
      class BestEffortRedisCache < RedisCache
        def get(feature)
          super
        rescue ::Redis::BaseError => e
         # + instrumentation
          @adapter.get(feature)
        end
      end
```

I can imagine that not everyone likes that behavior, but without this approach having redis down means that a great part of an app can be down. (Or at least I have not found a way to prevent that)

**Comment by jnunemaker** [comment]
>  I think a nice option would be to skip the cache and to instead use the wrapped adapter.

I like the way you think, but it could also cause a worse outage. Say redis is down so you fallback to mysql. What if a person's setup of mysql can't handle the load of all the new queries and that is why they used redis in the first place? 

The great thing about the adapter pattern is you can do whatever you want. I'll probably stick to supporting just the redis cache adapter as is, but you could definitely make a FallbackToOriginCache adapter that takes a cache and origin adapter and does what you've mentioned. I'd probably be willing to merge that in as well if others would find it useful.

```ruby
origin = Flipper::Adapters::ActiveRecord.new(...)
cache = Flipper::Adapters::RedisCache.new(origin)
fallback = FallbackAdapter.new(cache, origin)

class FallbackToOriginCacheAdapter
  def initialize(cache, origin)
    ...
  end

  def get(feature)
    @cache.get(feature)
  rescue
    @origin.get(feature)
  end
end
```

You could even fallback to wrapping the origin with an in memory adapter for a bit of caching or something too.

**Comment by dgmora** [comment]
> Say redis is down so you fallback to mysql. What if a person's setup of
mysql can't handle the load of all the new queries and that is why they
used redis in the first place?

I thought about that, it technically could happen. But if your db cannot
handle the load, you should just use the Redis adapter instead of the
RedisCache.

I get that it's a bit borderline though :)

**Comment by jnunemaker** [comment]
If your db can handle the load then why use a cache adapter? ;)

**Comment by halloffame** [comment]
I solved this problem using the failover adapter with the memory adapter as a fallback.

```ruby
require "flipper/adapters/redis"
require "flipper/adapters/memory"
require "flipper/adapters/failover"
require "flipper/adapters/read_only"

redis = Redis.new(url: Rails.configuration.redis_url)
redis_adapter = Flipper::Adapters::Redis.new(redis)
memory_adapter = Flipper::Adapters::Memory.new

# Import all flipper features from redis into memory_adapter.
# The memory adapter is only used as a fallback when redis is down.
# It will only pull from redis on start-up, so if you make changes
# to flipper-redis that you want reflected in the fallback, you should
# restart your app.
Flipper.new(memory_adapter).import(Flipper.new(redis_adapter))

Flipper.configure do |config|
  config.adapter do
    Flipper::Adapters::Failover.new(
      # Redis adapter is our default adapter
      redis_adapter,
      # In case redis is down, use memory adapter. This is a copy of what is in
      # redis (at time of boot-up). We wrap it in ReadOnly so that changes can't
      # be made while in fallback mode.
      Flipper::Adapters::ReadOnly.new(memory_adapter),
      # Rescue Redis errors. This defaults to [StandardError] if nothing provided.
      errors: [Redis::CannotConnectError, Redis::ConnectionError, Redis::TimeoutError]
    )
  end
end
```
