### ISSUE TITLE
ActiveRecord Adapter segfaults with New Relic

### ISSUE THREAD

**Issue by vovimayhem** [jnunemaker/flipper#445]
Hi! We started observing segfaults on one of our apps when we added the `flipper-active_record` gem. This happens during the phase where the New Relic agent generates the "Environment Report", on app startup.

I've created a project which consistently reproduces the segfault on my mac (I'm using docker 4 mac): https://github.com/IcaliaLabs/flipper-and-new-relic-rpm-segfault-demo

I've narrowed it down to the `flipper-active_record` gem, specially on how the adapter gets loaded - related to #432 , and 4233937af73a98da549671f5632def0b3d70e6c2.

**Comment by vovimayhem** [comment]
Although I haven't found the root cause, I have observed this:
- I found it hard to reproduce the segfaults with a minimal project / set of gems: Sometimes it presented the segfault, sometimes it didn't. I ended up loading the entire gem list from our project to the example project I shared with you. So I guess it's linked to the quantity of libraries loaded to memory.
- Replacing `flipper-active_record` with `flipper-redis` worked - that's how we fixed our app for now, but we'd prefer switching back to activerecord instead.
- Thinkering with `flipper-active_record`, I found:
  - [Requiring activerecord here](https://github.com/jnunemaker/flipper/blob/eb0ee0a39a6ae33b23ce3a49a6ba1718c17096da/lib/flipper/adapters/active_record.rb#L3) is not necessary - the code is currently being loaded by the [ActiveRecord hook](https://github.com/jnunemaker/flipper/blob/c414ee7e088b5594984e55d03f12d6a1b0e76543/lib/flipper-active_record.rb#L4). I initially thought removing this would fix the segfaults, but didn't.
  - What **_did work for me_** was [extracting the models](https://github.com/jnunemaker/flipper/blob/eb0ee0a39a6ae33b23ce3a49a6ba1718c17096da/lib/flipper/adapters/active_record.rb#L11-L26) to another file, and requiring this new file inside the [ActiveRecord hook](https://github.com/jnunemaker/flipper/blob/c414ee7e088b5594984e55d03f12d6a1b0e76543/lib/flipper-active_record.rb#L4), instead of the whole code. I moved the original require out of the hook, right after the `activesupport/lazy_load_hooks` requirement.

**Comment by jnunemaker** [comment]
I hate to just close issues, but I've not had any other reports and I'm currently using flipper with active record adapter and new relic without any problems. As I said on the PR, if you get to the root and get the tests passing in the PR please re-open.
