### ISSUE TITLE
Variable groups?

### ISSUE THREAD

**Issue by anhang** [jnunemaker/flipper#447]
Is there a way to specify a variable inside a group? For example, I'd like to enable all users that belong to a school. I'd like something like the following:

```ruby

Flipper.register(:student_of_school) do |actor, params|
  actor.respond_to?(:is_student_of?) && actor.is_student_of?(params[:school])
end
flipper = Flipper.new(adapter)

flipper[:stats].enable flipper.group(:student_of_school, {school: 1234}) 
```

**Comment by jnunemaker** [comment]
I usually make the school an actor.

```ruby
class School
  def flipper_id
    "School;#{id}"
  end
end

flipper = Flipper.new(adapter)
flipper[:stats].enable(School.new(...))
```

Actors don't have to be users. At GitHub we used repositories and orgs (which would be akin to school in your situation). Does that help?
