### ISSUE TITLE
Efficient way to reset MemoryAdapter

### ISSUE THREAD

**Issue by greyblake** [jnunemaker/flipper#449]
Hi, thank you for the nice library! 
I really like the design and often point to it as an example of one of the best things ever written in Ruby :)

However.
I'd like to use Memory Adapter for tests and searching for the most efficient way to reset features. 
Using legal public API, I can do the following in tests in `after(:each)` callback:

```ruby
Flipper.features.each { |f| Flipper.disable(f.name) }
```

But my benchmarks show that sometimes it take up to `0.6ms`.

I found a work around, just to reset `@source` instance variable directly: 

```ruby
Flipper.adapter.instance_variable_set('@source', {})
```

This has the same effect (at least for my use case) and takes `0.0ms`.

Question: 
* Is there more efficient legal way to disable all features than `Flipper.features.each { |f| Flipper.disable(f.name) }` ?
* If no, what you consider adding something like `reset` method? (may be only for memory adapter if it does not fit in common interface for all adapters)

Thanks in advance.

**Comment by jnunemaker** [comment]
I usually just reset the flipper instance for each test and let the old ones get garbage collected. 

Flipper.instance = Flipper.new(...)

In a before or setup method for the whole suite.

**Comment by greyblake** [comment]
Thanks! This should work as well!
