### ISSUE TITLE
Deleting features in a Redis Cluster raises Redis::Cluster::CrossSlotPipeliningError

### ISSUE THREAD

**Issue by phstc** [jnunemaker/flipper#450]
Hi

I switched Flipper to a Redis cluster and everything seems to be working well, except for deleting features.

When I try to delete a feature I get `Redis::Cluster::CrossSlotPipeliningError` 👇 

```
Redis::Cluster::CrossSlotPipeliningError: Cluster client couldn't send pipelining to single node. The commands include cross slot keys. ["flipper_features", "pablo_test"]
```

Apparently, the problem is with cluster + multi, used in here https://github.com/jnunemaker/flipper/blob/a3a318dd65fcdfbc60a43f3677c6e0d85bfc40e5/lib/flipper/adapters/redis.rb#L36-L42.

**Comment by jnunemaker** [comment]
That multi is probably not overly important. I added it only to reduce network calls for remove from two to one. The upside of removing it is cluster works. The downside is an extra network call per feature remove, which shouldn't be a huge deal outside of big imports/syncs. I would be open to a PR removing the multi.

**Comment by phstc** [comment]
Thank you @jnunemaker. That's a great explanation and I agree that it seems benefits pay off the downsides. 

I created a PR for removing `multi` #451.
