### ISSUE TITLE
rubygems version seems to be behind

### ISSUE THREAD

**Issue by navjeetc** [jnunemaker/flipper#452]
Just downloaded the gem (v 0.17.1) from rubygems.org and it does not seem to match master e.g. UI module is missing in rubygems.org although it is 0.17.1. Can we verify that the latest code in master has been released to rubygems.org ?

**Comment by jnunemaker** [comment]
The UI is in flipper-ui gem. Is that what you are referring to or do you mean something else?

**Comment by navjeetc** [comment]
Never mind. As you said I had to add **flipper-ui** to my Gemfile. All is good.
