### ISSUE TITLE
add pagination for actors list

### ISSUE THREAD

**Issue by gihnius** [jnunemaker/flipper#457]
Right now in flipper feature page, we show all actors in single page, this seems terrible if we have thousands of users enabled a feature.

**Comment by jnunemaker** [comment]
See the caveats markdown file in the docs. Flipper actors is designed for hundreds at most not thousands. On my phone or I would explain more. Happy to answer more questions and link up more design decisions later if you have any.

**Comment by smridge** [comment]
I agree with adding some sort of pagination. I recently ran into this where the UI was almost brought down with thousands of `actors`. I see where the docs being referred to were removed [here](https://github.com/jnunemaker/flipper/commit/68e4b62a1ca8b14c59fc20c895b8fa74820fdf2c). I was not able to find the comparable reference in the [new docs](https://www.flippercloud.io/docs/). With that, does the decision still stand that a `group` should be used? If so, perhaps this can be referenced in the new docs?

Additionally/separately, are these docs "searchable"? I found it a bit challenging to sift through.

**Comment by bkeepers** [comment]
@smridge It is still recommended to use groups if you have a lot of actors. There is a note about it in the docs on [actors](https://www.flippercloud.io/docs/features#enablement-actor).

> Additionally/separately, are these docs "searchable"? I found it a bit challenging to sift through.

Thanks for the feedback. We have some work in progress to add search to the docs. I'll prioritize finishing it up.

**Comment by jnunemaker** [comment]
It is currently located at the bottom of the [actor gate docs](https://www.flippercloud.io/docs/features#enablement-actor). It says:

> Note: enable_actor is not designed for hundreds or thousands of actors to be enabled. This is an explicit choice to make it easier to batch load data from the adapters instead of performing individual checks for actors over and over. If you need to enable something for more than 100 individual actors, use a [group](https://www.flippercloud.io/dashboard#enablement-group) or [% of actors](https://www.flippercloud.io/dashboard#enablement-percentage-of-actors).

Great suggestion about search. @bkeepers is working on search and should have it out soon.
