### ISSUE TITLE
UndefinedTable flipper_features on heroku test CI

### ISSUE THREAD

**Issue by IanVaughan** [jnunemaker/flipper#458]
When running the test CI on Heroku it fails with this error :

```
-----> Clearing db:test:purge db:create db:structure:dump rake tasks
-----> Detecting rake tasks
-----> Preparing test database
       Running: rake db:schema:load_if_ruby
...
      rake aborted!
       ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "flipper_features" does not exist
       LINE 8:  WHERE a.attrelid = '"flipper_features"'::regclass
...
```
Full output: https://gist.github.com/IanVaughan/c7f5bf6cea3be8615c3056fb06aa2a4d

But in my branch, I have the `schema.rb` changes committed: https://gist.github.com/IanVaughan/a93badf262bf78f5b68adda9ae635bd8

My `config/initializers/flipper.rb` file looks like:
```ruby
require 'flipper'
require 'flipper/adapters/active_record'

Flipper.configure do |config|
  config.default do
    adapter = Flipper::Adapters::ActiveRecord.new
    Flipper.new(adapter)
  end
end

Flipper.add(:some_flag) # <- If I remove this it works
```

Gem versions:
```
flipper (0.17.2)
flipper-active_record (0.17.2)
flipper-ui (0.17.2)
```

What I want to do is ensure the flags exist at runtime, without changing their settings in the DB if they already are present.

**Comment by IanVaughan** [comment]
I also get this on deployments, so I guess its due to the load order wrt to initialisers and the migration?

**Comment by jnunemaker** [comment]
Pretty sure this is just that you are trying to add a feature before the tables exist because the environment and this file get loaded when migrations are ran. I'd wait to do the add until the adapter is loaded as that should be safer. 

```ruby
require 'flipper'
require 'flipper/adapters/active_record'

Flipper.configure do |config|
  config.default do
    adapter = Flipper::Adapters::ActiveRecord.new
    flipper = Flipper.new(adapter)
    flipper.add(:some_flag)
    flipper
  end
end
```

The downside is that this will happen for each process and thread, but only once so not a huge deal. Why do the features need to exist? If the features don't exist, the return is false which is the same if they are added with no gate values. I might have suggestions if you can explain the intent. Let me know. 😄

**Comment by justinpchang** [comment]
```
begin
  if ActiveRecord::Base.connection.table_exists? :flipper_gates
    ...flipper stuff
  end
rescue ActiveRecord::NoDatabaseError => err
  Rails.logger.warn "No database found, skipping initialization: #{err}"
end

```

For future, you can also manually check for table existence such as in the above example. Catching the error is necessary for rake db:create and similar tasks when the rails app must be initialized but the DB has not been created yet.

My use case was that I have initializers that serialize the flipper gates and pass them to our frontend. So just needed to wrap it in the above conditions.
