### ISSUE TITLE
Check if feature is disabled

### ISSUE THREAD

**Issue by iamdriz** [jnunemaker/flipper#466]
Is it possible to check if a feature is disabled?

As I have some code in the initializer that sets the defaults at start-up but I don't want it to override anything that's been set in the adapter. Which is why I can't treat a false return for `enabled?` as disabled for this scenario.

~~~
# default disabled features
%i[feature1 feature2].each do |thing|
  Flipper.disable thing unless Flipper.enabled? thing
end

# default enabled features
%i[feature3 feature4].each do |thing|
  Flipper.enable thing unless Flipper.feature(thing).state == :off
end
~~~

The best way I could figure to do it (seen as there is no disabled method) was to check if the feature has a state of off before trying to enable it. That way if someone has actually set the feature to off... and the app is started up... it won't enable it again.

However I get the feeling that this is sort of doing the same thing... and would never enable the feature even if no one had disabled it at some point... is there a way to check if a feature exists but has also been actually disabled? Or is what I am doing the correct way to achieve this?

**Comment by iamdriz** [comment]
It seems I can handle this by checking if the feature exists with: `Flipper.exist? thing` and don't even need to check if it's got a state of `:off`.

**Comment by jnunemaker** [comment]
You are correct about the lack of a disabled method. Flipper is about enabling things and letting things through the gate, not disabling things.

The best way to check if a feature has previously been enabled or disabled is to check the set of known features, which is what `exists?` does. It is possible for someone to add a feature there and not enable or disable the feature, but that is not a typical use case. 

Currently, a state of :off means that nothing is is enabled in any fashion and is the best way to check that something is fully disabled. 

Mostly just confirming what you said so you know you were correct. That said, I'm curious what the use case is so I can better understand and maybe come up with something to help. Why are you trying to enable or disable some features by default? Knowing would help me maybe point you in a different direction or determine if something is missing in flipper.

**Comment by iamdriz** [comment]
Hi John, thanks for the reply.

So the use case is we have certain features we develop during our agile sprints and sometimes we get ahead of what our QA can test for a sprint show and tell or upcoming release, so we're using this gem to control which default features are on/off at the point of deployment to our different environments.

The reason for setting some features as turned off is so it's clear from our code which are actively off and which are actively on... and then if someone wants to toggle these on/off we don't want our defaults to override them (our apps start/stop frequently due to the subsequent deployments or restarts, etc.).

We have previously used a combination of the config gem and a custom configuration layer built on top of Rails.config.x for certain features... but this gem lets us get involved from Rails.console and make it feel like a lighter setting rather than a configuration.

Hopefully that all makes sense? Seems the `exists?` method does do the job I want which is great. We were using the rollout gem previously, but because rollout doesn't behave like a singleton it became a pain to have to re-hook up an instance to our redis db to toggle features from console.

**Comment by jnunemaker** [comment]
@iamdriz the features that you release like this, are they just on/off or do you take advantage of the % rollouts or individual actors/groups too?

**Comment by iamdriz** [comment]
Hi John.

The features are literally on/off at the moment. They work pretty much the same as if you'd put the feature in a YML file... with the exception that using Redis we can toggle these anytime.
