### ISSUE TITLE
Feature to hide the "Enable/Disable" section or retain gate records?

### ISSUE THREAD

**Issue by tenpaiyomi** [jnunemaker/flipper#472]
First off, thank you very much for the awesome gem, it's been very easy and straightforward to use.

I wanted to inquire about the option of either adding a configuration to hide the section for enabling/disabling a feature in its entirety with a single click, or the option to retain gate records when a feature is enabled/disabled.

The scenario where this comes up is that, with how we utilize certain feature flags, we may want to enable a feature for certain users at times, and then later enable the feature for all users.  However, later on down the line we may need to disable the feature for "all" users but still allow users which we have specifically selected to retain access.

The way we've been approaching this currently is to have a gate that corresponds to the entire instance (by a model we have which responds with a static id).  Whenever the gate is enabled for that model, everybody has access to it.  If that model's access is disabled, it falls back to checking specific user ids for if they have access, which works great.  However, with the way the logic is setup, if somebody were to inadvertently click the enable/disable button, due to it clearing the gate records, we would lose that list of users who may have had a feature manually enabled, hence the desire to be able to either hide the enable/disable button, or a flag to be able to retain records.

I could issue a PR for this, going one way or the other, but I noted in some other PRs that the logic was explicitly added in for clearing the records, so I didn't want to preemptively put in the work for something that may be undesirable overall.

Thoughts?

**Comment by jnunemaker** [comment]
@tenpaiyomi I'd be up for a PR as that would help me understand more of what you have in mind. As long as it defaults to what it is now, I think I'm ok with more configuration to tweak things when people need it.
