### ISSUE TITLE
Group is not enabling/disabling feature

### ISSUE THREAD

**Issue by Talha5** [jnunemaker/flipper#475]
I’ve a user model and trying to enable feature flag for only for specific users.

```
# Registered a group
# allowed? is a custom method in User(ActiveRecord) class
Flipper.register(:normal_users) do |actor|
  actor.is_a?(User) && actor.allowed?
end

# Enabled the feature for this group
feature = Flipper[:stats]
feature.enable_group :normal_users
```

But when check on users to see if it got enabled for users it doesn’t work:

```
feature.enabled?(current_user) => false
```
Also, when placing `binding.pry` inside `allowed?` method it never gets called. 

On the other hand actors work just fine.

And when deleting this group from UI it says:

"The group named "normal_users" has not been registered."

**Comment by jnunemaker** [comment]
Can you tell me more about your setup? Is the flipper ui mounted in the same app? Where are you defining the group in code? Any and all setup or flipper specific code you had in a gist or comment here would help me but I don’t have enough to go on at this point.

**Comment by Talha5** [comment]
Did simple setup of installing gem and then mounting UI via routes.rb

Just trying it out in rails console. I'll put up a sample application for you but its just all basic installation stuff.

When creating groups, are they being persisted in database? As when i try to re-register group within a same rails console session, it gives me `Flipper::DuplicateGroup: Group :admins has already been registered` which is fine but when i quit rails console and start it up again and re-register group with the same name, it creates the group again.
Also, sometimes groups created from rails console dont get displayed in flipper UI groups dropdown.

**Comment by Talha5** [comment]
@jnunemaker [here's](https://github.com/Talha5/flipper_test_app) a test repo, checkout the readme for info of the the issue and setup.

**Comment by jnunemaker** [comment]
Groups definitely work. I've never had this reported before and I use groups on a weekly basis without any problems. There has to be something unique about your setup. I'm not sure why you have the FlipperFeature model. That isn't necessary as it is in the AR adapter. The only thing you need is the migration. 

The Flipper.register call should be somewhere that runs on boot. Do you have a config/initializers/flipper.rb that defines the group? If that is undefined then enabled would return false. That is likely your problem. Can you try that if you haven't and let me know?

**Comment by earksiinni** [comment]
I ran into this problem. In my case, the issue was that I was calling `actor.is_a?(User)`, like OP. The problem is that `actor` is a `Flipper::Types::Actor`, so my check always returned `false`.

I fixed the issue by changing `actor.is_a?(User)` to `actor.thing.is_a?(User)`, which checks the wrapped object's type instead of the wrapper's type.

**Comment by jnunemaker** [comment]
Ah. Interesting. I usually check respond to instead of is a which is why I haven’t hit that issue. Thanks for sharing.
