### ISSUE TITLE
Configuration option to render descriptions on 'features' page?

### ISSUE THREAD

**Issue by jbarrieault** [jnunemaker/flipper#477]
Hello!

I am in the process of upgrading Flipper in a project in order to utilize the new description feature and noticed descriptions are only rendered on the 'feature' pages, but not the 'features' page as well. I found a [comment](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/ui/configuration.rb#L36) indicating descriptions should appear on both pages, but I also see they were specifically removed from the 'features' page in [another PR](https://github.com/jnunemaker/flipper/pull/470).

Although the UI is cleaner without descriptions on the features page, we would still like to render them there to make things easier for our admin users. Would you accept a pull request adding a configuration option for rendering descriptions on the features page? If not, we should at least update the outdated comment. 🙂

**Comment by jnunemaker** [comment]
Yes to PR. Let me know if I can answer any questions.
