### ISSUE TITLE
Enable all features by default

### ISSUE THREAD

**Issue by scottbarrow** [jnunemaker/flipper#482]
Hi
Is there a way to Enable a feature on its first request and allow it to be added to the adapter(redis) if it's not already defined?
Or is there a way to bypass flipper to enable all features in development environment?

Thanks

**Comment by AlexWheeler** [comment]
Hey @scottbarrow I can try to help you out here

**Is there a way to Enable a feature on its first request and allow it to be added to the adapter(redis) if it's not already defined?**
`Flipper[:some_feature].enable` will both add the `:some_feature` feature to redis and enable it if you're using the redis adapter

**Or is there a way to bypass flipper to enable all features in development environment?**
One idea is to do this in a seeds file if you use one to seed a development database, for example `db/seeds.rb` in rails.

```ruby
features = %i(sidebar navigation other_feature)
features.each { |feature| Flipper[feature].enable }
```

And if you seed different environments you could check the env - assuming you're using Rails

```

if Rails.env.development?
  features = %i(sidebar navigation other_feature)
  features.each { |feature| Flipper[feature].enable }
end
```

**Comment by scottbarrow** [comment]
Thanks @AlexWheeler 
I did create a clone of the redis adapter that enables the feature as it is requested which does just that, however I was wondering if there was an easier way without having to create a new adapter

Im not a fan of the seeds file idea as it would require a code change to add new flags, which to me defeats the purpose of using flipper and a redis instance to manage them

**Comment by jnunemaker** [comment]
@scottbarrow is the goal of this only for development and test? 

At github, we had a CI build that enabled all features by default to dig out incorrect use/tests. We made an EnabledByDefault adapter. It wrapped an adapter and delegated all methods but `get`. `get` would check if the feature was in the list of known features in the adapter. If it wasn't, it performed an Adapter#add and then an Adapter#enable for the boolean gate. Something like this.

```ruby
def get(feature)
  unless features.include?(feature.key)
    add(feature)
    gate = feature.gate(:boolean)
    enable(feature, gate, gate.wrap(Flipper::Types::Boolean.new(true)))
  end

  @adapter.get(feature)
end
```

Then you can just wrap your adapter in dev/test/wherever with enabled by default.

**Comment by jnunemaker** [comment]
FlipperCloud.io actually solves this a different way. It supports multiple environments. Each environment inherits from production unless overridden. We also create a personal environment per developer that they can use on their computer. Because it inherits from production, your personal environment works just like production unless you change that. Also, because it is personal, you can change anything you want and not affect other teammates (which would happen if you all shared a development environment). 

I wrote more about it here if you are curious: https://johnnunemaker.com/flipper-cloud-environments/

**Comment by scottbarrow** [comment]
@jnunemaker thanks flipper cloud looks interesting when or how am I able to try it?

**Comment by jnunemaker** [comment]
Yep! Email me: john@fewerandfaster.com.
