### ISSUE TITLE
authorization of specific actions

### ISSUE THREAD

**Issue by tjbarker** [jnunemaker/flipper#497]
We have a large number of features that are changing a lot over many environments and we have a large group of people that are interested in knowing which features are live where. We are also keen to not have "edit" access open to all users.

At the moment we can lock down the flipper UI at a top level, but we'd be interested in a locking down specific actions. Resulting in some users only being able to see which features are live while some users can update, etc.

I would imagine we could implement something where a class is passed in during config and it's called before every action, passing in the request (from which current_user or ip, etc could be gathered) and the action that's taking place.

The class would then return true/false on whether the action should take place.

EDIT: I'm happy to make the changes and open a pr but just wanted to check in with the community before starting

**Comment by jnunemaker** [comment]
Solved with middleware: https://github.com/jnunemaker/flipper/pull/498#issuecomment-790771766
