### ISSUE TITLE
Would like support for custom/dynamic groups

### ISSUE THREAD

**Issue by aroben** [jnunemaker/flipper#50]
It would be nice to have a way to define a custom group type that corresponds to, e.g., a GitHub team. Something like this:

```ruby
class GitHubTeam
  def flipper_id
    "GitHubTeam:#{id}"
  end

  def self.find_by_flipper_id(flipper_id)
    find flipper_id.split(":")[1]
  end
end

Flipper.register_custom_group(:github_team) do |group_id, actor|
  GitHubTeam.find_by_flipper_id(group_id).include? actor
end

$flipper[:my_feature].enable $flipper.custom_group(:github_team, GitHubTeam.find("rails/owners"))
$flipper[:my_feature].enabled? some_user #=> true because some_user is a member of @rails/owners
```

Basically the only difference from normal groups is that the group's ID is passed to the block as well as the actor, so we can look up the group (team) at runtime.

/cc @jnunemaker @rsanheim

**Comment by aroben** [comment]
The adapter would need to store both the group name (`:github_team`) and the group object's `flipper_id`. We'd either need to combine these into a single string somehow, or adapters will have to be changed to be able to store multiple values for a single set member.

**Comment by aroben** [comment]
Combining into a single string seems pretty simple. We'd just have to pick a separator character (perhaps  ASCII's `\x1E` record separator) and then disallow that character from appearing in the group name. I'll take a crack at this.

**Comment by jnunemaker** [comment]
I don't have time to look at this right unfortunately but it doesn't feel like the right abstraction. I'd be more inclined to have a name to group mapping and just iterate them and create normal groups. 


{
rails_owners: "rails/owners",
}.each do |flipper_group, group|
  Flipper.register...
end

Or I would just define a flipper group that was enabled for a bunch of teams. 

Does any of that make sense? Custom group as you have above doesn't feel different enough from group and my fear is it will confuse people down the road as to which should be used.

**Comment by aroben** [comment]
The approach I took in #51 is just to support passing an extra parameter to group blocks. Another possibility I was considering is having a way to register custom logic to handle groups that haven't been registered:

```ruby
Flipper.group_fallback_handler = do |group_name, thing|
  Team.find_by_name(group_name).include? thing
end
$flipper[:my_feature].enable_group "rails/owners"
$flipper[:my_feature].enabled? some_user
```

Since `rails/owners` hasn't been registered as a group using `Flipper.register`, the fallback handler block will be called, passing "rails/owners" as the `group_name`.

**Comment by aroben** [comment]
See https://github.com/jnunemaker/flipper/pull/51#issuecomment-96817963 for some good discussion about why this might not be a great idea.
