### ISSUE TITLE
Hooks / callbacks after flipping a feature?

### ISSUE THREAD

**Issue by andyw8** [jnunemaker/flipper#513]
Hi,

I'm looking for a way to trigger some behaviour when a feature if flipped (in this specific case to clear a cache). I couldn't find any built-in way after searching for terms such as `hooks' and 'callbacks'.

I discovered https://github.com/mode/flipper-echo but thought there might be something built-in, or a more obvious way that I'm missing? 

Thanks

**Comment by jnunemaker** [comment]
Hi there,

You could definitely do this with ActiveSupport::Instrumentation. Check out this example:

https://github.com/jnunemaker/flipper/blob/a91863d6c5b7c79ac80868b3e5359a93b1c9d481/examples/instrumentation.rb

Another option would be to use a [cache adapter](https://github.com/jnunemaker/flipper/blob/a91863d6c5b7c79ac80868b3e5359a93b1c9d481/docs/Optimization.md#cache-adapters) that already exists or to create a new cache adapter ([building your own adapter](https://github.com/jnunemaker/flipper/blob/a91863d6c5b7c79ac80868b3e5359a93b1c9d481/docs/Adapters.md#roll-your-own) or check out existing cache adapter) just for your app.                                                                                                                                                                                                                                                     

Let me know if you need any help with any of these.

**Comment by jnunemaker** [comment]
Closing to keep things clean but feel free to keep asking any questions.

**Comment by jnunemaker** [comment]
Oh, and any more details you can provide would help me help you. I love to hear specific use cases. If you can't share it publicly, you can email john@fewerandfaster.com and I'll help ya there.

**Comment by andyw8** [comment]
Thanks for the quick reply, I'll look into those options.

The use case is for  a site where we're using [action caching](https://github.com/rails/actionpack-action_caching) and want to have a flag to make content within a page available or unavailable.

**Comment by jnunemaker** [comment]
Gotcha. Yeah you could definitely do either. Up to you. I like the adapter option but events would work. Check out the adapter I linked to for ideas and let me know if you have questions.

**Comment by andyw8** [comment]
Here's what I ended up with, in case it's useful to others:

```ruby
class FlipperSubscriber
  def call(*args)
    event = ActiveSupport::Notifications::Event.new(*args)

    # Two events are sent when a feature is flipped, we only care about one
    return unless event.name == "feature_operation.flipper"
    return unless event.payload[:operation].in?([:enable, :disable])

    feature_name = event.payload[:feature_name]
    return unless feature_name == "my_feature"

    Rails.logger.info("Clearing cache due to flag '#{feature_name}' being toggled")
    Rails.cache.clear
    Rails.logger.info("Reindexing content due to flag '#{feature_name}' being toggled")

    MyWorker.perform_later
  end

  ActiveSupport::Notifications.subscribe(/flipper/, new)
end
```

**Comment by jnunemaker** [comment]
@andyw8 hey thanks for sharing! Appreciated. 

One tip: I'd recommend including `remove` and `clear` in the operations. Both of those will delete gates, which is the equivalent of disabling a feature. 

These are used in the flipper ui ([delete feature](https://github.com/jnunemaker/flipper/blob/3d901538380f2a28329dd16345cee7f378978bb4/lib/flipper/ui/actions/feature.rb#L38-L38)), api ([remove](https://github.com/jnunemaker/flipper/blob/3d901538380f2a28329dd16345cee7f378978bb4/lib/flipper/api/v1/actions/feature.rb#L20-L20) and [clear](https://github.com/jnunemaker/flipper/blob/3d901538380f2a28329dd16345cee7f378978bb4/lib/flipper/api/v1/actions/clear_feature.rb#L15-L15)) and sync adapter ([source](https://github.com/jnunemaker/flipper/blob/3d901538380f2a28329dd16345cee7f378978bb4/lib/flipper/adapters/sync/synchronizer.rb#L52-L52)) to name a few.

https://github.com/jnunemaker/flipper/blob/3d901538380f2a28329dd16345cee7f378978bb4/lib/flipper/feature.rb#L85-L98

**Comment by mbajur** [comment]
Hello!

I have a use case in which i need to bind my app audit-logs mechanism into Flipper UI. So we can know who enabled what. Does the examples above supports that? I think not because there is no access to env/sessions to obtain current user ID but i might be wrong :)

**Comment by jnunemaker** [comment]
@mbajur correct, flipper doesn't have any knowledge the user/session/reqeust/env. You'll have to keep track of that somewhere and then use that when you subscribe to the notifications that flipper instruments. 

For example at GitHub, we had `GitHub.context` that was essentially a big global that was reset on each request (in a middleware). The actor that modified the feature was stored in that object and the instrumentation used that.
