### ISSUE TITLE
Memoizer warning

### ISSUE THREAD

**Issue by morgoth** [jnunemaker/flipper#526]
After upgrading to flipper 0.21.0, I'm getting a warning in the logs when visiting flipper UI.
`Flipper::Middleware::Memoizer appears to be running twice. Read how to resolve this at https://github.com/jnunemaker/flipper/pull/523`
On the regular app requests, it looks fine (there is no warning).

I don't have any custom configuration of this middleware.

**Comment by jnunemaker** [comment]
Ah! Good catch. Thanks for reporting. 

@bkeepers we can remove the memoizer middleware from the UI and API apps. But if we do we lose the block functionality. 

@bkeepers Trying to decide if I should just add functionality to pass block or instance to UI and API or just remove block/instance and warn... any preferences?

**Comment by bkeepers** [comment]
Doh, sorry, I didn't even think about this side effect.

> @bkeepers Trying to decide if I should just add functionality to pass block or instance to UI and API or just remove block/instance and warn... any preferences?

What are the use cases where people would use it, instead of just relying on the default instance? Either way, it seems very rare, so I would be in favor of removing block/instance, or at least moving it to a named argument instead of the first argument.

**Comment by jnunemaker** [comment]
> Doh, sorry, I didn't even think about this side effect.

Me either. 

> What are the use cases where people would use it, instead of just relying on the default instance?

I guess people who haven't switched to the default instance. I actually have no concept of how many have switched verse how many are still using the old way of just creating a new dsl instance. 

So so so wish I could get automatic analytics on stuff like this in a non creepy way. 

> Either way, it seems very rare, so I would be in favor of removing block/instance, or at least moving it to a named argument instead of the first argument.

K.

**Comment by jnunemaker** [comment]
This is fixed in the unreleased version of flipper. I'll probably cut a release soon.
