### ISSUE TITLE
Autoloading constant deprecation warning with Rails application after updating to 0.21.0

### ISSUE THREAD

**Issue by clinejj** [jnunemaker/flipper#532]
After updating to 0.21.0 our application started receiving deprecation warnings related to the autoloading of constants in our test environment.

```sh
> DISABLE_SPRING=true bin/rails test
DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, <several other helpers>.
       
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

   Rails.application.reloader.to_prepare do
     # Autoload classes and modules needed at boot time here.
   end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
(called from <main> at /app/config/environment.rb:5)
```

This warning does not show when using Flipper 0.20.4 or in development/staging/production environments as far as I can tell. We are using flipper, flipper-active_record, and flipper-ui on Rails 6.1.3.2. This issue is repeatable when using just the flipper gem without active_record/ui.

There's a similar thread when trying to autoload action_controller_base (see https://github.com/rails/rails/issues/36546) but that doesn't look totally applicable here.

**Comment by jnunemaker** [comment]
@bkeepers any idea what would have changed in 0.21 that would cause this?

**Comment by bkeepers** [comment]
@clinejj first, so sorry for the delay in responding. We added some Rails integration in 0.21 (in [railtie.rb](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/railtie.rb) and [cloud/engine.rb](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/cloud/engine.rb)), but I'm not seeing anything that would cause autoloading of application constants.

Could you share relevant parts of your Gemfile and any initializers that reference Flipper?

**Comment by clinejj** [comment]
No problem, and thanks for the recommendation! After some trial and error with removing different gems, the appears to occur whenever [prawn-rails](https://github.com/cortiz/prawn-rails) is included with the gemfile. The issue doesn't occur with Flipper 0.20.4, but does with 0.21.

Gemfile:
```rb
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

gem 'aasm'
gem 'bcrypt', '~> 3.1'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'draper'
gem 'flipper'
gem 'flipper-active_record'
gem 'flipper-ui'
gem 'jbuilder', '~> 2.11'
gem 'pg', '~> 1.2'
gem 'prawn-rails', '~> 1.4'
gem 'puma', '~> 5.3'
gem 'rails', '~> 6.1.3'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.4'

group :development, :test do
  gem 'byebug', platforms: %i[mri]
  gem 'dotenv-rails'
  gem 'pry-byebug'
end

group :development do
  gem 'annotate', '~> 3.1'
  gem 'listen', '~> 3.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'minitest-reporters', '~> 1.4'
  gem 'minitest-spec-rails'
  gem 'mocha'
  gem 'selenium-webdriver', '~> 4.0.0.beta4'
end
```

config/initializers/flipper.rb (note - I still see the issue after removing this code)
```rb
Rails.configuration.after_initialize do
  # Add groups for each feature that is currently active - this allows us to update groups through active admin
  if ActiveRecord::Base.connection.table_exists?('features')
    Feature.all.active.each do |feature|
      Flipper.register(feature.name.parameterize.underscore.to_sym) do |actor|
        actor.respond_to?(:active_features) && actor.active_features.where(name: feature.name).exists?
      end
    end
  end

  Flipper.register(:sandbox) do |actor|
    actor.respond_to?(:sandbox?) && actor.cooperative?
  end
end
```

**Comment by bkeepers** [comment]
@clinejj is this still happening for you? I'm not seeing anything in Flipper that would cause this. Does it still happen if you update `prawn-rails` to the latest version?

**Comment by clinejj** [comment]
@bkeepers Yes, we are still seeing this issue. `prawn-rails 1.4.2` is the latest version, which the gemfile above is linked to. I can create a duplicate issue in that repo, my guess is that and flipper don't play nicely together but we did only start seeing the issue after updating flipper to 0.21.

I can try to create a clean rails app repo and see if it's still happening there?

**Comment by bkeepers** [comment]
@clinejj if you could reproduce the issue in a new Rails app, that would be so helpful!

**Comment by clinejj** [comment]
Ok after playing with this a bit more I realized it's an issue with [minitest-spec-rails](https://github.com/metaskills/minitest-spec-rails), which would explain why I only saw it in the test environment. Will close the issue, thanks for being responsive!
