### ISSUE TITLE
Incorrect syntax near the keyword 'key' due to SqlServer reserved word use in get_all query

### ISSUE THREAD

**Issue by gradybarrett** [jnunemaker/flipper#535]
https://github.com/jnunemaker/flipper/blob/d52f7bb88feca6f0463ed655c31c8b482dadad14/lib/flipper/adapters/active_record.rb#L103-L109

The above usage of `key` and `value` appears to be causing a SQL query syntax error in 0.21.0 - specifically 0.21.0.rc2. This query appears to have been there for quite some time, but something in 0.21.0.rc2 caused the break. `key` and `value` are both reserved words in SQL Server. `value` is also a reserved word in MySQL, so curious if it's an issue there as well.

We're using the active record adapter with an MS SqlServer database in a Rails 5.0 app. We use the activerecord-sqlserver-adapter gem.

We do have a module that adjusts our model `table_name`s depending on db technology, which we include in the Feature and Gate Flipper AR classes. It doesn't muck with Flipper, only models' `table_name` attributes. That's the extent of our customization. The rest of the Flipper config/setup is very basic.

```ruby
class Flipper::Adapters::ActiveRecord::Feature
  include WbCommon::AdminData
end

class Flipper::Adapters::ActiveRecord::Gate
  include WbCommon::AdminData
end
```

**Comment by jnunemaker** [comment]
I was on vacation. Thus the delay. Wouldn't normally take this long. 

Thanks for the good write up. Sorry this is causing trouble for you. What is the fix? Do I need to properly escape the use of key and value with backticks or something?

**Comment by gradybarrett** [comment]
No biggie! I just opened up a draft PR to convert the query to Arel. Let me know what you think.

I'm not as familiar w/ Sequel, but I think the same thing could be done using that framework's DSL in the Sequel adapter.

**Comment by gradybarrett** [comment]
PR now includes a Sequel alternative as well.

**Comment by andyundso** [comment]
Hi @jnunemaker 

Just wanted to ask if you plan on releasing a new Gem version including the work done in this issue? We recently added flipper to a project where we have talk to MSSQL and the current version 0.21.0 doesn't work, so we're tracking your master branch at the moment.

**Comment by jnunemaker** [comment]
0.22 is releasing right now. 😄 

I usually just lock to the last ref in master if I'm using unreleased code from other projects. And then just update whenever they do release.

**Comment by andyundso** [comment]
That's what we sometimes do as well, but in this case we also test and release on Windows and the caches on Azure pipelines fail because the file names are too long. We deactivated cache to work around it, which causes longer build time etc. etc.

but thanks for the release and this great project :)
