### ISSUE TITLE
Redis - Use hexists instead of hgetall for checking if the feature is enabled for an actor

### ISSUE THREAD

**Issue by mayankkumarji** [jnunemaker/flipper#537]
This is an issue with RedisAdapter. When checking if a feature is enabled for an actor, the `redis.hgetall` method is called internally, which loads a list of all the actors that have the feature turned on. This is too slow if the number of actors is high (I observed this for 4000 actors). Instead, if `redis.hexists` is used, it leads to a huge performance improvement.

**Comment by jnunemaker** [comment]
How would hexists return the set of enabled actors? Returning the set is a requirement for flipper adapters. 

Also, did you see caveat 1? https://github.com/jnunemaker/flipper/blob/master/docs/Caveats.md

The actor set if for a small number of actors. When you need a large number we recommend using a group. 

Let me know if you have questions on using a group as I can help.
