### ISSUE TITLE
FlipperUI with strict Content Security Policy

### ISSUE THREAD

**Issue by mpraglowski** [jnunemaker/flipper#538]
Hi, 
I'm trying to add Flipper gem to [Pupilfirst](https://github.com/pupilfirst/pupilfirst) codebase and I have issues with the defined CSP (see: [CSP initializer](https://github.com/pupilfirst/pupilfirst/blob/master/config/initializers/content_security_policy.rb)). Below the logs from Chrome console:

```
Refused to load the stylesheet 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' fonts.googleapis.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

Refused to load the script 'https://code.jquery.com/jquery-3.2.1.slim.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' https: http: 'nonce-mKTcJubXV9s4Sko4N0BKoQ=='". 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' https: http: 'nonce-mKTcJubXV9s4Sko4N0BKoQ=='". 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' https: http: 'nonce-mKTcJubXV9s4Sko4N0BKoQ=='". 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'http://localhost:3000/toggle/js/application.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' https: http: 'nonce-mKTcJubXV9s4Sko4N0BKoQ=='". 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

It is fairly easy to add styles to defined CSP but `script-src` tag prevents loading all scripts used by Flipper UI.

**Comment by jnunemaker** [comment]
@mpraglowski sorry you are having trouble. I'm not well versed in CSP. What is the fix? I'm happy to accept a pull request or create one myself. But I'm not sure what the correct change is to make this work for you.

**Comment by mpraglowski** [comment]
There are several CSP violations here, most of them are easy to solve - we just need to add JS scripts & CSS styles urls to our CSP definition. However the problem is with `http://localhost:3000/toggle/js/application.js` as our policy does not allow to load any script without defined nonce generated on server https://edgeguides.rubyonrails.org/security.html#content-security-policy

I've solved this by adding [OverrideCsp class](https://github.com/pupilfirst/pupilfirst/blob/master/lib/override_csp.rb) and [mount FlipperUI with allow everything policy](https://github.com/pupilfirst/pupilfirst/blob/master/config/routes.rb#L32).

Other solution might be allowing to pass nonce to FlipperUI and use it in `script` tag definition.
