### ISSUE TITLE
Listing of features cause n+1

### ISSUE THREAD

**Issue by IlyaDonskikh** [jnunemaker/flipper#540]
Following code, specifically `enabled?` method, cause n+1 issue:

```ruby
flags = Flipper.preload(feature_keys)
flags.map do |feature|
  { key: feature.name, enabled: feature.enabled?(feature_user) }
end
```

```SQL
ActiveRecord -- Flipper::Adapters::ActiveRecord::Gate Load -- { :sql => "SELECT `flipper_gates`.* FROM `flipper_gates` WHERE `flipper_gates`.`feature_key` IN ('test_feature', 'user_test_feature') /*application:Test,controller:feature_flags,action:index*/", :cached => nil }
ActiveRecord -- Session Load -- { :sql => "SELECT  `sessions`.* FROM `sessions` WHERE (sessions.expires_at > '2021-06-23 15:48:39.923996') AND `sessions`.`access_token` = 'b0acf7e9120f6f74f51c0b894f0d79fc' LIMIT 1 /*application:Test,controller:feature_flags,action:index*/", :cached => nil }
ActiveRecord -- Spree::User Load -- { :sql => "SELECT  `spree_users`.* FROM `spree_users` WHERE `spree_users`.`id` = 1 LIMIT 1 /*application:Test,controller:feature_flags,action:index*/", :cached => nil }
ActiveRecord -- Flipper::Adapters::ActiveRecord::Gate Load -- { :sql => "SELECT `flipper_gates`.* FROM `flipper_gates` WHERE `flipper_gates`.`feature_key` = 'test_feature' /*application:Test,controller:feature_flags,action:index*/", :cached => nil }
ActiveRecord -- Flipper::Adapters::ActiveRecord::Gate Load -- { :sql => "SELECT `flipper_gates`.* FROM `flipper_gates` WHERE `flipper_gates`.`feature_key` = 'user_test_feature' /*application:Test,controller:feature_flags,action:index*/", :cached => nil }
```

Do i have any way to avoid the problem?

---
v0.17.2

**Comment by jnunemaker** [comment]
Preload just queries all the features. You'll need memoization on using the [middleware](https://github.com/jnunemaker/flipper/blob/d52f7bb88feca6f0463ed655c31c8b482dadad14/docs/Optimization.md#memoization) (recommended) or by [manually](https://github.com/jnunemaker/flipper/blob/d52f7bb88feca6f0463ed655c31c8b482dadad14/examples/memoizing.rb) turning it on.

**Comment by jnunemaker** [comment]
I'd also recommend updating to 0.21. It does that all for you by default. Usually its just update the gem and remove any manual Flipper.configure setup. If you drop in your flipper initialization I can confirm the upgrade for you.

**Comment by IlyaDonskikh** [comment]
Thanks for the quick reply!

Unfortunately i stack in current project with `activerecord 4.2` and can't update the gemset up to 0.21.

**Comment by jnunemaker** [comment]
Ah. Interesting. I doubt we have any conflicts with 4.2. I wonder if I
can just relax the gem constraint…

On June 23, 2021, David Grevink ***@***.***> wrote:
> Thanks for the quick reply!
>
> Unfortunately i stack in current project with activerecord 4.2 and
> can't update the gemset up to 0.21.
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/540#issuecomment-
867146465>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB2ZBDFHCCASUZU6FX3DTUJB3BANCNFSM47GDLUJA>.

**Comment by IlyaDonskikh** [comment]
Thank you! 

On another note. Currently my flipper config is:
```
Flipper.configure do |config|
  config.default do
    adapter = Flipper::Adapters::ActiveRecord.new

    Flipper.new(adapter)
  end
end
```

And as well i added `Memoizer` middleware to `application.rb`:

```
config.middleware.use Flipper::Middleware::Memoizer
```

But i am still getting a query per `enabled?` method call:
```
2021-06-23 21:00:24.609130 D [1:47306054763960] (3.434ms) ActiveRecord -- Flipper::Adapters::ActiveRecord::Gate Load -- { :sql => "SELECT `flipper_gates`.* FROM `flipper_gates` WHERE `flipper_gates`.`feature_key` = 'test_feature' /*application:Instamart,controller:feature_flags,action:index*/", :cached => nil }
2021-06-23 21:00:24.611040 D [1:47306054763960] (0.559ms) ActiveRecord -- Flipper::Adapters::ActiveRecord::Gate Load -- { :sql => "SELECT `flipper_gates`.* FROM `flipper_gates` WHERE `flipper_gates`.`feature_key` = 'user_test_feature' /*application:Instamart,controller:feature_flags,action:index*/", :cached => nil }
```

**Comment by jnunemaker** [comment]
Relaxed the constraint: d006c65a25006ded20e4fc8e08a8528432237874

Your mileage may vary. Hopefully it all works for you. Let me know if you hit issues. You can lock to ref in bundler or wait for a bit until I release a new version.
