### ISSUE TITLE
ActiveRecord adapter not idempotent^W concurrency-safe with MySQL?

### ISSUE THREAD

**Issue by geeksam** [jnunemaker/flipper#544]
(Issue title is a nod to #420.)

I just updated Flipper to v0.21.0 and switched our Flipper adapter from Redis to AR (backed by MySQL), and everything went quite smoothly... until a day or two later, when our Resque workers wouldn't come up after a deploy.  Sentry showed an `ActiveRecord::RecordNotUnique` exception originating from a line in `config/initializers/flipper.rb` that explicitly enabled a specific feature.

(Yes, I know.  A patient tells their doctor "Doctor, my arm hurts when I do this!"  The doctor responds, "well, don't do that!"  That line of code probably shouldn't have been there; nevertheless, it was.)

This was not quite as easy to reproduce in a test as I was expecting it to be, but I'll spare you the play-by-play.  TL;DR:  even though the AR adapter is wrapping its access in a transaction, calling `Flipper::Adapters::ActiveRecord#enable` still manages to violate the unique index on `flipper_gates` when called concurrently.

I've got a branch that demonstrates this over at https://github.com/RealGeeks/flipper/tree/ar-adapter-concurrency-error, but:
- it adds a dependency on `mysql2`
- it fails weirdly under SQLite
- just rescuing the exception feels kinda hacky to me?  (I'd be much more satisfied with this if I knew why the transaction wasn't working for this.)

**Comment by jnunemaker** [comment]
Thanks for all the good details and examples. I was on vacation. But I'm back now and added fixes for AR and Sequel in 87f5a98bce7baad7a27b75b5bce3256967769f27. Does that look like it will solve your problem?

**Comment by geeksam** [comment]
Thanks!  That looks like it should do the trick.

(Or would, had I not already removed the code that caused me to encounter the problem.  But hey, now nobody else will bang their heads on it in future.)
