### ISSUE TITLE
How to Setup Two Adapters

### ISSUE THREAD

**Issue by asadakbarml** [jnunemaker/flipper#548]
Hi, I wanted to use flipper-active_record for storage, but flipper-redis for caching. Is there a way to do this in Rails? The documentation is a bit confusing because I'm not sure when is done for you, especially with version 0.21, and what must be done on our own to enable storage, preloading, memoization and caching.

I've had several questions that I haven't been able to find the answers to in the docs or issues. 
1. When do I use `config.default` versus `config.adapter`?
2. Do I need to state config.adapter twice if I have two adapters I am using?
3. How do I independently specify an adapter for storage and an adapter for caching?
4. When do I need to manually include Memoizer in the middleware versus when is it already included? Some docs say to manually include while the docs around 0.21 say it is done automatically?

Edit: Adding another question
5. Is this middleware (https://github.com/jnunemaker/flipper/blob/master/docs/Optimization.md#advanced) automatically added in rails in the latest version of the gem or does it need to happen manually to implement memoization?

Thanks!

**Comment by jnunemaker** [comment]
1. use `config.default` if you want to customize the DSL instance (say with instrumentation). Use `config.adapter` if you want to customize only the adapter (say with caching).
2. Nope. Once is enough. Just use initialize the cache adapter with the underlying storage adapter. 
3. There is no distinction currently. All cache adapters initialize with some other adapter that they are to wrap caching around. @bkeepers is hoping to add an explicit `config.cache` or something like that for allowing this automatically (eventually). 
4. 0.21 does it automatically for Rails apps. You only need to if you aren't using Rails or are on an older version.
5. It is automatic for rails. You can forget about it. :) 

See the [redis cache docs](https://github.com/jnunemaker/flipper/blob/master/docs/Optimization.md#rediscache) for a good example and/or below.

```ruby
require 'flipper/adapters/redis_cache'

Flipper.configure do |config|
  config.adapter do
    redis = Redis.new(url: ENV['REDIS_URL']) # or whatever
    ttl = 4800
    Flipper::Adapters::RedisCache.new(Flipper::Adapters::ActiveRecord.new, redis, ttl)
  end
end
```

Let me know if that doesn't clear things up for you or if I can help with anything else. ✨
