### ISSUE TITLE
Problems with version 0.22.0 - Rack::Timeout::RequestTimeoutException + ThreadError

### ISSUE THREAD

**Issue by wenderjean** [jnunemaker/flipper#549]
Hey guys,

Recently we changed our Flipper version from `0.13.0` to `0.22.0` and we started to see a lot of `Rack::Timeout::RequestTimeoutException` and `ThreadError` in our application. I'm not sure yet but those problems seem to be related to an increase in the number of times we hit the cache to write/read data.

We noticed during a debug session that when I request a FF for the first time Flipper writes all of them in our cache including the keys `flipper/v1/features` and `flipper/v1/get_all` then when I try to request another FF (present in our cache), the debug logs prints like:

```
$ DEBUG -- : Cache write: flipper/v1/get_all ({:expires_in=>5 minutes, :unless_exist=>true})
$ DEBUG -- : Cache read: flipper/v1/features ({:expires_in=>5 minutes})
$ DEBUG -- : Cache fetch_hit: flipper/v1/features ({:expires_in=>5 minutes})
$ DEBUG -- : Cache read_multi: [ ALL MY FF's HERE ]
$ DEBUG -- : Cache read: flipper/v1/features ({:expires_in=>5 minutes})
$ DEBUG -- : Cache fetch_hit: flipper/v1/features ({:expires_in=>5 minutes})
$ DEBUG -- : Cache read: flipper/v1/feature/<my FF here> ({:expires_in=>5 minutes})
$ DEBUG -- : Cache fetch_hit: flipper/v1/feature/<my FF here> ({:expires_in=>5 minutes})
$ DEBUG -- : Cache read: flipper/v1/feature/<my FF here> ({:expires_in=>5 minutes})
$ DEBUG -- : Cache fetch_hit: flipper/v1/feature/<my FF here> ({:expires_in=>5 minutes})
```

Notes:

1. The FF I'm requesting is already written in the cache
2. It seems to request everything again, write again
3. Notice that the last `read` and `fetch_hit` lines repeat for the same FF

### Metrics

**This is a metric from the Memcache instance that illustrates what happened when the new version was delivered in production. It's an average of "Set" command in 5 minutes.**
![image](https://user-images.githubusercontent.com/941776/128097974-68f86a07-bc8c-4cc3-a21f-12b0a982900a.png)

**The same pattern repeats for the "Get" command.**
![image](https://user-images.githubusercontent.com/941776/128098212-0e854da8-53ea-4cd8-827a-f457f78c93a6.png)

**One other interesting thing to notice is the pattern once more when looking at the occurrences of `Cache *` operations in our log files.**

![image](https://user-images.githubusercontent.com/941776/128098290-fcd80070-0c6d-41f4-9465-605f3cde50dd.png)

### My environment

```ruby
# Gemfile

ruby '~> 2.5.1'

gem 'puma', '~> 3.7.0'
gem 'rails', '5.2.3'
gem 'rack', '2.1.3'

```

```ruby
# application/config/initializers/flipper.rb

# frozen_string_literal: true

require 'flipper'
require 'flipper/adapters/active_record'
require 'flipper/adapters/active_support_cache_store'

class CustomFlipperCacheStore < Flipper::Adapters::ActiveSupportCacheStore
  def get(feature)
    # Allow % of actors to be used without cache
    return @adapter.get(feature) if feature.key.end_with?('_some_pattern')

    super
  end
end

Flipper.configure do |config|
  config.adapter do
    CustomFlipperCacheStore.new(
      Flipper::Adapters::ActiveRecord.new,
      Rails.cache,
      expires_in: 5.minutes
    )
  end
end
``` 

#### Rack::Timeout::RequestTimeoutException: Request ran for longer than 60000ms
```
  from flipper/adapters/active_support_cache_store.rb:136:in `read_many_features'
  from flipper/adapters/active_support_cache_store.rb:91:in `get_all'
  from flipper/adapters/memoizable.rb:108:in `get_all'
  from flipper/dsl.rb:200:in `preload_all'
  from flipper/middleware/memoizer.rb:73:in `memoized_call'
  from flipper/middleware/memoizer.rb:42:in `call'
  ```
  
  #### ThreadError: deadlock; recursive locking
  ```
  from flipper/adapters/active_support_cache_store.rb:129:in `read_feature_keys'
  from flipper/adapters/active_support_cache_store.rb:90:in `get_all'
  from flipper/adapters/memoizable.rb:108:in `get_all'
  from flipper/dsl.rb:200:in `preload_all'
  from flipper/middleware/memoizer.rb:73:in `memoized_call'
  from flipper/middleware/memoizer.rb:42:in `call'
  ```

I'm looking for any insight that could help us to work around this problem. :)
Thanks

**Comment by wenderjean** [comment]
For future reference, this is a side effect since version 0.21.0 considering the fact it'll memoize and preload all FF's for every request.

https://github.com/jnunemaker/flipper/blob/v0.22.0/docs/Optimization.md#memoization

**Comment by jnunemaker** [comment]
I'm planning on reading this in depth. But I'm confused why you closed the issue. Thread problems are not intended. We generally go the route of duplicating a flipper instance per thread to avoid thread issues. This does mean that all adapters must be thread safe. 

Are you using connection pooling with Dalli? 

Are you doing any other caching with rails cache or dalli? 

If so, were you with same setup prior to updating flipper? 

Do the problems go away if you remove the cache and just use the AR adapter?

**Comment by jnunemaker** [comment]
Also, I and others are using flipper with puma and with active support caching so I don't think that is the issue.

I'd love to get this figured out with you so even if we have to pair (if you are comfortable) I can take a look sometime. We can try to resolve via issues for now though.

**Comment by wenderjean** [comment]
hey @jnunemaker,

I closed the issue because I imagined the issue was entirely related to the `preload` itself. Yesterday we rolled the version back to `0.19.1` and it solved the issue for now.

Are you using connection pooling with Dalli?
  - We're using Dalli in our project and before that move we were on version `0.13.0` of Flipper.
  
Are you doing any other caching with rails cache or dalli?
  - We have an HTTP cache in place for Faraday in the other applications that reaches our API to consume features
  
If so, were you with same setup prior to updating flipper?
  - I tried two different setups using a version with `config.default`  that was in place already and that one I posted above using `config.adapter`, I'll leave the old version in the end of this comment:

Do the problems go away if you remove the cache and just use the AR adapter?
  - I can see it is reaching the database for every request what makes me think we'd see an increase in the number of database transactions in production

We have an architecture like:

1. Rails API hosting Flipper and configuring an endpoint to make features public available
2. Other applications running different servers/instances, when they need to consume features the use Faraday to reach our API
    - Here we have an extra HTTP cache in place

Using `pry` to debug I noticed an initial weird condition in `Features#inspect` because we're triggering the method `state` and the `enabled_gate_names` causing the `read` and `fetch_hit` duplication I mentioned before but, it is explained by the fact that `pry` invokes `#inspect`, using Puma some other place should be invoking it also in order to explain.

**Comment by wenderjean** [comment]
I've spent more time with version 0.22.0` trying to figure out but actually, we have a lot of cache requests unless we turn `preload` off.

We can schedule a pair when you have some time @jnunemaker, no problem.

**Comment by jnunemaker** [comment]
@wenderjean https://calendly.com/nunemaker/chat

**Comment by jnunemaker** [comment]
@wenderjean 

1. why are you using CustomFlipperCacheStore? Just curious why you don't want to cache certain things.

2. > we have a lot of cache requests unless we turn preload off.

Yep. My expectation is memoization and preloading on means 1 or 2 cache calls per request. That's better than 1-2 per feature per request though, which is what you'll get without them turned on. If you are seeing more requests since uploading, my guess is that you should turn preloading off as it means that most of your requests don't use feature flags. 

I would however leave memoizing on.

You should not see more than 1 or 2 read cache calls per request (depending on cache state and adapters in use) with memoize and preload on. If you are seeing more than that, I'd definitely need to see more to be able to help. 

3. Is this correct for your older version setup:

* same adapter(s) with caching
* no memoization or preloading

And now for the new version:

* cached adapter
* memoization and preloading on

4. Do the other api requests use feature flags or just the one that the faraday clients hit?

**Comment by elias19r** [comment]
Hi @jnunemaker! Thanks for the work you've put into this lib over the years

> Do the other api requests use feature flags or just the one that the faraday clients hit?

We have _one_ web app that makes use of the Flipper gem. It uses MySQL + Memcached to store feature flags, and serves a Flipper-API endpoint at `GET /features/{name}`

Then, _other web apps_, using a Faraday client, send requests to it to check for a feature when they need

As @wenderjean mentioned, after upgrading Flipper to version 0.22.0 we noticed our cache read/write usage drastically increased

![image](https://user-images.githubusercontent.com/254979/128519538-e581b638-5893-4fd1-950b-9af72b88b0fc.png)

Memcached is used for caching other things too across multiple instances of the other web apps, so this increase was really concerning. Then Memcached usage stabilized after downgrading to version 0.19.1

We think the attempt to write to `flipper/v1/get_all`, followed by reading `flipper/v1/features` and `read_multi` of all `flipper/v1/feature/*`, on every request, is what was causing it: https://github.com/jnunemaker/flipper/blob/v0.22.0/lib/flipper/adapters/active_support_cache_store.rb#L81-L93

So, I'd say that _for apps storing feature flags with database + cache and serving a Flipper-API endpoint like `GET /features/{name}`, from which other apps will fetch a feature at a time_, a preload-all-memoization may cause an unnecessary load on your cache server

**Comment by elias19r** [comment]
My comment above just complements what Wender had already described about our setup

https://github.com/jnunemaker/flipper/issues/549#issuecomment-892815481
> We have an architecture like:
> 1. Rails API hosting Flipper and configuring an endpoint to make features public available
> 2. Other applications running different servers/instances, when they need to consume features they use Faraday to reach our API
>    - Here we have an extra HTTP cache in place

**Comment by elias19r** [comment]
Also, not related to the main issue, but I'd like to bring your attention to this potential issue with `Features#inspect` Wender mentioned above

> Using pry to debug I noticed an initial weird condition in `Features#inspect`

We noticed that `Features#inspect` ends up calling `adapter.get(self)` through `gate_values` when building the string for `state=` and `enabled_gate_names=` here https://github.com/jnunemaker/flipper/blob/v0.22.0/lib/flipper/feature.rb#L331-L332

So the act of logging a Feature will cause it to be read twice, so people can potentially increase the number of cache/DB calls just by logging features

**Comment by jnunemaker** [comment]
@elias19r correct. This is negated through memoization, which we turn on by default now. Is there something that we should do about it? I'm not opposed to changing feature#inspect, but I'm not sure how valuable it is without the gate/state information.

**Comment by elias19r** [comment]
Hi @jnunemaker!

> This is negated through memoization, which we turn on by default now.

I'm sorry, which part is _this_ referring to?

As far as we could understand, a `GET /features/{name}` request is intended to get a single feature flag and, in this case, preload-all-memoization wouldn't help -- instead, it will actually cause more load by making 3 calls: an attempt to write to `flipper/v1/get_all`; then reading `flipper/v1/features`; then `read_multi` of all `flipper/v1/feature/*`

I'm not sure if that is a bug or if we should just advise users to disable preload if they are serving a `GET /features/{name}` endpoint with Flipper-API

>  I'm not opposed to changing feature#inspect, but I'm not sure how valuable it is without the gate/state information.

Oh, agree! I don't know how we should deal with `Feature#inspect`. I can't think of a suggestion at the moment :|

**Comment by elias19r** [comment]
> As far as we could understand, a `GET /features/{name}` request is intended to get a single feature flag and, in this case, preload-all-memoization wouldn't help -- instead, it will actually cause more load by making 3 calls: an attempt to write to `flipper/v1/get_all`; then reading `flipper/v1/features`; then `read_multi` of all `flipper/v1/feature/*`

To add more info, _without_ preload-all-memoization, as of version 0.19.1, a `GET /features/{name}` request makes 2 calls: reading from `flipper/v1/features`; then reading a single key `flipper/v1/feature/{name}`

**Comment by jnunemaker** [comment]
> I'm sorry, which part is this referring to?

Sorry, the multiple adapter calls when you use `#inspect` are negated by memoization/preloading. The first call would be memoized and all subsequent would be served from memory.

> As far as we could understand, a GET /features/{name} request is intended to get a single feature flag and, in this case, preload-all-memoization wouldn't help -- instead, it will actually cause more load by making 3 calls: an attempt to write to flipper/v1/get_all; then reading flipper/v1/features; then read_multi of all flipper/v1/feature/*

Ok, I understand what you are getting at now. Thanks for explaining. For serving API requests, you are correct in that you might want to disable preloading on individual feature requests to achieve optimal network requests.

Off the top of my head, I think you could do this:

```ruby
Rails.application.configure do
  config.flipper.memoize = ->(request) { request.path !~ /\/features\/.*/ }
end
```

It does make me wonder if we need an `:if`/`:unless` option for preloading (instead of memoizing and preloading together). Then, you could leave memoization on and just turn preloading off for the individual feature routes.
