### ISSUE TITLE
Import method does not import disabled features when importing to ActiveRecord adapter

### ISSUE THREAD

**Issue by taylorecton** [jnunemaker/flipper#553]
When following the [steps to swap adapters](https://github.com/jnunemaker/flipper/blob/master/docs/Adapters.md) (quoted below) to the ActiveRecord adapter, enabled features are added, but disabled features from the remote/source adapter do not get added to the new ActiveRecord adapter (omitted some of the example code for brevity):
```ruby
# Say you are using redis...
redis_adapter = Flipper::Adapters::Redis.new(Redis.new)
redis_flipper = Flipper.new(redis_adapter)

# And you would like to switch to active record...
ar_adapter = Flipper::Adapters::ActiveRecord.new
ar_flipper = Flipper.new(ar_adapter)

ar_flipper.import(redis_flipper)
```

The issue occurs in the `Flipper::Adapters::Sync::Synchronizer.sync` method which is called during the import:
https://github.com/jnunemaker/flipper/blob/85fd90fc8958a83473173dc13f89d8d12126346c/lib/flipper/adapters/sync/synchronizer.rb#L33-L48

Specifically, when line 40 tries to access `local_get_all[feature_key]`, the `local_get_all` hash is modified because of the way the ActiveRecord adapter defines the hash returned by its `get_all` method:
https://github.com/jnunemaker/flipper/blob/85fd90fc8958a83473173dc13f89d8d12126346c/lib/flipper/adapters/active_record.rb#L112

If `feature_key` was not already in the `local_get_all` hash, it gets added as a result of line 40 in the `Flipper::Adapters::Sync::Synchronizer.sync` method when `@local` is an ActiveRecord adapter (not sure if other adapters have similar behavior). 

The result is that when execution reaches line 47 in the sync method, any `feature_key`s that were not already in the `local_get_all` hash have been added to the hash, and `features_to_add` will be an empty list and line 48 will not add any of the disabled features from the `@remote` adapter.

I believe this could be easily fixed by changing line 40 in the `Flipper::Adapters::Sync::Synchronizer.sync` method to be the following:
```ruby
local_gates_hash = local_get_all.key?(feature_key) ? local_get_all[feature_key] : @local.default_config
```

This way the code only tries to access the `local_get_all` hash if the key is already present, preventing the `local_get_all` hash from being mutated in the loop. I can add output from a debugging session to help clarify what's happening if needed.

I'm happy to submit a PR for the proposed solution above if it seems reasonable! Otherwise, let me know if there's anything else I can do to help out with this issue.

**Comment by jnunemaker** [comment]
Wow! Good find. Sorry about that pain it caused. That fix is fine with me. I'm actually thinking maybe having default config like that in the AR adapter is bad. Might be better to just not do that. But I can't currently remember why I did so I'll have to look at it a bit.

**Comment by taylorecton** [comment]
No pain, just some confusion! 😄

I went ahead and submitted a PR for what I suggested. If you'd rather take some time to look at the adapter code, no worries! I just suggested fixing the issue this way so the Synchronizer doesn't have to worry about how the individual adapters return the hash from their `get_all` method.
