### ISSUE TITLE
Using HTTP adapter with dynamic URL

### ISSUE THREAD

**Issue by djpowers** [jnunemaker/flipper#559]
I was wondering if there was a way to use the [HTTP adapter](https://github.com/jnunemaker/flipper/tree/master/docs/http) in such a way that the URL used to reach the mounted Flipper API could be modified at runtime.

The use case here involves using the [Apartment gem](https://github.com/influitive/apartment). Each tenant has its own database, and thusly its own Flipper gates. The subdomain is used to determine the tenant, so I was hoping to modify the subdomain on the fly based on a parameter, where `tenant` is a variable: `"https://#{tenant}.flipperapi.com"`

I have the HTTP adapter working when configured in `config/initializers` with a static URL. I tried moving the same configuration block out of the initializer to be called by a controller, but that no longer returned results, so I thought it might require being part of the initialization phase.

While exploring, I saw that `Flipper.configuration` is available during runtime, but I wasn't sure if that could be modified. My other thought was the possibility of initializing several HTTP adapter instances, but that didn't necessarily seem practical since there could be any number of tenants.

I understand this is probably an atypical setup, so I understand if it's not something you're able to support. But I figured I'd ask in case there's an easy workaround that would not require any changes to the gem.

Thanks!

**Comment by djpowers** [comment]
Following up in case anyone else stumbles upon this, the issue was that I was pulling the entire configuration block into my controller action, when just the Flipper Adapter object would suffice.

Using the example from the docs, you can require the adapter and omit the configure wrapper:
```ruby
Flipper::Adapters::Http.new({
  url: 'http://app.com/mount-point', # required
  headers: { 'X-Custom-Header' => 'foo' },
  basic_auth_username: 'user123',
  basic_auth_password: 'password123'
  read_timeout: 5,
  open_timeout: 2,
})
```

**Comment by jnunemaker** [comment]
@djpowers glad you figured this out. The top level configuration is just for the standard setup. Your snippet is correct for non-standard setups. www.flippercloud.io actually has its own adapter and configures it to use per request for whichever org/project/environment is being read from or written to.
