### ISSUE TITLE
Allow enable/disable to take a block

### ISSUE THREAD

**Issue by hschne** [jnunemaker/flipper#571]
Apologies if this has come up before. I searched existing issues but didn't find a feature request that looked similar :) 

## Problem

In our tests, we often have the situation where were we verify that some behavior applies while a feature flag is enabled. Something like this: 

```ruby
test 'do something with feature' do
  Feature[:myfeature].enable
  do_something
  Feature[:myfeature].disable
end
```

To avoid breaking test isolation we do have to make sure enabled features are disabled again - there might be other tests that require that flag to be disabled. However, always enabling and disabling features like that is a bit cumbersome. Tests end up being littered with `Feature.enable`/`Feature.disable` calls which isn't _nice_. 

## Proposed Solution

It would be sweet if `Flipper::Feature.enable` and `Flipper::DSL.enable` would take a block. The expected behavior is then that the specified feature is only enabled _within that block_. The test above becomes: 

```ruby
test 'do something with feature` do
  Feature[:myfeature].enable { do_something }
end
```

## Alternatives Considered

This _probably_ has no use outside tests, and would be a rather specific fix. For most users, explicitly calling `enable/disable` would be sufficient. Rather than changing `enable`, separate methods (e.g. `enable_for`, `enable_in_block`) could be added. 

It is also not too bad to just monkey patch the existing methods, e.g. 
```ruby
module FeaturePatch
  def enable(thing = true)
    result = super(thing)
    return result unless block_given?

    yield
    disable(thing)
  end
end

Feature.prepend(FeaturePatch)
```
But, you know, would be nicer to just have it in the gem itself :sweat_smile: 

--- 

Let me know what you think. I'll gladly put in a pull request if this is something that could be added :slightly_smiling_face:

**Comment by jnunemaker** [comment]
Thanks for the great write up! Always helpful to have all that info when responding. Appreciate it.

First, I'll be direct and say that I agree that this seems more just for tests. I don't want to pull it into the general DSL/API for flipper when its really just for tests.

I'd like to describe what I do for tests (which I haven't really ever and should write up a big post someday). I always switch to the memory adapter in the setup of each test/spec.

```ruby
Flipper.instance = Flipper.new(Flipper::Adapters::Memory.new)
```

This makes it so all features are disabled by default. 

Then, I just use `Flipper.enable(:my_feature)` wherever I want to test that path. 

If you want to flip that around and always assume enabled unless disabled, you can. I talked about how we did that at GitHub [in this issue](https://github.com/jnunemaker/flipper/issues/482#issuecomment-725535409). 

Does any of that help or resonate? Closing the issue to keep things tidy but still very open to conversation on this.

**Comment by hschne** [comment]
> I don't want to pull it into the general DSL/API for flipper when it's really just for tests.

I absolutely understand, this is a very specific problem to have after all. Your comment and links are a great help, thanks a lot for that! 

I just want to clarify that I'm not looking to enable all features for all tests. What I'm doing is testing several code paths of a class, some with a Feature enabled, some without. `Flipper.enable(:my_feature)` works, but - at least in my experience - we need to disable the feature at the end of the test, lest we break test isolation. 

I've had this situation: If you have one test (A) that requires a feature to be disabled to pass, and one (B) that requires the feature to enabled, random test order may result in A randomly failing if B is ever executed first. As far as I can tell, with the memory adapter, features are enabled/disabled globally within the test process. So at the end of B, we'd have to disable the feature again. 

So that's where I'm coming from. Maybe it's just something silly with our test setup that causes brittle tests :zany_face: 

Anyways, agree that there is no point in keeping this open, and thanks once again for the help! :raised_hands:

**Comment by jnunemaker** [comment]
Yep. The memory adapter will fix that as then they get reset for every test. 

What adapter are you using currently? It sounds like it isn't getting reset between tests.

**Comment by hschne** [comment]
> It sounds like it isn't getting reset between tests.

That's exactly it. Clearing after each test should do it, thanks! :tada:
