### ISSUE TITLE
Support for the applications using multiple databases

### ISSUE THREAD

**Issue by jgrau** [jnunemaker/flipper#573]
Hi

I'm installing `flipper-active_record` and `flipper-ui` but I'm running into the follow error:

```
ActiveRecord::ConnectionNotEstablished
No connection pool for 'ActiveRecord::Base' found for the 'reading' role.
```

I believe this is due to my application using [Multiple Databases with Active Record](https://guides.rubyonrails.org/active_record_multiple_databases.html) which is configured in `ApplicationRecord` (which inherits from `ActiveRecord::Base`) but `flipper-active_record` uses `ActiveRecord::Base` as the parent class for the models.

Is it feasible to support a custom parent class? I recently started using the gem `good_job` which implements in what looks to me like a fairly simple approach: https://github.com/bensheldon/good_job/search?q=active_record_parent_class

With some guidance I'd love to submit a PR :)

**Comment by jgrau** [comment]
Ah, digging a bit more made me realise I can configure the feature and gate classes. This worked:

```
require 'flipper/adapters/active_record'

class FlipperFeature < ApplicationRecord
end

class FlipperGate < ApplicationRecord
end

Flipper.configure do |config|
  config.adapter do
    Flipper::Adapters::ActiveRecord.new(
      feature_class: FlipperFeature,
      gate_class: FlipperGate,
    )
  end
end
```

🎉

**Comment by bkeepers** [comment]
@jgrau Glad you figured out a solution that will work!

I think you could also do the following if you want to avoid redefining the classes. I don't think it matters either way.

```ruby
Flipper::Adapters::ActiveRecord::Feature.connects_to database: { writing: :primary, reading: :replica }
Flipper::Adapters::ActiveRecord::Gate.connects_to database: { writing: :primary, reading: :replica }
```
