### ISSUE TITLE
Setting Flipper flags in the future

### ISSUE THREAD

**Issue by harrylewis** [jnunemaker/flipper#580]
Hey there 👋 

I've been here before, and just want to say, still loving Flipper!

I'm curious to know if there has ever been any discussion about providing functionality to enable/disable Flipper flags at some point in the future? The way my team currently handles setting flags in the future is to set a reminder on Slack or some other service, to remind ourselves at the appropriate time to turn it on.

While this works, the idea of allowing Flipper to handle that "reminder" functionality seems like a small quality of life improvement in our team's workflow, and also means it will actually get set appropriately in case no one is around at the time the reminder goes off.

I'd love to hear folks' thoughts about this.

I realize this isn't such a simple feature as it requires some sort of store to collect the future flag settings, a server process to check them and run them at the correct time, possibly editing/deleting functionality, and more. I like the simple nature of the open source `flipper` gem. Perhaps this could be an add-on gem somewhere else. I imagine also functionality like this is probably easier to support in a Cloud environment like Flipper Cloud.

**Comment by jnunemaker** [comment]
Yep. This works on my learn-the-rules branch. Hoping to get that ready for release this year yet or at worst early next year. 

https://github.com/jnunemaker/flipper/blob/141be3c40eab072b19cc4dd5e8e795f155db40e4/examples/expressions.rb#L209

It'll probably be easier by the time the release hits but that should give you an idea that it will at least be possible.

**Comment by harrylewis** [comment]
Awesome, from a brief look, I really like the flexibility of the expressions API, to encapsulate not only this case, but also an arbitrary set of "rules" that are not time-based. Looking forward to it!

**Comment by jnunemaker** [comment]
Yep! I'm going to add dates and times in addition to just Unix epoch stuff. 

Also it should be only a few lines to make features dependent on each other. So you could say events_receiving is only enabled if events feature is enabled (for the same properties). 

It's going to be awesome!

**Comment by Intrepidd** [comment]
Hi there, I'm really interested in this feature, but it doesn't seem to have been released yet ? 

Any way I can help ? 

Thanks

**Comment by jnunemaker** [comment]
It's not released. Need to get a UI around it and then we can.
