### ISSUE TITLE
How to temporarily disable for lifecycle of a request? 

### ISSUE THREAD

**Issue by rsanheim** [jnunemaker/flipper#588]
Hey @jnunemaker, hope you are well!

I'm working on adding a more cohesive strategy for feature flags for [simple-server](https://github.com/simpledotorg/simple-server) similar to what we built at GitHub around Flipper in the early days. Basically, allow flipping flags on or off via query string for a single request only, and then reset the state at the end of the request. There are a couple main use cases

* when features are staff shipped we want staff to be able to disable features temporarily to compare results or perf without having to go to the UI and flip things on and off
* when things are fully shipped (so globally enabled), we want some users (probably just staff) to be able to temporarily disable features via a query string...to track down regressions etc

Right now I hacked this together as an `around_action` for a single feature flag, which doesn't work right because we don't really know the original state from the API:

```ruby
  def set_feature_flags_from_params
    if params[:_follow_ups_v2]
      original = current_admin.feature_enabled?(:follow_ups_v2)
      current_admin.enable_feature(:follow_ups_v2)
    end
    yield
  ensure 
  # reset the flag back to original state, but we don't actually know the original state here - 
  # for example, the feature could be enabled as a % of actors, or could be globally disabled.
    if original
      current_admin.enable_feature(:follow_ups_v2)
    else
      current_admin.disable_feature(:follow_ups_v2)
    end
  end
```

The above could handle some more edge cases, but it feels frail and like there must be a better way. 😁 I'm guessing a good solution here would probably be to have a thread local copy of Flipper state that requests can modify however they want and then discard after the request is done.  Is there something better in the lower level API I could be doing here, or something else I'm missing? Thanks!

**Comment by rsanheim** [comment]
Here is the actual code in question where I'm hacking things in to set and reset -- the above example was half baked: https://github.com/simpledotorg/simple-server/pull/3111/files#r763473526

**Comment by bkeepers** [comment]
:wave: @rsanheim! I've been working with @jnunemaker on Flipper lately, so hope you don't mind me chiming in here.

This is a really interesting use case and there are probably a couple ways to approach it. The first idea that comes to mind (that doesn't require custom adapters) is to create an instance of the `Memory` adapter for each request and import the default adapter. Then you can modify the instance local to that request as much as as you want since it will be discarded at the end of the request.

I haven't tested this code, but here's an idea of how to implement it (assuming Rails):

```ruby
class ApplicationController < ActionController::Base
  around_action :toggle_features

  def toggle_features
    # Check if current user is allowed to override features per request
    if Flipper.enabled? :toggle_features, current_user
      # Import settings from default adapter into memory adapter. If using the default config,
      # this should not perform any network requests because features are already preloaded.
      adapter = Flipper::Adapters::Memory.new
      adapter.import(Flipper.adapter)

      # Enable/disable features from request parameters
      request.params[:enable].to_s.split(',').each { |feature| Flipper.new(adapter).enable feature }
      request.params[:disable].to_s.split(',').each { |feature| Flipper.new(adapter).disable feature }

      # Set default Flipper instance to a ReadOnly version of memory adapter to prevent writes.
      # This is stored in `Thread.current`, so it will only apply to this thread
      Flipper.instance = Flipper.new(Flipper::Adapters::ReadOnly.new(adapter))
    end

    yield
  ensure
    # Ensure flipper instance is reset for next request
    Flipper.instance = Flipper.configuration.default
  end
end
```

This is all guarded by a `:toggle_features` flag, so you need to enable that for whoever you want to be able to do this.

Would this work?

**Comment by jnunemaker** [comment]
@rsanheim I am well! So great to see you drop into my email today. 😄 

@bkeepers that is a super neat idea! I love it. Kinda makes me want to build this into a middleware that is automatic for people somehow. 

* Insert middleware. 
* Define who is authorized to do this.
* Peel out. 

I'd probably change Flipper.instance back to some @original_flipper_instance variable but otherwise this looks like a great idea. Curious what your gut feeling is @rsanheim.

**Comment by rsanheim** [comment]
@bkeepers that looks like a great approach -- I'll give that a try on my next pass through this code. Thanks for the detailed suggestion!

@jnunemaker Agreed, would be awesome if this was a middleware that folks could drop in and use. I suppose the there would need to be a convention for what the feature flag names are in the params, but that wouldn't be too tough to make configurable or just something each project could override.

**Comment by bkeepers** [comment]
@rsanheim Let us know how it works out. I'm going to close this in the mean time.

> Kinda makes me want to build this into a middleware that is automatic for people somehow.

That would be cool! It would require access to the current actor, which would require some gymnastics for some people to get from the Rack environment instead of a Rails controller.

**Comment by marcoadkins** [comment]
@bkeepers Had to make a few tweaks to the memory adapter setup (use import rather than get all) but other than that its working great. Thanks for the idea 💡 

```ruby
# frozen_string_literal: true

require 'flipper/adapters/read_only'

module FlipperQueryParams
  extend ActiveSupport::Concern

  included do
    around_action :toggle_features
  end

  def toggle_features # rubocop:disable Metrics/AbcSize
    # Check if current user is allowed to override features per request
    if feature_enabled?(:toggle_features) && (params[:enable] || params[:disable])
      # Create new memory adapter using data from default adapter.
      adapter = Flipper::Adapters::Memory.new
      adapter.import(Flipper.adapter)

      # Enable/disable features from request parameters
      params[:enable].to_s.split(',').each { |feature| Flipper.new(adapter).enable feature }
      params[:disable].to_s.split(',').each { |feature| Flipper.new(adapter).disable feature }

      # Set default Flipper instance to a ReadOnly version of memory adapter to prevent further
      # writes. This is stored in `Thread.current`, so it will only apply to this thread
      Flipper.instance = Flipper.new(Flipper::Adapters::ReadOnly.new(adapter))
    end

    yield

  ensure
    # Ensure flipper instance is reset for next request
    Flipper.instance = Flipper.configuration.default
  end
end
```

**Comment by marcoadkins** [comment]
@jnunemaker No problem. Yea there were some issues with the data mapping. The raw gate values were weirdly double nested.

```ruby
# flipper/gate_values.rb:22
def initialize(adapter_values)
      Rails.logger.info "MARCO DEBUG|ADAPTER VALS|#{adapter_values}"
      @boolean = Typecast.to_boolean(adapter_values[:boolean])
      @actors = Typecast.to_set(adapter_values[:actors])
      @groups = Typecast.to_set(adapter_values[:groups])
      @percentage_of_actors = Typecast.to_percentage(adapter_values[:percentage_of_actors])
      @percentage_of_time = Typecast.to_percentage(adapter_values[:percentage_of_time])
end
```

```shell
MARCO DEBUG|ADAPTER VALS|{:boolean=>{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}, :actors=>{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}, :percentage_of_actors=>{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}, :percentage_of_time=>{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}, :groups=>{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil}}
```

Ended up throwing exceptions when trying to typecast:
```shell
{:message=>"Exception", :exception_class=>ArgumentError, :exception_message=>"{:boolean=>nil, :groups=>#<Set: {}>, :actors=>#<Set: {}>, :percentage_of_actors=>nil, :percentage_of_time=>nil} cannot be converted to an integer", :trace=>["/Users/macro/.asdf/installs/ruby/2.6.4/lib/ruby/gems/2.6.0/gems/flipper-0.19.0/lib/flipper/typecast.rb:27:in `to_integer'", "/Users/macro/.asdf/installs/ruby/2.6.4/lib/ruby/gems/2.6.0/gems/flipper-0.19.0/lib/flipper/typecast.rb:51:in `to_percentage'", "/Users/macro/.asdf/installs/ruby/2.6.4/lib/ruby/gems/2.6.0/gems/flipper-0.19.0/lib/flipper/gate_values.rb:28:in `initialize'",
```
