### ISSUE TITLE
ActiveSupportNotification Log Subscription triggers feature db query on every request

### ISSUE THREAD

**Issue by michaelwapp** [jnunemaker/flipper#599]
Using the following gems / versions: 
```
gem 'flipper', '0.23.0'
gem 'flipper-active_record', '0.23.0'
gem 'flipper-ui', '0.23.0'
ruby '3.0.2'
gem 'rails', '6.1.4.3'
```
I've found a problem when analyzing my SQL queries. For every request I receive in my application e.g. a default get request the following feature flipper query is also triggered. Do you know what the cause of this could be? 

```
SELECT "flipper_features"."key" AS feature_key, "flipper_gates"."key", "flipper_gates"."value" FROM "flipper_features" LEFT OUTER JOIN "flipper_gates" ON "flipper_features"."key" = "flipper_gates"."feature_key"
Query Trace:
/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/active_record_query_trace-1.8/lib/active_record_query_trace.rb:105:in `fully_formatted_trace'
/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/active_record_query_trace-1.8/lib/active_record_query_trace.rb:66:in `sql'
/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/subscriber.rb:150:in `finish'
/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/log_subscriber.rb:115:in `finish'
/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.3/lib/active_support/notifications/fanout.rb:157:in `finish'
```

My flipper.rb initializer looks like this: 
```
# frozen_string_literal: true

# Require adapter to set default store
require 'flipper/adapters/active_record'

# Simple check if flipper table exists
def flipper_table_exists?
  ActiveRecord::Base.connection.tables.include?('flipper_features')
rescue StandardError
  false
end

# For the test environment an in-memory adapter will be used
# and all features are disabled by default. See /test/test_helper.rb
if !Rails.env.test? && flipper_table_exists?
  # Get all features
  features = Flipper.features
  Flipper.memoize = true
  Flipper.preload_all

  begin
    feature_keys = %i(test_1_key, test_2_key)

    feature_keys.each do |feature_key|
      unless features.any? { |f| f.key == feature_key.to_s }
        if Rails.env.production?
          Flipper.disable feature_key
        else
          Flipper.enable feature_key
        end
      end
    end
  rescue StandardError => e
    # Ignore exceptions on app startup
    Rails.logger.warn("Ignoring exception on flipper feature initialization: #{e.message}")
    Rails.logger.warn e.backtrace.join("\n")
  end
end
```

**Comment by michaelwapp** [comment]
Adding 
``` 
 Rails.application.configure do
    config.flipper.preload = false
end
```

to my `initializer/flipper.rb` didn't change the behaviour. The query is still triggered every time I access a route.

Any other ideas how to remove this db request?

**Comment by bkeepers** [comment]
@michaelwapp there's a bug in the current release that causes preload/memoizer settings in config/initializers to be ignore. It is fixed in #586 and will be in the next release.

In the mean time, moving those settings to `config/application.rb` should fix it.

**Comment by michaelwapp** [comment]
Using both (in `config/application.rb`)
```
 Rails.application.configure do
    config.flipper.preload = false
    config.flipper.memoize = true
end
```
results into a kind of strange behaviour. 


If I set memoize to `true` and preload to `false` the above mentioned query goes away. However, the memoizing doesn't work correctly as there are queries being executed on each request for the specific / dedicated feature keys. So its an either - or decision where in both cases queries are executed which I don't want or need. 

Ideas?

**Comment by bkeepers** [comment]
> If I set memoize to `true` and preload to `false` the above mentioned query goes away. However, the memoizing doesn't work correctly as there are queries being executed on each request for the specific / dedicated feature keys.

This is as designed.

`memoize` will save the result of each feature check after the first time, so subsequent calls will not trigger another query.

`preload` will load all your features once per request, so no matter how many features you check or how many times you check them, there will only ever be one query.

> So its an either - or decision where in both cases queries are executed which I don't want or need.

Are you seeing a performance issue?

You could disable the `preload` config and manually call `Flipper.preload_all` or `Flipper.preload(*feature_names)` in controllers that you want it.

**Comment by michaelwapp** [comment]
> `memoize` will save the result of each feature check after the first time, so subsequent calls will not trigger another query.

That's exactly what it doesn't do if I set both `memoize = true` and `preload = false`. That's why I'm confused. Subsequent SQL queries are triggered if configured like this.

**Comment by jnunemaker** [comment]
Would you mind setting memoize to true and preload to false, restarting your app, refreshing the page and the snagging the features you are checking and the sql logs? I'd love to give that a look.

**Comment by michaelwapp** [comment]
Here is my `config/application.rb` file: 

```
module TestWeb
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.1
    
    config.middleware.move_after ActionDispatch::ShowExceptions, Flipper::Middleware::Memoizer
    config.flipper.preload = false
    config.flipper.memoize = true
  end
end
```

Starting and accessing my route where the feature flipper `sentry_tracing` is used results into the following SQL logs: 

```
  Flipper::Adapters::ActiveRecord::Gate Load (1.4ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "sentry_tracing"]]
  ↳ config/initializers/sentry.rb:26:in `block (2 levels) in <main>'
  Flipper feature(sentry_tracing) enabled? true (67.4ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test ...

  Flipper::Adapters::ActiveRecord::Gate Load (3.1ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "sentry_tracing"]]
  ↳ config/initializers/sentry.rb:26:in `block (2 levels) in <main>'
  Flipper feature(sentry_tracing) enabled? true (8.0ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test ... 

  Flipper::Adapters::ActiveRecord::Gate Load (2.0ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "sentry_tracing"]]
  ↳ config/initializers/sentry.rb:26:in `block (2 levels) in <main>'
  Flipper feature(sentry_tracing) enabled? true (10.3ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test ...
```


If I change the config to only have `config.flipper.memoize = true` it results into the following SQL queries: 


```
 (1.4ms)  SELECT "flipper_features"."key" AS feature_key, "flipper_gates"."key", "flipper_gates"."value" FROM "flipper_features" LEFT OUTER JOIN "flipper_gates" ON "flipper_features"."key" = "flipper_gates"."feature_key"
  Flipper feature(sentry_tracing) enabled? true (0.2ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test ...

   (5.0ms)  SELECT "flipper_features"."key" AS feature_key, "flipper_gates"."key", "flipper_gates"."value" FROM "flipper_features" LEFT OUTER JOIN "flipper_gates" ON "flipper_features"."key" = "flipper_gates"."feature_key"
  Flipper feature(sentry_tracing) enabled? true (0.0ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test ...

   (1.4ms)  SELECT "flipper_features"."key" AS feature_key, "flipper_gates"."key", "flipper_gates"."value" FROM "flipper_features" LEFT OUTER JOIN "flipper_gates" ON "flipper_features"."key" = "flipper_gates"."feature_key"
  Flipper feature(sentry_tracing) enabled? true (0.0ms)  [ thing=nil gate_name=boolean ]
method=POST path=/api/iot/v1/test...
```

**Comment by jnunemaker** [comment]
@michaelwapp I think I'm going to need to setup a test rails app and see if I can reproduce this.
