### ISSUE TITLE
Shouldn't checking .enabled? on an actor work the same way as on a user?

### ISSUE THREAD

**Issue by tilo** [jnunemaker/flipper#600]
```
user = User.find 1
actor = Flipper::Actor.new("User:${user.id}")
user.flipper_id == actor.flipper_id
 => true

name = :my_feature
Flipper[name].enabled? user
 => true
Flipper[name].enabled? actor
 => false
 ```
 🤯 
 Shouldn't this work?
 I must be doing something wrong here 🤔 
 
 Flipper version is `0.20.4`

**Comment by jnunemaker** [comment]
You are using $ to interpolate but in Ruby it is #. 

Try this:  

actor = Flipper::Actor.new("User:#{user.id}")

**Comment by jnunemaker** [comment]
Also the separator is a semicolon instead of a colon by default.

**Comment by tilo** [comment]
@jnunemaker actually a typo in the Issue I opened - I did use a `#` and the code, and it shows this odd behavior:

```
> user = User.find 1
> Flipper[:tax_doc_show_2021].enabled? user
=> true
> Flipper[:tax_doc_show_2021].enabled? Flipper::Actor.new("User:#{user.id}")
=> false

```

**Comment by tilo** [comment]
@jnunemaker actually a typo when I typed the Issue last night 🤦 - in the code a `#` was used, and it shows this odd behavior:

```
> user = User.find 1
> Flipper[:my_feature].enabled? user
=> true
> Flipper[:my_feature].enabled? Flipper::Actor.new("User:#{user.id}")
=> false
```

**Comment by jnunemaker** [comment]
Gotcha. Your issue is the colon instead of semi-colon then. Did you change the colon?
