### ISSUE TITLE
Latest release with default config throws "Flipper::Middleware::Memoizer appears to be running twice" warning

### ISSUE THREAD

**Issue by coreyaus** [jnunemaker/flipper#604]
Firstly, massive thanks for an excellent open-source gem! 🙏   And obviously let me know if this is some misunderstanding on my part rather than a bug (and apologies if that's the case!)

## Background on the 2 issues we experienced upgrading to `v0.23.1`

We've started to use Flipper recently with a very basic configuration and only a few features at this stage. We use the `flipper-active_record` gem, and don't have any custom configuration in any initializers or anything like that (e.g. no calls to `middleware.use` anywhere in our code). The only extra configuration we had in place was the suggested testing config for RSpec (to use the memory adapter in our specs): https://www.flippercloud.io/docs/testing#starting-fresh

Everything worked fine for us on v0.22.2 and v0.23.0

We started to see two issues when upgrading from v0.23.0 to v0.23.1 (see the code comparison for those 2 releases [here](https://github.com/jnunemaker/flipper/compare/v0.23.0...v0.23.1)):
- The following warning appeared frequently across lots of specs (essentially any specs that loaded `Flipper.enabled?(:some_feature)` conditionals somewhere in the executed code):
    > Flipper::Middleware::Memoizer appears to be running twice. Read how to resolve this at [#523](https://github.com/jnunemaker/flipper/pull/523)
- We started to see failures in some specs that were directly testing behaviour determined by `Flipper.enabled?(:some_feature)` conditionals. The tests followed the same simple structure as [these great demos](https://www.flippercloud.io/docs/testing#test-both-sides)

By putting a `binding.pry` in our test suite with our original configuration we were also seeing that `Flipper::Middleware::Memoizer` was auto-loaded in our middleware stack (potentially out of sequence, given it was throwing that "appears to be running twice" warning above):
```ruby
Rails.configuration.middleware.middlewares.map(&:inspect).include?('Flipper::Middleware::Memoizer')
=> true
```

## Temporary fix

We had to remove the following [suggested testing config](https://www.flippercloud.io/docs/testing#starting-fresh) from our spec helper file:

```ruby
# in spec_helper.rb
RSpec.configure do |config|
  config.before(:each) do
    Flipper.instance = Flipper.new(Flipper::Adapters::Memory.new)
  end
end
```

And instead add the equivalent code to `/config/environments/test.rb`:

```ruby
# in test.rb
Rails.application.configure do
  config.flipper.instance = Flipper.new(Flipper::Adapters::Memory.new)
  # NOTE: This was also necessary to prevent the warning and spec failures
  config.flipper.memoize = false
end
```

## Questions

1. **Is this the expected behaviour?** If so perhaps it's just a matter of revising the docs on suggesting testing configuration [here](https://www.flippercloud.io/docs/testing) and the upgrade instructions [here](https://github.com/jnunemaker/flipper/blob/master/Changelog.md#upgrading) as well as any other places in the docs
    - Incidentally, the advice that customisations in `config/initializers/flipper.rb` are now ignored was also raised by a contributor [here](https://github.com/jnunemaker/flipper/pull/563#issuecomment-983765441) who suggested the option of moving those customisations to `config/application.rb` or `config/environments/[production|test|staging].rb` for it to get picked up early enough

2. **If this is a bug and not the expected behaviour**, should the impacts only be limited to our test suite? So far I've only seen this issue in our specs but am about to run a more thorough review of the logs from our staging and production environments (as well as running some manual testing). If this is an actual issue and not just a change that requires some tweaks to the docs, do you expect that it'll cause issues in staging/production environments similar to the issues described above in our test environment, or would it happily just be limited to our specs?
    - **UPDATE:** Flipper appears to be working as expected in staging and production based on our manual testing, however, we're seeing LOTS of instances of this warning in our staging and production logs: "Flipper::Middleware::Memoizer appears to be running twice".
    - So I suppose my question is whether this is an actual issue in staging/production, or is it just a case of the warning added in [PR #523](https://github.com/jnunemaker/flipper/pull/523) being thrown when it shouldn't be (as a false positive)? 

3. **Again, if this is a bug and not the expected behaviour** do you have any pointers on how we might be able to help resolve it?
    - As far as I could tell, the issues we saw first arose as a result of the changes in either (or both) of the following:
        - this PR: [PR #563](https://github.com/jnunemaker/flipper/pull/563) (which resolved [issue #562](https://github.com/jnunemaker/flipper/issues/562))
        - and/or [PR #586](https://github.com/jnunemaker/flipper/pull/586)
    - The warning above also flags [PR #523](https://github.com/jnunemaker/flipper/pull/523) for review, and there seems to be some ongoing discussion there that may be related
    - I don't understand the specifics well enough to even guess at a potential solution sorry, so would appreciate any guidance on how to configure a base Flipper installation to work with the latest version of the gem using the default settings

Massive thanks in advance for any help you're able to offer!

**Comment by jnunemaker** [comment]
1. Not expected and I'm not currently seeing it. 
2. Seems like yes, limited to test. 
3. I'm going to try to re-create. I haven't been able to yet. 

What version of rails are you on? Also, could you add your `rails middleware` output here? 

Thanks! Sorry for slow response. I'm going to look into this today.

**Comment by jnunemaker** [comment]
@coreyaus what server (unicorn, puma, passenger, etc.) and version are you using? Also could you paste any relevant configs for that server?

**Comment by jnunemaker** [comment]
Closing this as stale but happy to research more if we can get more info about your setup. Just let me know. Thanks!

**Comment by diogobeda** [comment]
Hi @jnunemaker, we're facing a similar issue and seeing tons of the same `"Flipper::Middleware::Memoizer appears to be running twice"` logs in prod.
I've debugged the issue a bit and it doesn't really seem like the same request is going through the memoizer twice, but that multiple requests are using the same flipper instance and thus accessing the same [`memoize` flag](https://github.com/jnunemaker/flipper/blob/v0.24.1/lib/flipper/middleware/memoizer.rb#L70). Possibly because they're being run on [the same thread](https://github.com/jnunemaker/flipper/blob/v0.24.1/lib/flipper.rb#L46)?

We're running the following gems:
```
gem "flipper-redis", "~> 0.24.1"
gem "flipper-ui", "~> 0.24.1"
```

Our initializer is pretty straightforward, in that it uses the `Memory` adapter for tests and `Redis` adapter for everything else. with no extra configs.

We're also currently on Rails `6.1.5` and our `rails middleware` output looks like this:
```
use Webpacker::DevServerProxy
use Rack::Cors
use ActionDispatch::HostAuthorization
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use Rack::Rewrite
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use RailsAutoscaleAgent::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rack::Timeout
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use Rollbar::Middleware::Rails::RollbarMiddleware
use ActionDispatch::ActionableExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use ActionDispatch::PermissionsPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Rack::Static
use Rack::Deflater
use OmniAuth::Builder
use Flipper::Middleware::Memoizer
use Rack::Attack
use ScoutApm::Middleware
use ScoutApm::Instant::Middleware
use ActionDispatch::Static
run Coach::Application.routes
```

Let me know if you need more info or help debugging the issue. And thanks for the great work on Flipper 😄

**Comment by bkeepers** [comment]
@diogobeda thanks for letting us know. What web server (unicorn, puma, passenger, etc.) and version are you using?

**Comment by bkeepers** [comment]
@diogobeda can you try this branch and let me know if you're still seeing warnings? https://github.com/jnunemaker/flipper/pull/631

**Comment by diogobeda** [comment]
@bkeepers I still see the warnings on that branch, even when using multiple workers and puma minimum threads set to > 1.
From what I could debug the two requests that are triggering the warning are the action cable WS connection and an ajax request, both are triggered by JS after the page loads.

**Comment by bkeepers** [comment]
@omnibs thanks. Let us know if you figure out how to reproduce it.

**Comment by bkeepers** [comment]
@coreyaus @diogobeda @omnibs Can you do me a favor? Can you try setting `config.allow_concurrency = false` in `config/application.rb` and tell me if the warning goes away? I'm trying to track down if this is an issue with thread safety and I have been unable to duplicate the issue you're seeing. Setting `allow_concurrency = false` will add `Rack::Lock` to the middleware stack, which just wraps each request in a mutex.

**Comment by coreyaus** [comment]
Thanks for looking into this @bkeepers! I've set `config.allow_concurrency = false` in my `test.rb` and can confirm that silences the warnings in my test suite 👍 

Regarding the details you requested earlier (in case they're still relevant), we use `puma 5.6.4` as our app server and we're running `rails 6.1.5` (though we were on v6.1.4.4 at the time of opening this issue). I've also now upgraded to the latest version of `flipper` (`0.25.0`). Let me know if the output of `rails middleware` is still useful and I'll send that through.

In terms of how to recreate this issue, I'm now only seeing it in my test environment under these circumstances (not sure about staging/production environments):

1. Specifically in feature specs, usually Capybara tests with `js: true`
    - In particular when a redirect occurs as part of the spec, e.g. if a user hits an `authorization` block and gets redirected with a flash message (see simple example below)

2. When using an adapter specific to the test environment
    - We use `flipper-active_record` in general but would ideally love to use the Memory adapter or PStore adapter in our specs (to avoid extra database overhead). If we just use the ActiveRecord adapter in our specs this issue disappears
    - The suggested testing config [here](https://www.flippercloud.io/docs/testing#starting-fresh) doesn't work for Capybara tests with `js: true`, as per this discussion: https://github.com/jnunemaker/flipper/issues/261#issuecomment-425691268.
    - Perhaps part of my issue is that I'm not certain the correct steps to configure our test environment to use the Memory adapter without edges cases (and without causing this "running twice" warning). **Do you have any guidance on that (particularly a path that ensures Flipper can be easily used within feature specs)?** Let me know if I should move this question to a separate issue, or if it's useful to share the things I've tried

Thanks again for all your help on this!

**Simple feature spec example where this issue occurs**

```ruby
require "rails_helper"

describe "List all admin users", type: :feature, js: true do
  include Warden::Test::Helpers

  context "as a non-admin" do
    let!(:user) { create(:user) }

    before do
      login_as(user)
    end

    scenario "I cannot view the list of admins" do
      visit admins_path # unauthorized, so a redirect occurs here (e.g. to root_path or similar)
      expect(page).to have_content('You don\'t have permission to access the requested page')
    end
  end
```
