### ISSUE TITLE
Connection pool support

### ISSUE THREAD

**Issue by jose-zenledger** [jnunemaker/flipper#609]
Instead of a new connection for each flipper instance, it would be nice to use connection pooling.

In `config/initializers/redis.rb` we have:
```ruby
$redis = ConnectionPool.new(size: [ENV['REDIS_POOL'].to_i, 1].max) { Redis.new(url: ENV['REDIS_URL'])  }
```
in `config/initializers/flipper.rb` we want to do the following:
```ruby
require 'flipper'
require 'flipper/adapters/redis'
require 'flipper/adapters/active_support_cache_store'

Flipper.configure do |config|
  config.adapter do
    Flipper::Adapters::ActiveSupportCacheStore.new(
      Flipper::Adapters::Redis.new($redis),
      ActiveSupport::Cache::MemoryStore.new,
      expires_in: 10.seconds
    )
  end
end
```

However this fails when using flipper since the methods required for redis are not defined on the connection pool. To access the redis methods you have to do: 
```ruby
$redis.with do |redis|
  # do operations on redis
end
```

Do you think we can add support? I'm happy to work on it

**Comment by jose-zenledger** [comment]
I have this to proxy methods through a connection pool but it is not as optimal as native support:
```ruby
class ConnectionPoolProxy
  def initialize(pool)
    @pool = pool
    @instance_class = pool.with(&:class)
  end

  def method_missing(method_name, *args, &block)
    @pool.with { |instance| instance.public_send(method_name, *args, &block) }
  end

  def respond_to_missing?(method_name, _ = false)
    @instance_class.public_instance_methods.include?(method_name.to_sym)
  end
end
```

**Comment by jnunemaker** [comment]
You can also just make a new flipper adapter. That said, I'm cool with a RedisConnectionPool adapter in flipper. Seems good to me.

**Comment by jnunemaker** [comment]
I'm going to close this issue to keep things tidy but if you have any more questions let me know. Happy to merge a PR for a connection pool adapter.

**Comment by jnunemaker** [comment]
Also if I wasn't clear before, which re-reading I'm wondering if I was, what I meant is we could add RedisConnectionPool adapter in flipper. I'd start by copying the redis one and then adding the necessary `pool.with` blocks around accessing redis.

**Comment by cymen** [comment]
@jnunemaker Did anything ever come of this? It would be really great to have an adapter that use the Redis connection pool.

**Comment by cymen** [comment]
It would also be great to have connection pool support for Redis in the RedisCache adapter.

**Comment by bkeepers** [comment]
@cymen no, but we'd gladly accept a pull request that adds a Redis connection pool adapter.

**Comment by cymen** [comment]
@bkeepers sounds good -- I wrote one and opened a PR here https://github.com/flippercloud/flipper/pull/826

**Comment by j-castellanos** [comment]
@bkeepers I came up with a solution as well https://github.com/flippercloud/flipper/pull/839

**Comment by jeffbax** [comment]
Just wanted to say that I would love to see one of these solutions make it in :)
