### ISSUE TITLE
Custom Memoizable adapter

### ISSUE THREAD

**Issue by douglasgabriel** [jnunemaker/flipper#611]
First of all, I'd like to thank you for such a good open-source project.

# Context
I have 2 applications, one is user-facing and is the one that defines the feature flags, and the other is for developers to update these feature flags state.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/8550928/157904768-21aa1cfa-fa3b-41a6-968a-fe5141105428.png">

The thing is that **Application1** uses [Event Machine](https://github.com/eventmachine/eventmachine) to handle user requests, which makes it a single-thread application and because of that it ends up with a single instance of Flipper for the time that the application lives.

This is a problem in this scenario because `Flipper` uses `Flipper::Adapters::Memoizable` as its internal `memoization` strategy and the way it works makes the in-memory cache not be updated in the **Application1** runtime.

> A simple solution is to just create a new `Flipper` instance every time we change the Event Machine context to handle a different request, but it also would not work for us because we also have an in-memory cache strategy where we define a TTL in order to reduce the pressure on Redis.

# Suggestion
Allow `Flipper` to be created passing a custom `Memoizable` adapter:

```ruby
Flipper.configure do |config|
  config.default do
    Flipper.new(redis_adapter, options, memoize_adapter: my_custom_memoize_adapter)
  end
end
```

**Comment by jnunemaker** [comment]
You are welcome! I had not even considered using Flipper with event machine. Glad you brought this up. 

Really you just want memoization disabled entirely right (since you have your own in memory cache)? Maybe we just allow disabling the automatic wrapping of an adapter with the memoized adapter?

```ruby
Flipper.configure do |config|
  config.default do
    Flipper.new(redis_adapter, memoize: false)
  end
end
```

If memoize was false, then instead of wrapping it, flipper would just use the exact adapter you passed. Then you could write your own stuff and it would be fine. 

The only caveat is the memoization middleware and Flipper.memoize=, Flipper.memoizing? wouldn't work, but that seems fine for you. What do you think?

**Comment by douglasgabriel** [comment]
Yep, it should work as well. Just more context:

I have 2 customized adapters:
1 - For memoization purposes, it extends your `Flipper::Adapters::Memoizable` keeping the `cache` in the `Thread.current`. This is important to us to keep the value of a feature flag consistent during the entire request;

2 - For caching purposes, it also extends your `Flipper::Adapters::Memoizable` but introduces a TTL. This is important to us to not hit Redis every time we receive a new request.

So, with your suggestion I should be able to:

```ruby
redis_adapter = Flipper::Adapters::RedisAdapter.new(redis_connection)
in_memory_cache_adapter = MyMemoryCacheAdapter.new(redis_adapter)
memo_per_thread_adapter = MyMemoPerThreadAdapter.new(in_memory_cache_adapter)

Flipper.configure do |config|
  config.default { Flipper.new(memo_per_thread_adapter, memoize: false) }
end
```

**Comment by jnunemaker** [comment]
I can take a stab when I get time, but feel free to give it a try first if you have any time.

**Comment by douglasgabriel** [comment]
Sure, I have all of it almost ready, I can open a PR with these changes 👍
