### ISSUE TITLE
Dependency conflict - flipper and flipper-ui

### ISSUE THREAD

**Issue by alec-c4** [jnunemaker/flipper#617]
My Gemfile
```
gem "flipper"
gem "flipper-active_record"
gem "flipper-ui"
```

update logs
```
Bundler could not find compatible versions for gem "flipper":
  In snapshot (Gemfile.lock):
    flipper (>= 0.24.0)

  In Gemfile:
    flipper-active_record was resolved to 0.24.0, which depends on
      flipper (~> 0.24.0)

    flipper-ui was resolved to 0.2.0.beta4, which depends on
      flipper (~> 0.7.0.beta1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Please check all dependencies. Also, flipper-ui does conflict with latest omniauth gem.

```
gem "flipper"
gem "flipper-active_record"
gem "flipper-ui", "~> 0.24.0"
```

```
Bundler could not find compatible versions for gem "rack-protection":
  In snapshot (Gemfile.lock):
    rack-protection (>= 2.2.0)

  In Gemfile:
    flipper-ui (~> 0.24.0) was resolved to 0.24.0, which depends on
      rack-protection (< 2.2.0, >= 1.5.3)

    omniauth was resolved to 2.0.4, which depends on
      rack-protection

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by jnunemaker** [comment]
I’m on phone but sounds like rack protection is the issue. Perhaps new
version came out and Omni auth requires that? I can take a peek tonight
or tomorrow. 

On March 29, 2022, David Grevink ***@***.***> wrote:
> My Gemfile
>
> gem "flipper" gem "flipper-active_record" gem "flipper-ui"
> update logs
>
> Bundler could not find compatible versions for gem "flipper": In
> snapshot (Gemfile.lock): flipper (>= 0.24.0) In Gemfile: flipper-
> active_record was resolved to 0.24.0, which depends on flipper (~>
> 0.24.0) flipper-ui was resolved to 0.2.0.beta4, which depends on
> flipper (~> 0.7.0.beta1) Running `bundle update` will rebuild your
> snapshot from scratch, using only the gems in your Gemfile, which may
> resolve the conflict.
> Please check all dependencies. Also, flipper-ui does conflict with
> latest omniauth gem.
>
> gem "flipper" gem "flipper-active_record" gem "flipper-ui", "~>
> 0.24.0"
> Bundler could not find compatible versions for gem "rack-protection":
> In snapshot (Gemfile.lock): rack-protection (>= 2.2.0) In Gemfile:
> flipper-ui (~> 0.24.0) was resolved to 0.24.0, which depends on rack-
> protection (< 2.2.0, >= 1.5.3) omniauth was resolved to 2.0.4, which
> depends on rack-protection Running `bundle update` will rebuild your
> snapshot from scratch, using only the gems in your Gemfile, which may
> resolve the conflict.

—
Reply to this email directly, view it on GitHub
<https://github.com/jnunemaker/flipper/issues/617>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAAB24G43RHMDCHSMCOS23VCOAVVANCNFSM5R73WATQ>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by jnunemaker** [comment]
Looks like this was just a dependency that was too strict. I've made it less strict. Should be released before too long.

**Comment by danmayer** [comment]
yep, just hitting the same dependency issue with `rack-protection`... following for a release that resolves

**Comment by jnunemaker** [comment]
I'll get a new version out tomorrow! Sorry for delay.

**Comment by danmayer** [comment]
Awesome, thanks. No worries, appreciate all you do.
