### ISSUE TITLE
Add Flipper::API module

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#62]
Now that we have Flipper::UI it would be nice to have Flipper::API. Flipper::API would provide the same functionality as the UI but all json responses instead of html/css views. Clients could then be created for chatops/hubot to enable/disable features and all that.

**Comment by digidigo** [comment]
Would this be required to allows an angular app to check whether a feature should be on or off for a user.

**Comment by jnunemaker** [comment]
No, for that I would do whatever you need to on your end. This is so other systems can enable/disable and do other things through an API instead of a web UI. For example, if your company ran https://hubot.github.com/, hubot could talk to the API to turn features on/off and do more. 

For angular, I would just make routes on your own that do so and make angular talk to them.

**Comment by AlexWheeler** [comment]
@jnunemaker is anyone working on this?  I'd be stoked to start and/or contribute if someone has a branch going

**Comment by jnunemaker** [comment]
@AlexWheeler not currently. Go for it!

**Comment by jnunemaker** [comment]
Perhaps start with one or two routes and we can settle on some stuff rather than doing a bunch of work and possibly changing directions? Perhaps GET /features, GET /features/:feature-key, POST /features/:feature-key/boolean?

**Comment by AlexWheeler** [comment]
@jnunemaker sounds great!

**Comment by jnunemaker** [comment]
Created a [project for the api](https://github.com/jnunemaker/flipper/projects/2) and added the notes I could think of that still need to be done. Also tried to track all the completed work for those that are curious.

**Comment by AlexWheeler** [comment]
Closing since this successfully shipped a while back! 🎉
