### ISSUE TITLE
Upgrading from 0.23.0 to 0.23.1 or greater leads to stack level too deep error when calling URI.open

### ISSUE THREAD

**Issue by rsslldnphy** [jnunemaker/flipper#621]
After updating only `flipper` and `flipper-active_record` from 0.22.2 to 0.24.0 in our Rails app, everything that made http requests started throwing stack level too deep errors.

I was able to replicate the error _in our app_ by running `rails c` and then `URI.open 'https://google.com`.

```
Loading staging environment (Rails 6.1.4.6)
irb(main):001:0> URI.open 'https://google.com'
Traceback (most recent call last):
        1: from (irb):1
SystemStackError (stack level too deep)
irb(main):002:0>
```

Some googling turned up [this issue](https://github.com/scoutapp/scout_apm_ruby/issues/404) on `scout_apm` which we also use, along with [this issue](https://github.com/getsentry/sentry-ruby/issues/1427) on `sentry-ruby` (which we also use) which suggests there is some incompatibility between two ways of patching `net/http` - method aliasing and module prepending.

This led me to suspect that something between `flipper` 0.22.2 and 0.24.0 either added or changed a patch of `net/http`. However when I searched [the diff](https://github.com/jnunemaker/flipper/compare/v0.22.2...v0.24.0) for the words `alias` and `prepend`, nothing came up.

At this point I'm a bit stumped. I've created an empty Rails app and am slowly adding in gems one at a time to try to create a simple replication, but have had no luck yet. It doesn't seem to be an incompatibility with scout or sentry. So I thought I would create this issue in case you have an idea of what the change that led to this incompatibility might be and/or any ideas of how to diagnose what the incompatibility is. Depending on who is using what method of patching it may be that it's the other gem that needs fixing, but at this point I don't know which gem that is or how to find out. Any help much appreciated!

**Comment by rsslldnphy** [comment]
have narrowed the issue down to being introduced in the [change between 0.23.0 and 0.23.1](https://github.com/jnunemaker/flipper/compare/v0.23.0...v0.23.1) (and updated the issue title accordingly)

**Comment by jnunemaker** [comment]
@rsslldnphy I'd be shocked if this was somehow flipper. Nothing changed in those versions of consequence to net/http. The only dependency change was relaxing the supported dalli version. Also, flipper doesn't change any core classes in any way. `prepend` is not used (other than in tests) and `alias` (and friends) is only used for flipper things.

Can you maybe show the diff on your gemfile to see if any other gems changed? Or if you have a blank demo app that demonstrates the issue, I can take a look. 

I'm going to close this to keep things clean, but I'm still willing to work with you to prove this is or is not somehow related. If we prove it is, then I'll re-open.

**Comment by rsslldnphy** [comment]
Thanks @jnunemaker, I really appreciate that. I agree, I really can't see how flipper could be responsible for this! I couldn't see anything in the code that looked suspicious and it just generally seemed odd that it would have that effect. However it's the only difference I can see. Here's a complete diff between a working and non working branch:

```diff
diff --git a/Gemfile b/Gemfile
index 6cd12b6f3..be44fea3f 100644
--- a/Gemfile
+++ b/Gemfile
@@ -91,9 +91,9 @@ gem "graphiql-rails"
 gem "graphql-batch", "~> 0.4.3"
 
 # Feature flagging
-gem "flipper", "0.23.0"
-gem "flipper-ui", "0.23.0"
-gem "flipper-active_record", "~> 0.23.0"
+gem "flipper", "0.23.1"
+gem "flipper-ui", "0.23.1"
+gem "flipper-active_record", "~> 0.23.1"
 
 gem "sentry-ruby"
 gem "sentry-rails"
diff --git a/Gemfile.lock b/Gemfile.lock
index dad455eb2..452b1d77a 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -223,13 +223,13 @@ GEM
       concurrent-ruby (~> 1.1)
       websocket-driver (>= 0.6, < 0.8)
     ffi (1.15.5)
-    flipper (0.23.0)
-    flipper-active_record (0.23.0)
+    flipper (0.23.1)
+    flipper-active_record (0.23.1)
       activerecord (>= 4.2, < 8)
-      flipper (~> 0.23.0)
-    flipper-ui (0.23.0)
+      flipper (~> 0.23.1)
+    flipper-ui (0.23.1)
       erubi (>= 1.0.0, < 2.0.0)
-      flipper (~> 0.23.0)
+      flipper (~> 0.23.1)
       rack (>= 1.4, < 3)
       rack-protection (>= 1.5.3, < 2.2.0)
       sanitize (< 7)
@@ -655,9 +655,9 @@ DEPENDENCIES
   encoded_polyline
   factory_bot_rails (>= 6.1.0)
   faker
-  flipper (= 0.23.0)
-  flipper-active_record (~> 0.23.0)
-  flipper-ui (= 0.23.0)
+  flipper (= 0.23.1)
+  flipper-active_record (~> 0.23.1)
+  flipper-ui (= 0.23.1)
   friendly_id (= 5.4.2)
   geokit
   gibbon (~> 3.4)
```

I haven't been able to replicate it with an empty project yet, it's going to take some more time adding gems one by one till I stumble across the clash, whatever it is (if that's what it is). It's possible it could also be some combination of the gems we're using plus the config we're using / the way we're using the gems so this could take some time to track down. Will update this issue when/if i have any luck.

Other possibly relevant information: I also haven't managed to replicate it outside of heroku, despite running with the same environment variables on my macbook. That could mean either a) I'm not running it with exactly the config I think I am or b) it's something that only shows up on Linux (so "a" sounds like the more likely option here).

**Comment by rsslldnphy** [comment]
Update on this, I've narrowed down the issue to this diff:

```diff
diff --git a/lib/flipper/railtie.rb b/lib/flipper/railtie.rb
index 27495318..de19137a 100644
--- a/lib/flipper/railtie.rb
+++ b/lib/flipper/railtie.rb
@@ -25,6 +25,13 @@ module Flipper
       end
     end
 
+    initializer "flipper.log", after: :load_config_initializers do |app|
+      flipper = app.config.flipper
+      if flipper.log && flipper.instrumenter == ActiveSupport::Notifications
+        require "flipper/instrumentation/log_subscriber"
+      end
+    end
+
     initializer "flipper.memoizer" do |app|
       config = app.config.flipper
 
@@ -37,12 +44,6 @@ module Flipper
       end
     end
 
-    initializer "flipper.log" do |app|
-      config = app.config.flipper
-      if config.log && config.instrumenter == ActiveSupport::Notifications
-        require "flipper/instrumentation/log_subscriber"
-      end
-    end
 
   end
 end
```

So it looks like the issue I'm having is as a result of [this commit](https://github.com/jnunemaker/flipper/commit/adbf249bffd53c374a364afe69951c8aba7c3f5f), which in turn was done to fix an issue created by [this pr](https://github.com/jnunemaker/flipper/pull/563).

Still haven't figured out what exactly the issue is yet but it at least narrows it down to something to do with the `LogSubscriber` and the order in which it's initialized. These are innards of Rails I know nothing about, but I'll keep digging.

**Comment by rsslldnphy** [comment]
Just in case we're doing anything weird in our config that might be causing this, here it is (except a bunch of other `Flipper.register` calls that follow exactly the same pattern as the one included here):

```ruby
require 'flipper/adapters/active_record'

Flipper.configure do |config|
  config.default do
    Flipper.new(Flipper::Adapters::ActiveRecord.new)
  end
end

Flipper::UI.configure do |config|
  config.fun = false
end

Flipper.register(:central_admin) do |actor|
  actor.try(:central_admin?)
end
```

**Comment by rsslldnphy** [comment]
(Final?) update: I haven't been able to track down where the incompatibility is, but strongly suspect it's with `scout_apm` due to [this open PR](https://github.com/scoutapp/scout_apm_ruby/pull/402) and [this code](https://github.com/scoutapp/scout_apm_ruby/blob/8d1e330d37b5e2f73170b40a4c1a6836ce857726/lib/scout_apm/instruments/http.rb#L28-L42). My guess would be that when they release a new version that uses `prepend` this problem will go away, so for now I'll leave `flipper` pinned to an older version and try again when the `scout_apm` PR is merged.
