### ISSUE TITLE
Defining config.adapter in an initializer not applied to Flipper instance

### ISSUE THREAD

**Issue by gavin-hinchley** [jnunemaker/flipper#634]
It does not appear that using `config.adapter` in `/config/initializers/flipper.rb` sets the default adapter used by a Flipper instance.

### Repro:

1. Create a Rails initializer via ` /config/initializers` using [the Flipper documentation](https://www.flippercloud.io/docs/adapters/active-support-cache-store) to set ActiveSupportCacheStore in `config.adapter`.

2. Run `bin/rails console` calling `Flipper.adapter`.

3. Observe that the adapter is NOT `ActiveSupportCacheStore`.

![image](https://user-images.githubusercontent.com/91741879/171880212-37353e70-e3c1-43aa-86d7-7b705a8894d7.png)

### Workaround: 

1. Use `config.default` instead to define Flipper instance with adapter directly, eg:
```
Flipper.configure do |config|
  config.default do
    adapter =
      Flipper::Adapters::ActiveSupportCacheStore.new(
        Flipper::Adapters::ActiveRecord.new,
        Rails.cache,
        expires_in: 30.days
      )
    Flipper.new(adapter)
  end
end
```
2. Run `bin/rails console` calling `Flipper.adapter`.

3. Observe `ActiveSupportCacheStore` is set.

**Comment by gavin-hinchley** [comment]
Note our `Gemfile.lock` has these versions:
```
    flipper (0.24.1)
    flipper-active_record (0.24.1)
      activerecord (>= 4.2, < 8)
      flipper (~> 0.24.1)
    flipper-active_support_cache_store (0.24.1)
      activesupport (>= 4.2, < 8)
      flipper (~> 0.24.1)
    flipper-ui (0.24.1)
      erubi (>= 1.0.0, < 2.0.0)
      flipper (~> 0.24.1)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, <= 2.2.0)
      sanitize (< 7)

**Comment by stevecrozz** [comment]
@gavin-hinchley fwiw, I had a similar issue and for me it was because we were (in the course of some performance testing), using flipper and adding features before doing the flipper configuring. So our config.default block was never even being called.

**Comment by jnunemaker** [comment]
@gavin-hinchley any chance that is your issue as well? I'd search uses of Flipper and see if it is possible that any would be invoked prior to initializers being loaded.

**Comment by jnunemaker** [comment]
Closing to keep things tidy but if we can confirm this in a blank app I'll definitely re-open.

**Comment by jnunemaker** [comment]
@bkeepers I tried this on the https://github.com/fewerandfaster/flipper-rails-demo and I'm getting sync adapter (for flipper cloud) instead of cached memory adapter. Any ideas what would cause that? If not I can dig in but wondered if anything would strike you. 

![Screen Shot 2022-07-26 at 10 12 56 AM](https://user-images.githubusercontent.com/235/181027435-91d8dac5-8cc4-42b0-9375-c972b5ff00eb.png)

**Comment by bkeepers** [comment]
I did some digging and think I might have figured out a cause for this issue. See #634 for an explanation and fix

**Comment by jnunemaker** [comment]
I think he means #652.

**Comment by bkeepers** [comment]
Yep, thanks
