### ISSUE TITLE
Disable a feature for a specific actor

### ISSUE THREAD

**Issue by acouprie** [jnunemaker/flipper#649]
Hello,

I got an issue with Flipper.

We use Flipper to turn on or off features for specific customers. First we want to enable globally a feature that is ready to be used in production, and then activate or deactivate it for selected customers.

It seems that it is not possbile to deactivate a feature enabled globally, for exemple I expect the feature to be disabled only for the Organization.first while it is still for the others but it is not : 

```
FLIPPER[:cases].enabled?
=> true

FLIPPER[:cases].enabled? Organization.first
=> true

FLIPPER[:cases].disable Organization.first
=> true

FLIPPER[:cases].enabled? Organization.first
=> true
```

I saw discussion about this [here](https://github.com/jnunemaker/flipper/pull/618) and [here](https://github.com/jnunemaker/flipper/issues/514).

Will this be a feature for Flipper and if yes do you know when ? Do you suggest a workaround ?

Thank you

**Comment by acouprie** [comment]
Ok, I managed a workaround by rewriting the code to never use global FLIPPER (`FLIPPER[:cases].enabled?`). I loop on all orgs and apply the logic I want accordingly.

**Comment by jnunemaker** [comment]
Hi! 

Eventually I would like to add deny to flipper as well but we have a few things to get shipped before that so I don't have a timeframe for you right now.

**Comment by bkeepers** [comment]
@acouprie another approach is to use a [group](https://www.flippercloud.io/docs/features#enablement-group) to define everyone who _is_ allowed access.

```ruby
Flipper.register(:generally_available) do |user|
  !user.banned?
end
```

```ruby
Flipper.enable_group(:cases, :generally_available)
