### ISSUE TITLE
Memoization has major performance edge cases

### ISSUE THREAD

**Issue by bessey** [jnunemaker/flipper#650]
I have just finished debugging an issue plaguing our staging environment where we have found that over time all requests get continually slower until the database is reset back to a prod clone. After some major digging I found that Flipper's [Preloading and Memoization](https://www.flippercloud.io/docs/optimization) are the culprit. 

These docs:

> Flipper will preload all features before each request by default, which is recommended if you have a limited number of features (< 100?) and they are used on most requests. 

imply that this scales with the number of _features_ but it also scales with the number of _gates_ because all gates are memoized too. In this environment we have smoke tests constantly adding new actors with flags explicitly enabled for them. As a result despite having < 10 features, the preloader is instantiating >1k rows for each actor explicitly enabled. The SQL to do this may be fast but instantiating that many ruby objects is most certainly not. We saw latency increases just from Flipper of >100ms per request.

These docs:

> If you have a lot of features, but only a few are used on most requests, you may want to customize preloading

imply that only those with many features need customise this.

I think the docs could clarify that preloading is only suitable if ALL of the following are true:
- You have <100 features
- Most of your requests depend on >3 features
- You have <100 actors specified _summed across all features_

Numbers are finger wavey of course, but I'd say this is about the point where the overhead of doing multiple SQL calls is outweighed by the overhead of instantiating large amounts of DB data in memory.

Lastly the docs might also clarify that due to all adapters -memoized or not- fetching all gates for a given feature, Flipper is not designed for use cases with large numbers of actors.

Hope that is helpful. Love the gem otherwise!

**Comment by jnunemaker** [comment]
> I think the docs could clarify that preloading is only suitable if ALL of the following are true:

Yep, more data will affect things. Its an optimization that is good at the beginning but definitely has its limits. Thanks for suggesting. I'm updating the docs.

> Lastly the docs might also clarify that due to all adapters -memoized or not- fetching all gates for a given feature, Flipper is not designed for use cases with large numbers of actors.

We do have a note at the bottom of [here](http://localhost:3000/docs/features#enablement-actor). It use to be a bit more prominent in a caveats page but when we moved docs we must have de-emphasized it. 

> Hope that is helpful. Love the gem otherwise!

Helpful. 😄 Thanks. [Docs updated](https://www.flippercloud.io/docs/optimization).
