### ISSUE TITLE
Flipper-ui locked to older version of rack-protection  <= 2.2.0

### ISSUE THREAD

**Issue by Bandes** [jnunemaker/flipper#651]
Could[ this dependency](https://github.com/jnunemaker/flipper/blob/master/flipper-ui.gemspec#L24) on rack-protection <= 2.2.0 be relaxed to allow current versions of rack-protection?

We use rack-protection and try to keep it current, so at the moment flipper-ui is not usable for us.

**Comment by jnunemaker** [comment]
I'm sure it can. Any suggestions on version?

**Comment by Bandes** [comment]
I think the latest is 2.2.2, maybe lock it at 2.3? (I'm not a gem developer myself so I don't know the intricacies of choosing dependency versions, so I may be off-base, but that seems like it might make sense...)

**Comment by jnunemaker** [comment]
Closed by f4a41c541ccf14c535a61c6bc6fe7eeabbfc7e71
