### ISSUE TITLE
The UI is incredibly easy to misuse

### ISSUE THREAD

**Issue by jesslark** [jnunemaker/flipper#654]
The user interface when adding an actor provides a bad experience. The "add actor" button is subtle, looking more like a label, and the "fully enable" button is huge and brightly colored. 

It would be a better experience if:
- "add actor" button was bigger and more colorful
- "fully enable" had a confirmation dialog

<img width="568" alt="Screen Shot 2022-08-12 at 2 12 51 PM" src="https://user-images.githubusercontent.com/17681614/184445895-fdff91bd-f897-4d99-9831-c58bca883f5b.png">

**Comment by jnunemaker** [comment]
I'm open to PRs for this. I'd probably make confirm for enable an option, not the default, or at least have an option to disable it. That would be added in UI configuration code. Its probably easy to add as I think there is a way to do similar for disable. 

For the button, using primary color would be fine. If making it larger, you'd probably want to make the text field similarly larger so it doesn't look smaller than the button.

**Comment by jnunemaker** [comment]
Closing this to keep things tidy but definitely open to PRs on this.
