### ISSUE TITLE
Memoization is turned off for specific Rails controller

### ISSUE THREAD

**Issue by ilvez** [jnunemaker/flipper#663]
### Context
Flipper version: 0.25.2. Gems in use: `flipper`, `flipper-active_record`, `flipper-ui`.
Rails version: 7.0.3.1
Ruby: 3.1

We are using `Flipper::Adapters::ActiveRecord` adapter and configuration is:
```
    config.flipper.preload = false
    config.flipper.memoize = true # This actually default I understand..
```

### Issue
Generally memoization is working, but when processing reaches to our `ErrorsController` it is turned off before controller code will start to run. This causes lots of N+1s when `Flipper.enabled?` is called. We use this ErrorsController to show custom errors page. I looked up how others have defined custom error pages and this use-case matches quite exactly how we are doing it: https://web-crunch.com/posts/custom-error-page-ruby-on-rails . So this is route that causes issue:
```
  match '/404', to: 'errors#not_found', via: :all
```

There is nothing special about controller itself, but I'm suspecting some middleware logic is not working correctly for this specific use case. I can reproduce the issue by accessing some non-existing route.

This is the code that triggers memoization on/off in `lib/flipper/middleware/memoizer.rb`. I debugged both normal and problematic calls down to this particular code. If I comment out ensure block `flipper.memoize = false` then memoization works for `errors#not_found` as well.

```ruby
      def memoized_call(env)
        reset_on_body_close = false
        flipper = env.fetch(@env_key) { Flipper }

        # Already memoizing. This instance does not need to do anything.
        if flipper.memoizing?
          warn "Flipper::Middleware::Memoizer appears to be running twice. Read how to resolve this at https://github.com/jnunemaker/flipper/pull/523"
          return @app.call(env)
        end

        flipper.memoize = true

        case @opts[:preload]
        when true then flipper.preload_all
        when Array then flipper.preload(@opts[:preload])
        end

        @app.call(env)
      ensure
        flipper.memoize = false if flipper # <- If this is removed, everything works for ErrorsController
      end
```

I'm currently not sure whether my code is doing something funny/hacky to trigger this situation or is there actual bug. And I really don't understand why `flipper.memoize = false` needs to be run at all.

Happy to provide further details.

**Comment by ilvez** [comment]
I also noticed this PR draft open, but it hasn't been worked on few months. Quite curious if it would help against my issue.

https://github.com/jnunemaker/flipper/pull/638

**Comment by bkeepers** [comment]
By default, the [Flipper memoizer is appended to the Rails middleware stack](https://github.com/jnunemaker/flipper/blob/1d5143e8d847e36b86ca563adc07c5c300c626a5/lib/flipper/railtie.rb#L39-L44), so it's going to be pretty low in the stack. You can try inserting the memoizer middleware before `ActionDispatch::ShowExceptions` and let me know how it works for you:

```ruby
# config/initializers/flipper.rb

Rails.application.configure do
  # Disable the default memoize configuration
  config.flipper.memoize = false
  
  # Manually insert memoizer before Rails' exception handler
  config.middleware.insert_before(
    ActionDispatch::ShowExceptions,
    Flipper::Middleware::Memoizer,
    { preload: true }
  ) 
end
```

We could probably move it higher in the stack, but we'll want to carefully consider the ramifications for that.

**Comment by ilvez** [comment]
Thank you so much! It worked as expected. Only thing I changed was to remove `{ preload: true }`, since we don't want it. Good to know that it can be configured like this though.

**Comment by jnunemaker** [comment]
@ilvez great! I'll close this issue to keep things tidy but if you have any more questions, let us know.
