### ISSUE TITLE
Add Flipper::Feature#disabled?

### ISSUE THREAD

**Issue by StoryparkNick** [jnunemaker/flipper#664]
Hi there,

Love the library - one small thing I'd love to see changed is the addition of a `disabled?` method alongside `enabled?`.

Sometimes I have to write code like this:

```rb
unless Flipper[:feature_name].enabled?(thing) do
  # do something when feature is disabled
end
```

I would much prefer to write this:

```rb
if Flipper[:feature_name].disabled?(thing) do
  # do something when feature is disabled
end
```

Is this a feature you'd be willing to accept? I'm happy to make a PR if so.

Thanks :)

**Comment by jnunemaker** [comment]
@StoryparkNick hi! This has come up a few times before. Check out https://github.com/jnunemaker/flipper/pull/494#issuecomment-823455391 first and https://github.com/jnunemaker/flipper/issues/514 if you are still curious. 

Let me know what you think about either of those.

**Comment by StoryparkNick** [comment]
Thanks for that context @jnunemaker, I can see why having a `#disabled?` method isn't as easy of a win as I thought.

For what it's worth, I'd chuck my hat in the ring for `#not_enabled?`, but I can always monkey patch my local version.
