### ISSUE TITLE
Descriptions for Flags

### ISSUE THREAD

**Issue by bagelbits** [jnunemaker/flipper#668]
Add editable `description` field to Flags.

**Comment by jnunemaker** [comment]
This is possible. See descriptions_source block. You can make that block query a database or a static file in your repo, whatever you like. 

https://github.com/jnunemaker/flipper/blob/ce622d4ab108cc5c3e6de9a2499c931dc3064c51/examples/ui/basic.ru#L31-L42

https://github.com/jnunemaker/flipper/blob/95d8434db13aa351fd477667e556839b3931dbce/lib/flipper/ui/configuration.rb#L38-L41

**Comment by jnunemaker** [comment]
@bagelbits let me know if you have any issues with it.
