### ISSUE TITLE
Multi-variate flag values

### ISSUE THREAD

**Issue by rabidaudio** [jnunemaker/flipper#698]
It seems like flipper only supports boolean flags, which is the most common use-case. But for experimentation, such as A/B(/C) testing, having additional values beyond simply `true` and `false`. This is typically done by storing string values.

I'm considering hacking a custom adapter or middleware or something to support this in our project, but if there's some interest in supporting it I'd be happy to open a PR.

**Comment by jnunemaker** [comment]
I don't really use A/B testing at all so I'm not sure I'm the best to maintain it or that Flipper should. But I'd be _very_ curious to see what you come up. Seeing is always easier to react to.
