### ISSUE TITLE
undefined method `name' for module `Kernel'

### ISSUE THREAD

**Issue by KevinColemanInc** [jnunemaker/flipper#70]
When I go to /flipper in flipper-ui I get this stack trace:

    NameError - undefined method `name' for module `Kernel':
      /Users/kcoleman/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/delegate.rb:89:in `method_missing'
      flipper (0.7.0.beta6) lib/flipper/adapters/instrumented.rb:32:in `features'
      /Users/kcoleman/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/delegate.rb:87:in `method_missing'
      flipper (0.7.0.beta6) lib/flipper/adapters/memoizable.rb:25:in `block in features'
      flipper (0.7.0.beta6) lib/flipper/adapters/memoizable.rb:24:in `features'
      flipper (0.7.0.beta6) lib/flipper/dsl.rb:230:in `features'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/actions/features.rb:14:in `get'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/action.rb:67:in `block in run'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/action.rb:67:in `run'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/action.rb:27:in `run'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/middleware.rb:70:in `call!'
      flipper-ui (0.7.0.beta6) lib/flipper/ui/middleware.rb:60:in `call'
      flipper (0.7.0.beta6) lib/flipper/middleware/memoizer.rb:40:in `call'
      rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
      rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
      rack-protection (1.5.3) lib/rack/protection/xss_header.rb:18:in `call'
      rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
      rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
      rack-protection (1.5.3) lib/rack/protection/path_traversal.rb:16:in `call'
      rack-protection (1.5.3) lib/rack/protection/json_csrf.rb:18:in `call'
      rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
      rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
      rack-protection (1.5.3) lib/rack/protection/frame_options.rb:31:in `call'
      rack (1.6.0) lib/rack/builder.rb:153:in `call'
      actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
      actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
      actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      rack (1.6.0) lib/rack/etag.rb:24:in `call'
      rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
      rack (1.6.0) lib/rack/head.rb:13:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
      rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
      activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
      activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
      activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
      better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
      web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
      quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
      actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
      rack (1.6.0) lib/rack/runtime.rb:18:in `call'
      activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      rack (1.6.0) lib/rack/lock.rb:17:in `call'
      actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
      rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
      sentry-raven (0.12.3) lib/raven/integrations/rack.rb:61:in `call'
      rack-cors (0.3.1) lib/rack/cors.rb:72:in `call'
      railties (4.2.0) lib/rails/engine.rb:518:in `call'
      railties (4.2.0) lib/rails/application.rb:164:in `call'
      rack (1.6.0) lib/rack/lock.rb:17:in `call'
      rack (1.6.0) lib/rack/content_length.rb:15:in `call'
      rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
      /Users/kcoleman/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
      /Users/kcoleman/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
      /Users/kcoleman/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'a

**Comment by rsanheim** [comment]
What version of flipper and Ruby are you using?

**Comment by jnunemaker** [comment]
What adapter are you using? The backtrace goes to a name method call for adapter. Are you using a homegrown one?

**Comment by KevinColemanInc** [comment]
@jnunemaker I think the issue was my gems were on different versions.  This change in my gem file fixed it:

    -gem 'flipper-ui'
    -gem 'flipper-redis'
    +gem 'flipper-ui', '~> 0.7.0.beta6'
    +gem 'flipper-redis', '~> 0.7.0.beta6'
