### ISSUE TITLE
Groups don't intersect?

### ISSUE THREAD

**Issue by pjaspers** [jnunemaker/flipper#71]
If an actor belongs to two groups, once it's enabled for one group it's automatically enabled for that user even if the second group defines it as `disabled`.

This might be the desired output, but it felt counterintuitive to me.

``` ruby
# Contrived example, but bear with me.
Flipper.register(:large_group) do |actor|
  actor.part_of_large_group?
end

Flipper.register(:subset_of_large_group) do |actor|
  actor.part_of_small_group? 
end

$flipper[:can_do].enable_group :large_group
$flipper[:can_do].disable_group :subset_of_large_group

$flipper[:can_do].enabled? user_in_subset # => true
```

Is this the desired behavior?

**Comment by jnunemaker** [comment]
> This might be the desired output, but it felt counterintuitive to me.

This is the desired behavior. Flipper is made to be enabled as soon as any of the gates return true. I can see how you could have expected the opposite. Maybe disable group isn't quite named correctly. The goal of disable is simply to clear the enable. If whatever it is has not been enabled, then it effectively does nothing. Does that make sense? Perhaps I should mention this in the readme or something.

**Comment by pjaspers** [comment]
That makes sense. Wording is indeed a bit weird.

**Comment by jnunemaker** [comment]
Out of curiousity, are you using flipper in production? Anything you can share about how you are using it? Using a core adapter or a custom one? Its ok if you don't want to answer, I just like to ask people to help get a sense of how people are using flipper.

**Comment by jnunemaker** [comment]
Add a caveats markdown file: https://github.com/jnunemaker/flipper/blob/master/docs/Caveats.md. Hopefully that can serve as an aid to this type of question in the future.

**Comment by pjaspers** [comment]
Great!

We're starting to use it in production, with the redis adapter. For now using it with just two groups and a couple of features.
