### ISSUE TITLE
Is it possible to rename a flipper feature?

### ISSUE THREAD

**Issue by lyricsboy** [jnunemaker/flipper#713]
Hello! We have a Flipper instance, backed by Redis, where we have set up a few dozen features to support a migration from one app's Flipper to another's. Some of these features have actor or group-level configuration specified. Unfortunately, they were created using the "wrong" naming convention, and we'd like to rename them before we put them into service. The features are not currently referenced directly in any code.

Is it possible to do this somehow? Safely-ish? Could/should we dig into the Redis store and modify them?

We can do it manually by creating features with the correct names, and deleting the incorrectly-named features... but that would be somewhat tedious.

Thanks for any tips!

**Comment by jnunemaker** [comment]
If they are unused you can definitely look at the redis store and rename them there. 

I can add feature rename support. Didn’t even think about that. I’ll make an issue and work on it when I have time. 

For you, I’d just check out how the redis adapter stores them. Likely you can rename them in the set of all features and the individual keys that store the gate data and you should be good. 

Let me know if you hit any problems or need help and I can try to add an example.

**Comment by KevinBerthier** [comment]
For those who have Postgres adapter, here is the migration to apply : 
```rb
    reversible do |dir|
      dir.up do
        execute "UPDATE flipper_features SET key = 'new_tag' WHERE key = 'old_tag'"
        execute "UPDATE flipper_gates SET feature_key = 'new_tag' WHERE feature_key = 'old_tag'"
      end
      dir.down do
        execute "UPDATE flipper_features SET key = 'old_tag' WHERE key = 'new_tag'"
        execute "UPDATE flipper_gates SET feature_key = 'old_tag' WHERE feature_key = 'new_tag'"
      end
    end
```
