### ISSUE TITLE
Breaking change in 0.28.0 - Rename of thing to actor

### ISSUE THREAD

**Issue by Geesu** [jnunemaker/flipper#716]
We went live with version 0.28.0 and unfortunately broke production for any pages which were using flipper groups. Due to this change:

https://github.com/jnunemaker/flipper/commit/3e4b5893#diff-aae41bf03cc259893c739aa855e16892b7c2a87608cc3c8e97908c2e6e08eeb1R9

We were registering a group in our initializer:

```
Flipper.register(:our_group) do |actor|
  actor.thing.is_a?(OurClassName)
end
```

We've fixed this by renaming but should we have expected this change? Given we are passed a `Flipper::Types::Actor` object to our block we wouldn't have expected public methods to change in a minor release.

**Comment by jnunemaker** [comment]
@Geesu sorry to hear that. Our goal is definitely no outages. Pre-1.0 we consider any minor change a potential breaking change. I tried to note that in the changelog by saying "This likely breaks things for anyone using Flipper internal classes related to actors" but from what you are saying that wasn't clear enough. 

I updated the changelog to this:
https://github.com/jnunemaker/flipper/commit/d33052c57b0666b0a3b2e7fd44ad1499d5af5547

Does that seem more clear?

**Comment by jnunemaker** [comment]
Also worth noting that we are going to go 1.0 here very shortly and then bump major for stuff like this as a means of communicating more effectively.

**Comment by Geesu** [comment]
> @Geesu sorry to hear that. Our goal is definitely no outages. Pre-1.0 we consider any minor change a potential breaking change. I tried to note that in the changelog by saying "This likely breaks things for anyone using Flipper internal classes related to actors" but from what you are saying that wasn't clear enough.
> 
> I updated the changelog to [this](https://github.com/jnunemaker/flipper/commit/d33052c57b0666b0a3b2e7fd44ad1499d5af5547). Does that seem more clear? If not, any tips on improving that?

Yes that is great thanks!

The scary part is that code was in an initializer, so our tests couldn't exercise it. We've also moved it to a service object which is tested using the `Actor` object directly so it would be caught in the future.
