### ISSUE TITLE
Can't delete flags due to redis-namespace bug

### ISSUE THREAD

**Issue by jdelStrother** [jnunemaker/flipper#719]
I use Redis::Namespace to keep my flipper flags separate from the rest of my redis database, but this is currently introducing a bug where I can't remove any feature flags - it tries to remove the `flagname` key from redis rather than `flipper:flagname`.

This is due to a bug in redis-namespace - https://github.com/resque/redis-namespace/pull/223 - rather than being anything that Flipper is doing wrong, but thought it was worth highlighting here for anyone else running into the same problem.

---

As an aside, Flipper is the only reason we use redis-namespace. Would you be supportive of a PR that adds a `key_prefix` option into flipper-redis, so we can drop redis-namespace?

**Comment by jnunemaker** [comment]
I'd be open to this.

**Comment by jnunemaker** [comment]
redis namespace is no longer needed thanks to #722.
