### ISSUE TITLE
Unflipping a Single Actor When Flipped as a Group

### ISSUE THREAD

**Issue by marcusleemitchell** [jnunemaker/flipper#72]
I'm not sure if this is by design but if I flip a group, I would like to be able to unflip individual actors contained in the group.

Is this possible?

**Comment by jnunemaker** [comment]
See caveat number 2. https://github.com/jnunemaker/flipper/blob/7c23e43f27749b1dd47112775b942e35cbc88e02/docs/Caveats.md. It is by design. disable only clears, it does not explicitly disable. Make sense? Happy to chat more about your usecase. Perhaps there is something flipper is missing, but currently I'm sticking to disable just clearing.

**Comment by marcusleemitchell** [comment]
Hey John.

I really appreciate the reply.
If I may explain the use case we have and why this idea arose, maybe it's
something that could be included.

So, we have ~20k Accounts, over 4 types (roughly speaking).
At first we were migrating underlying data and then flipping the individual
Account. This gave us the ability to test a sample and then flip the
remainder.
This started to get ugly around the 2k mark.
So now we have 2 groups per type. One with the first 10 of each type, the
second with the remainder. We can flip the 10, test then flip the remainder.

What we've lost is the ability to unflip a  single account contained in a
group.

Maybe a second feature key to hold exclusions from groups. Explicitly
disabled actors that override the 'enabled' state from any group in which
they might be included.

Just thinking out loud.

It's a great gem, really helped us roll a large piece of work out.

**Comment by jnunemaker** [comment]
> At first we were migrating underlying data and then flipping the individual
Account. 

Any particular reason you aren't using the percentage of actors gate to migrate the data for accounts? If you increase the percentage, accounts would be enabled and if you decrease those same accounts would then be disabled. You don't know the exact accounts without doing an enable check, but you get control for long rollouts.

**Comment by marcusleemitchell** [comment]
Good point. We wanted to know the accounts being flipped to migrate their
data and communicate to users (in some but not all cases)
If enabling group or percents could give me back Ids in those group (or
flipped percentage)

Marcus

**Comment by jnunemaker** [comment]
@marcusleemitchell here is an example that shows how to determine if a collection of users or an individual user is enabled for the percentage of actors check: https://github.com/jnunemaker/flipper/blob/825221a2f5af4e16ec46be2660aa7e3c5124c8e3/examples/percentage_of_actors_enabled_check.rb

The key is to add the correct percentage enabled value and feature name.
