### ISSUE TITLE
Bundling bootstrap and poppler with the library ?

### ISSUE THREAD

**Issue by dhruvCW** [jnunemaker/flipper#730]
I am prototyping flipper for my organisation, we are running into a bit of a issue with our Content Security Policy. Would it be possible for the library to bundle poppler, bootstrap and jquery ? This will then not require us to extend our CSP. Our CSP is configured site wide and we currently are not in a position to setup per route CSP right now, if the dependencies are bundled we won't need to extend the CSP.

**Comment by jnunemaker** [comment]
@bkeepers would know more about this. Seems ok if it’s easy. We’d just need a middleware to serve static files, right?

**Comment by dhruvCW** [comment]
I think the existing `UI::Action::File` module can be utilized. Infact just dropping the files under the right public folder should be enough. If this is something that the project would like to do, I can create a PR with the suggested changes.

**Comment by dhruvCW** [comment]
Would a new release containing this change be created soon ?
