### ISSUE TITLE
Assets not found in 0.28.1

### ISSUE THREAD

**Issue by kwent** [jnunemaker/flipper#741]
Hi,

When used with a custom domain as `https//flippers.acme.com` assets are not found at the specified path anymore. What is the best way to handle this now ?

![Screenshot 2023-07-17 at 6 52 21 PM](https://github.com/jnunemaker/flipper/assets/879780/a2e85170-b7f4-467b-a7ab-bdb84afa503d)

![Screenshot 2023-07-17 at 6 46 26 PM](https://github.com/jnunemaker/flipper/assets/879780/14fbc0d4-245c-4f0f-b371-8bfd7c373aa2)

Regards

**Comment by bkeepers** [comment]
@kwent Thanks for reporting it. Should be fixed in 0.28.2.

**Comment by kwent** [comment]
Works well now ! Thank you !
