### ISSUE TITLE
Flipper UI upgrade to 0.28.1 breaks UI

### ISSUE THREAD

**Issue by doutatsu** [jnunemaker/flipper#744]
Upgrading to the latest version completely broke the UI. Reverting back
| 0.28.0 | 0.28.1 |
| --- | --- |
| <img width="633" alt="image" src="https://github.com/jnunemaker/flipper/assets/4270980/d9c890f9-0c96-4aad-b8ab-21f458d11ccc"> | <img width="419" alt="image" src="https://github.com/jnunemaker/flipper/assets/4270980/636e0ac9-4999-49ae-9899-36e65f7342f4"> |

**Comment by bkeepers** [comment]
Fixed in 0.28.2 cc https://github.com/jnunemaker/flipper/pull/742

**Comment by doutatsu** [comment]
Ah my bad - dependabot didn't get me the latest version 😠

**Comment by bkeepers** [comment]
No worries. Thanks for reporting it anyway. We would rather get duplicate reports than none. 😎
