### ISSUE TITLE
Inconsistent API results

### ISSUE THREAD

**Issue by nhorton** [jnunemaker/flipper#747]
While debugging another issue, I found the following behavior. This is using the ActiveRecord adapter.

```
3.1.3 :034 > Flipper.features
 {#<Flipper::Feature:463240 name="new_note_from_ai", state=:on, enabled_gate_names=[:boolean], adapter=:memoizable>,
  #<Flipper::Feature:463380 name="sibling_chart", state=:on, enabled_gate_names=[:boolean, :actor], adapter=:memoizable>,
  #<Flipper::Feature:463440 name="foo", state=:off, enabled_gate_names=[], adapter=:memoizable>}> 
3.1.3 :035 > Flipper.feature "sibling_charts"
 => #<Flipper::Feature:753520 name="sibling_charts", state=:off, enabled_gate_names=[], adapter=:memoizable>                                                 
```
Note the different result for when requesting one feature or enumerating all. This feels very related to a behavior we were debugging today where settings in the flipper UI would seem to be lost immediately upon page refresh. Note that we have not turned on any non-default caching in Flipper or ActiveRecord.

**Comment by jnunemaker** [comment]
One is singular and one is plural. Can you check singular of both or plural of both?
