### ISSUE TITLE
Best practices with Rails?

### ISSUE THREAD

**Issue by ideasasylum** [jnunemaker/flipper#83]
Flipper looks great, very flexible and with a good selection of adapters. But with great choice comes… great confusion?

## Rails setup

The DSL example in the README is ok but it could do with some suggested best practices in Rails.

- Put the flipper init code in a initializer?
- use a Flipper global variable? Any concerns when using multi-threaded servers like Puma?
- I'd probably wrap access to `$flipper` in helper method anyway. Perhaps it makes more sense to do the initialization there to avoid the global variable? 

I'd love to hear how others actually use Flipper in Rails.

## Adapter Selection

Is there any guidance we could offer on which adapters to choose? For example, I'm guessing the selection process goes like:

1. if you use redis already, use flipper-redis
2. if you don't have redis, use one of the activerecord adapters as appropriate
3. pstore for single-server environments (i.e., not Heroku?)
4. memory adapter for tests
5. Mongo/Cassandra for special cases where you already have this dependancy

Also, I'm not sure of the maturity for these adapters so maybe that also plays a factor. And is there a performance consideration?

## Help?

I'm just setting up Flipper so I don't have the answers myself right now but I'll happily write a PR on the docs when I figure it out. Help me?

**Comment by jnunemaker** [comment]
For a Rails 3x app, I added this to config/initializers/flipper.rb:

```ruby
require "flipper"
require "flipper_record" # custom adapter i made, you can use your own or redis or whatever

module MyApplication
  def self.flipper
    @flipper ||= Flipper.new(FlipperRecord.new, {
      instrumenter: ActiveSupport::Notifications,
    })
  end

  # for overriding with memory adapter in tests
  def self.flipper=(flipper)
    @flipper = flipper
  end
end

require "flipper/instrumentation/statsd"
Flipper::Instrumentation::StatsdSubscriber.client = MyApplication.stats

if Rails.env.development?
  require "flipper/instrumentation/log_subscriber"
end
```

I added this to config/routes.rb for flipper-ui:

```ruby
  flipper_app = Flipper::UI.app(->() { MyApplication.flipper }, {
    secret: MyApplication::Application.config.secret_token
  })

  # custom constraint I made that verifies authenticated user and authorized as admin (constraint is optional but not really... :))
  mount flipper_app => "/admin/flipper",
    constraints: AdminAuthenticatedConstraint.new 
```

I added this to config/application.rb in the config block:

```ruby
require "flipper/middleware/memoizer"
config.middleware.use Flipper::Middleware::Memoizer, lambda { SpeakerDeck.flipper }
```

Rails 4 is basically the same, but they have custom config now, so you could use that instead of using the memoized method in MyApplication module. I would never use a global variable. I should update docs if they show that anywhere.

As far as adapters:

1. yeah
2. yeah
3. honestly I just use it locally when I want it to persist across process restarts (ie: flipper-ui example in repo)
4. yeah
5. yeah

As far as maturity, the ones maintained in this repo are production ready. Adapters are designed for bulk where practical and if used with the memoizing middleware, are pretty performant. 

These are all great questions. Let me know if I can answer anything else. Closing the issue, but happy to help more.

**Comment by jnunemaker** [comment]
The lambda above for the memoizer middleware is so that it gets lazy loaded on first invocation.

**Comment by nruth** [comment]
It'd be great to get this knowledge into the readme. I guess I'm abnormal in looking at closed pull requests for docs :) 

Could we reopen this until there's a patch, or better to just make a PR with what you wrote above pushed into the readme? Some things will be adapter specific (e.g. handling threading for redis is quite different to the AR adapters).

**Comment by nruth** [comment]
> I would never use a global variable. I should update docs if they show that anywhere.

There's a global in the [docs for flipper-ui](https://github.com/jnunemaker/flipper/tree/master/docs/ui) under Usage > Rails.

**Comment by andyw8** [comment]
Here's some notes about how I configured this in a Rails 5 app, might be useful to others. I'm using Flipper with [Clearance](https://github.com/thoughtbot/clearance/).

```ruby
# config/environment.rb
Rails.application.configure do
  adapter = Flipper::Adapters::ActiveRecord.new
  config.flipper = Flipper.new(adapter)
end
```

```ruby
# app/helpers/flipper_helper.rb
module FlipperHelper
  def feature_enabled?(feature_name, actor = current_user)
    Rails.configuration.flipper[feature_name].enabled?(actor)
  end
end
```

```ruby
# config/routes.rb
mount Flipper::UI.app(-> { Rails.configuration.flipper }) => "/flipper", constraints: CanAccessFlipperUi
```

```ruby
# app/models/can_access_flipper_ui.rb
class CanAccessFlipperUi
  def self.matches?(request)
    return false unless (clearance = request.env[:clearance])

    clearance.current_user.admin?
  end
end
```
