### ISSUE TITLE
1/3 of requests are without an enabled feature

### ISSUE THREAD

**Issue by krtschmr** [jnunemaker/flipper#84]
Using flipper v 0.70

application_controller

     helper_method :feature_enabled?
     def feature_enabled?(feature_name)
        $flipper[feature_name].enabled?(current_user)
      end

in template just ask for

    if feature_enabled? :chatting

the feature was enabled for all via ui

around every third request, the features is disabled. we are using 3 applicationserver, but all are having a good connection to redis.

known bug?

**Comment by jnunemaker** [comment]
Definitely not a known bug. I can't really debug without more information. Could you create a script with the same data seeded for redis that shows the issue? How is flipper configured? I really can't help without more info. Feel free to provide it here and I'll re-open if we figure anything out.
