### ISSUE TITLE
Getting enabled features based on user

### ISSUE THREAD

**Issue by arashm** [jnunemaker/flipper#86]
Is there anyway I could do something like this?:

```ruby
flipper.features(current_user)
# => [:stats, :analytic]
```

or

```ruby
current_user.enabled_features
# => [:stats, :analytic]
```

Is it even possible for the GEM to have such feature?

**Comment by jnunemaker** [comment]
@arashm Added a new example that shows how to get features enabled for an actor. https://github.com/jnunemaker/flipper/blob/a5d92ac63332582bc4cbafd8c1a9458e2611024a/examples/enabled_for_actor.rb
