### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by dmitrypol** [jnunemaker/flipper#90]
Thank you for creating such a valuable gem.  I see that there is a support for Mongo generic Ruby driver.  Is there a way to make Flipper work with Mongoid?  Especially 4x version since it still uses the previous Moped driver vs Mongoid 5 (which uses Mongo Ruby driver)

**Comment by jnunemaker** [comment]
Yes, there definitely is. You can easily create an adapter of your own for any data store. The docs are here: https://github.com/jnunemaker/flipper/blob/9ea8a7df5aad222bd3332f09c082071a1898c835/docs/Adapters.md. I'm not interested in personally supporting a mongoid adapter, but you can create your own gem or even just an adapter for only your application. I'd be happy to link to it if you do make one as a gem.

**Comment by phstc** [comment]
Just for the reference for those using (newer) versions of Mongoid that uses `mongo`:

```ruby
Flipper.configure do |config|
  config.default do
    collection = Mongoid.default_client['flipper']
    adapter = Flipper::Adapters::Mongo.new(collection)
    Flipper.new(adapter)
  end
end
```

**Comment by derekclee** [comment]
I ended up creating a mongoid model.

```
class FlipperGate
  include Mongoid::Document

  store_in collection: "flipper"

  def self.flipper
    adapter = Flipper::Adapters::Mongo.new(collection)
    Flipper.new(adapter)
  end
end
```

**Comment by jclusso** [comment]
> Just for the reference for those using `mongoid >= 5.0.0`
> 
> ```ruby
> Flipper.configure do |config|
>   config.default do
>     collection = Mongoid.default_client['flipper']
>     adapter = Flipper::Adapters::Mongo.new(collection)
>     Flipper.new(adapter)
>   end
> end
> ```

This would be great to have in the readme @jnunemaker.
