### ISSUE TITLE
Add core memcache adapter

### ISSUE THREAD

**Issue by jnunemaker** [jnunemaker/flipper#96]

**Comment by nruth** [comment]
Would this provide data storage in memcached (as opposed to redis, active_record, etc), or a way to cache lookups across requests?

**Comment by jnunemaker** [comment]
This would wrap another adapter and purely be a cache. We do this for github.com. It would be something similar to the memoize adapter, but for memcache.

**Comment by nruth** [comment]
That would be really cool to have!

I've been thinking about trying something like that for an app we've added flipper active_record to. It seems like different gates and "things" could have different cache configurations (e.g. expiry) but I'm not sure if it'd be useful in practice. 

Seeing what you're using for such a busy site would be quite illuminating, or would probably just solve our problem, like the rest of the gem does. :+1:

**Comment by jnunemaker** [comment]
As I mentioned, ours looks really similar to the memoizable one here:
https://github.com/jnunemaker/flipper/blob/52471278683a75633d4af29e3f952d3d0934e58b/lib/flipper/adapters/memoizable.rb

Just remove the if memoizing checks and you are pretty darn close.

**Comment by nruth** [comment]
Thanks for the nudge in the right direction. I misunderstood similar as similar concept or functionality.

**Comment by AlexWheeler** [comment]
This is great and I've been thinking a bit about it.  A wrapper for an adapter would work well, but looking at `Flipper::Adapters::Memoizable`'s initialize function it takes a `cache` argument.  What do you think of instead of making a wrapper for an adapter we made a Memcached  class that satisfies the cache interface.  Down the line if you want to use different caches you could still use the same memoizable middleware and class, but just make caches satisfy the cache interface.  Could even make shared cache tests

**Comment by jnunemaker** [comment]
Memoizable should always be in memory and should be used regardless of any other outside caching you use. The goal of memoizable is to avoid repeated network calls for the same data. The goal of a memcached adapter is the same concept, but I don't think we want to merge them as a memcached adapter would be more about repeated network calls to a downstream storage system (aka mysql or whatever). I see it more like layers of caches. You want one in memory to prevent duplicate calls during a request and another do prevent duplicate calls (ie: memcached) in a time window to a slower, more complex data store (ie: mysql).

I don't think it makes sense to introduce a new concept like a cache. I actually really like that there is just one concept (adapter) and that you can adapt it to whatever you need from a performance standpoint. 

Thoughts?

**Comment by jnunemaker** [comment]
Closed by #132. We now have a [dalli adapter](https://github.com/jnunemaker/flipper/blob/master/lib/flipper/adapters/dalli.rb). We could probably add a Rails.cache one too.
